### ISSUE TITLE
Mixed units display on the timeline graph.

### ISSUE THREAD

**Issue by vysogot** [DataDog/documentation#10008]
**Describe the bug**
The units from the Y-axis are not displayed properly, both on the graph and in the legend.

**To Reproduce**
Have an agent that observes Redis (my example):
1. Go to your Redis dashboard
2. Click on creating timeline new graph
3. Set it up like below

![Screenshot 2021-03-12 at 09 24 30](https://user-images.githubusercontent.com/165690/110913338-4a5b9580-8315-11eb-98af-6d790cf2e6db.png)

![Screenshot 2021-03-12 at 09 24 53](https://user-images.githubusercontent.com/165690/110913356-52b3d080-8315-11eb-8f5a-933462f71522.png)

**Expected behavior**
The `memory usage` should be displayed with MB (or MiB) while the number of keys as they are. Also, there should be the right hand side unit of MB or MiB.

**Comment by vysogot** [comment]
I tried to do changes to JSON, after watching the Datadog 101 videos, but it didn't help. How should the JSON look like? Here is the present one before any changes:

```
{
    "viz": "timeseries",
    "requests": [
        {
            "q": "avg:redis.keys{$scope}",
            "type": "line",
            "style": {
                "palette": "dog_classic",
                "type": "solid",
                "width": "normal"
            }
        },
        {
            "q": "avg:redis.mem.used{$scope}",
            "type": "line",
            "style": {
                "palette": "dog_classic",
                "type": "solid",
                "width": "normal"
            },
            "on_right_yaxis": true
        }
    ],
    "yaxis": {
        "max": "auto",
        "scale": "linear",
        "min": "auto",
        "label": "",
        "includeZero": true
    },
    "right_yaxis": {
        "max": "auto",
        "scale": "linear",
        "min": "auto",
        "label": "",
        "includeZero": true
    },
    "markers": []
}
```

**Comment by apigirl** [comment]
Hi @vysogot,

Feel free to reach out to our [awesome support team](https://docs.datadoghq.com/help/) - they can definitely help you get this sorted out. Since this isn't docs specific feedback, I am going to close this issue.

Kaylyn
