### ISSUE TITLE
Timeseries widget displays data points that don't exist

### ISSUE THREAD

**Issue by elvis-xianghai-fan** [DataDog/documentation#10015]
**Describe the bug**
I sent 3 Gauge data points with different tag values to the same metric in the interval of 60 seconds. The first and second data points were duplicated in the Timeseries widget.

**To Reproduce**
1. Sent the metric data points to the datadog agent using bash.
```
/ # date && echo -n "test.metric:10|g|#tag1:a" | nc -w 1 -uv 10.26.0.84 8125
Mon Mar 15 01:29:06 UTC 2021
10.26.0.84 (10.26.0.84:8125) open
/ # sleep 60
/ # date && echo -n "test.metric:20|g|#tag1:b" | nc -w 1 -uv 10.26.0.84 8125
Mon Mar 15 01:30:08 UTC 2021
10.26.0.84 (10.26.0.84:8125) open
/ # sleep 60
/ # date && echo -n "test.metric:30|g|#tag1:c" | nc -w 1 -uv 10.26.0.84 8125
Mon Mar 15 01:31:10 UTC 2021
10.26.0.84 (10.26.0.84:8125) open
/ #
```
`10.26.0.84` is my agent IP.

2. Display the metric data using a Timeseries widget. (See the screenshot below.)

**Expected behavior**
Data points `test.metric:10` and `test.metric:20` should only be shown once at 01:29 UTC and 01:30 UTC respectively.

**Screenshots**
![image](https://user-images.githubusercontent.com/48536649/111093464-f26e9a00-8573-11eb-9cea-ea157bcc7440.png)

**Desktop (please complete the following information):**
 - OS: maxOS 10.15.7
 - Browser: Chrome
 - Version: 88.0.4324.192

**Comment by elvis-xianghai-fan** [comment]
Some more information: if I choose `from: tag1:a`, the Timeseries does show there's only one data point!
![image](https://user-images.githubusercontent.com/48536649/111093891-f2bb6500-8574-11eb-8efa-9f70cce22667.png)

**Comment by apigirl** [comment]
Hi @elvis-xianghai-fan,

Feel free to reach out to our [awesome support team](https://docs.datadoghq.com/help/) - they can definitely help you get this sorted out. Since this isn't docs specific feedback, I am going to close this issue.

Kaylyn
