### ISSUE TITLE
Missing Link for Learning JSON View

### ISSUE THREAD

**Issue by knowledgewarrior** [DataDog/documentation#1006]
Graphing primer page (http://docs.datadoghq.com/graphing/) is missing a link to in #4 where it says, "For more about using the JSON view, scroll to the bottom and click the Learn about the JSON tab link."  

I scroll to the bottom but there's no link to click. 

Would be nice to have more about using JSON for the API and what's available.  eg, what values to use for querying, etc.  I only see, "rollback" on the doc page, eg.

**Comment by technovangelist** [comment]
good catch, added the link that is up at the top to this point as well.
