### ISSUE TITLE
Ambiguous reference to info command

### ISSUE THREAD

**Issue by GoodMirek** [DataDog/documentation#1011]
Reference to info command on page http://docs.datadoghq.com/integrations/rabbitmq/ is ambiguous. While onboarding as a new customer, I have no idea what is meant by that.

**Comment by technovangelist** [comment]
Hmm, good point. We will look into adding a filter that will do a search and replace of things like this with a link to the introduction to the agent page that lists the commands.

**Comment by technovangelist** [comment]
hey there, 

I added a feature to the docs so that every mention of the 'info command' has been updated to a link to the corresponding page. thanks for catching that.
