### ISSUE TITLE
Custom Colors Metric Barplot 

### ISSUE THREAD

**Issue by holzben** [DataDog/documentation#10137]
**Is your feature request related to a problem? Please describe.**
We are using metrics for our bar charts and we like to have custom colors according to state or more generic according to a certain criteria, e.g. OK -> green bar, error -> red bar.

**Describe the solution you'd like**
Add a feature to the color scaling where you can select an attribute eg state, https response and a color to select next to it. 

**Describe alternatives you've considered**
Add the feature to the json mode, eg user adds a array of custom colors

**Additional context**
With log counts we always made the hacky solution via editing the colors directly in the json view,
but did not work for metrics (at least for me ).

**Comment by apigirl** [comment]
Hi @holzben ,

Feel free to reach out to our [awesome support team](https://docs.datadoghq.com/help/) - they can definitely help you get this sorted out. Since this isn't docs specific feedback, I am going to close this issue.

Kaylyn
