### ISSUE TITLE
Getting frequently occurrence of statement: select AURORA_VERSION(); in RDS Prod DB server log files

### ISSUE THREAD

**Issue by mpalam7** [DataDog/documentation#10133]
## Issue Description
Noticed following:
very frequently occurrence of statement: select AURORA_VERSION(); in our RDS Prod DB server log files.

Verified it is coming from following App server for Datadog-agent:
datadog-agent	(IP address: 10.186.157.6)
datadog-agent        (IP address: 10.186.142.0
and also from our other App servers.

This is a strange that we do not have any AWS Aurora instance only we have AWS RDS instance.

Could you please verify it from your end for any issues from DataDog side since we are investigating about this issue actively.

Thanks,
Mohammad

**Comment by mpalam7** [comment]
Hi there,

Could you please assign this request/ticket to someone to have a look into this issue why this is happening and suggest us as earliest possible.

Thanks,
Mohammad

**Comment by apigirl** [comment]
Hi @mpalam7,

Feel free to reach out to our [awesome support team](https://docs.datadoghq.com/help/) - they can definitely help you get this sorted out. Since this isn't docs specific feedback, I am going to close this issue.

Kaylyn
