### ISSUE TITLE
aws.sqs.approximate_age_of_oldest_message not listed

### ISSUE THREAD

**Issue by kanet77** [DataDog/documentation#1015]
[Datadog-AWS SQS Integration](http://docs.datadoghq.com/integrations/awssqs/) lists available metrics. I see `aws.sqs.approximate_age_of_oldest_message` in DataDog but it is not listed on that page.

It might also make sense to update the [Monitor Amazon SQS message traffic with Datadog](https://www.datadoghq.com/blog/monitor-amazon-sqs-message-traffic-datadog/) with this new metric.

**Comment by irabinovitch** [comment]
@tmichelet reasonable to add this to the metric metadata csv?

**Comment by tmichelet** [comment]
Absolutely, I think aws released new sqs metrics too so let's check on this

**Comment by l0k0ms** [comment]
Hello Humans, 

This is now up to date, 

Thanks for the feedback.
