### ISSUE TITLE
Interpolation for indexed spans and logs

### ISSUE THREAD

**Issue by nickfiacco-bolt** [DataDog/documentation#10160]
**Is your feature request related to a problem? Please describe.**
I want to be able to graph logs/spans and default the value to 0 when there is no data.

**Describe the solution you'd like**
Interpolation (at least default zero) for logs and indexed spans.

**Describe alternatives you've considered**
Using metrics instead of logs/spans. This doesn't work because we don't want to have a separate metric when we already have the span/log data.

**Comment by apigirl** [comment]
Hi @nickfiacco-bolt,

Feel free to reach out to our [awesome support team](https://docs.datadoghq.com/help/) - they can definitely help you get this sorted out. Since this isn't docs specific feedback, I am going to close this issue.

Kaylyn
