### ISSUE TITLE
Datadog APM is killing Java process in Jira Instance.

### ISSUE THREAD

**Issue by vallamad** [DataDog/documentation#10305]
## Issue Description
Hello Team,
We have configured DD monitors for Jira Application. Recently we have tried to upgrade Jira Application to the latest version, but the Jira Application was stopped intermittently post upgrade activity. When we contacted to the Atlassian team regarding this issue they have suspected that the Data Dog APM is killing the Java process in the Jira instance and suggested to disable the  Data Dog APM argument in the Jira instance. The issue got resolved once we disabled the Data Dog APM in the Jira instance configuration file. But we can't run the Jira instance without monitoring in production,

Could you please investigate why the DD APM is killing the Java process. Please let me know if you need any info.

Thanks
Madhu

**Comment by apigirl** [comment]
Hi @vallamad,

Feel free to reach out to our [awesome support team](https://docs.datadoghq.com/help/) - they can definitely help you get this sorted out. Since this isn't docs specific feedback, I am going to close this issue.

Kaylyn
