### ISSUE TITLE
Datadog-AWS ElastiCache Integration Doc Out of Date

### ISSUE THREAD

**Issue by bergbrains** [DataDog/documentation#1032]
I am troubleshooting my datadog/aws/elasticache/memcached integration and was following [this page](http://docs.datadoghq.com/integrations/awselasticache/), but it's out of date.  Needs to be deprecated and replaced.

The cacheid is already set to the name of the cluster.  werks gud.

Thanks!

Eric

**Comment by l0k0ms** [comment]
Hello, 

This issue has been fixed.

Many thanks for your feedback,
