### ISSUE TITLE
Datadog agent setup wizard ended prematurely : #7932

### ISSUE THREAD

**Issue by knanaiah001** [DataDog/documentation#10339]
Hi Team ,

I'am facing below issue while installing Datadog agent in my system. Installation is failing with dialog box "Datadog agent setup wizard ended prematurely" even with valid API key. Could check on this?
Operating system :win 10, 64 bit
I have uploaded the windows installer log file and error screenshot 
[MSI76e5d.LOG](https://github.com/DataDog/documentation/files/6344349/MSI76e5d.LOG)

![datadog](https://user-images.githubusercontent.com/68857336/115414209-7838d180-a213-11eb-9db7-21bba1afdf8a.PNG)

**Comment by knanaiah001** [comment]
Hi Team,
any update

**Comment by apigirl** [comment]
Hi @knanaiah001,

Feel free to reach out to our [awesome support team](https://docs.datadoghq.com/help/) - they can definitely help you get this sorted out. Since this isn't docs specific feedback, I am going to close this issue.

Kaylyn
