### ISSUE TITLE
set-cookie for synthetic tests not working

### ISSUE THREAD

**Issue by saschareza** [DataDog/documentation#10348]
**Describe the bug**
Not possible to set cookies with the advanced features in synthetic browser tests

**To Reproduce**
1. Go to Synthetic Tests
2. Create a new browser test
3. Open the advanced settings
4. Follow the set-cookie syntax as described here: https://docs.datadoghq.com/synthetics/browser_tests/ and here https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie
5. Start the recording
6. iFrame loads, but the application in the iFrame has no cookies set

**Expected behavior**
Cookies should be set

**Screenshots**

**Desktop (please complete the following information):**
Tried with all available synthetic browsers

**Comment by saschareza** [comment]
It does work if the test runs, but configuring the test in datadogs iFrame with the set cookie feature is not possible.

**Comment by apigirl** [comment]
Hi @saschareza 

Feel free to reach out to our [awesome support team](https://docs.datadoghq.com/help/) for any future issues like this, they can definitely help you.

Kaylyn
