### ISSUE TITLE
iphone/applestore/scam

### ISSUE THREAD

**Issue by stef5678** [DataDog/documentation#10359]
for the last 2 years there has been cheated with my i-tunes payment. i have paid too much. it seems like a little more than 2 years ago a person hacked my apple account maybe by taking my sim card or hack my phone. the person bought for lots of money on apple-store and got it delivered to cambodia or elsewhere. i had to pay for apple-products and apple-education. i lost lots of money that way. please help me getting my money back?
from stefan

**Comment by apigirl** [comment]
Hi @stef5678 - this is a Datadog repo, not an Apple one. You might try here to get customer support from Apple - https://support.apple.com/

Closing this since it is not a Datadog or Datadog docs issue.

**Comment by stef5678** [comment]
thank you kaylin

---
_Stefan _

Kaylyn skrev den 2021-04-22 21:42:
