### ISSUE TITLE
Global Variables not accessible for Cookies in Synthetic Tests

### ISSUE THREAD

**Issue by saschareza** [DataDog/documentation#10354]
**Describe the bug**
Global Variables can't be used to set cookie values in synthetic browser tests

**To Reproduce**
1. Go to Synthetic Tests
2. Create a new browser test
3. Chose advanced options
4. Create a cookie and chose a global variable as value
5. Run the test
6. Error - see screenshot below

**Expected behavior**
Global variables should be accessible for synthetic browser tests

**Screenshots**
![image](https://user-images.githubusercontent.com/65445188/115533530-18840a00-a297-11eb-81b7-f7c28126a0a4.png)
![image](https://user-images.githubusercontent.com/65445188/115533589-29348000-a297-11eb-93f7-25a57e5b86f5.png)

**Comment by apigirl** [comment]
Hi @saschareza,

Feel free to reach out to our [awesome support team](https://docs.datadoghq.com/help/) - they can definitely help you get this sorted out. Since this isn't docs specific feedback, I am going to close this issue.

Kaylyn
