### ISSUE TITLE
Helm chart : Kube state metrics

### ISSUE THREAD

**Issue by karthickkalirajan** [DataDog/documentation#10382]
## Documentation Page
https://artifacthub.io/packages/helm/datadog/datadog/2.11.2

## Issue Description
Currently we are using   datadog_helm_chart_version 2.4.7 which comes with kube-state-metrics v1.9.7  (quay.io/coreos/kube-state-metrics:v1.9.7).
https://artifacthub.io/packages/helm/datadog/datadog/2.4.7
We have latest helm chart version where its mentioned as dependencies kube-state-metrics=2.13.0 
https://artifacthub.io/packages/helm/datadog/datadog/2.11.2
We require kube-state-metrics v.2.0.0 to support collecting metrics from our aks cluster 1.19.x

NAME                         READY   UP-TO-DATE   AVAILABLE   AGE   CONTAINERS           IMAGES
datadog-cluster-agent        1/1     1            1           30d   cluster-agent        datadog/cluster-agent:1.8.0
datadog-kube-state-metrics   1/1     1            1           30d   kube-state-metrics   quay.io/coreos/kube-state-metrics:v1.9.7

Q1. Assuming that the helm chart for datadog agent will be bundled with kube-state-metrics. When do we expect the kube-state-metrics v2.0.0 or above bundled with helm chart of datadog agent ?
Q2. Should we deploy the kube-state-metrics separately using another helm chart before deploying datadog agent helm chart ? 
Q3. Please advise the preferred method.

Thank you
Karthick K

**Comment by apigirl** [comment]
Hi @karthickkalirajan,

Feel free to reach out to our [awesome support team](https://docs.datadoghq.com/help/) - they can definitely help you get this sorted out. Since this isn't docs specific feedback, I am going to close this issue.

Kaylyn
