### ISSUE TITLE
Cannot login to app.datadoghq.com

### ISSUE THREAD

**Issue by rbecksdx** [DataDog/documentation#10389]
Hi,
When trying to log in with my user: rodolphe.beck@sodexo.com I get a "login error"
When trying to reset my password, I get "Sorry, there was a problem processing the request. Please try again."

I already tried several times.

Can you please help me recover my account?

Thanks.

**Comment by sarina-dd** [comment]
Hi @rbecksdx, sorry to hear you're having trouble with accessing your account. You can contact our [support team](https://www.datadoghq.com/support/) and they can help you get this sorted out. Since this isn't docs specific feedback, I am going to close this issue.

Thanks,
Sarina
