### ISSUE TITLE
Datadog client libraries for microservices compatibility with Datadog agent version on AKS cluster

### ISSUE THREAD

**Issue by karthickkalirajan** [DataDog/documentation#10383]
**Is your feature request related to a problem? Please describe.**
When updating datadog cluster agents on nodes in the AKS cluster, its expected to inform developers on the datadog agent which should also be updated in the application services (microservices).
client libraries:
1. dd-trace
2. dd-trace-java
3. dd-java-agent

**Describe the solution you'd like**
Is there a document which describes the compatibility matrix of datadog agents running on the AKS clusters with the client libraries  ? 
for example 
datadog agent-verison  -->  java-agent-version
1.8.0                               --> 0.75.0

**Describe alternatives you've considered**
A document of cluster agent versions and client agent versions to be published

**Additional context**

**Comment by apigirl** [comment]
Hi @karthickkalirajan,

We don't have any plans for a docs page like this, but our [awesome support team](https://docs.datadoghq.com/help/) can definitely help you figure out what you need to know.

Kaylyn
