### ISSUE TITLE
Unable to get the APM traces for nodes

### ISSUE THREAD

**Issue by Smruti-panda** [DataDog/documentation#10405]
## Issue Description
We are able to get the processes listed for the node - aw01apptalappd002 but the APM traces are not getting registered. Tom was helping use out in setting things up and troubleshooting the issues, we have tied all that and it still does not show up. 

Logging up the support case as advised by Tom, Please help. 
[Re_ Datadog Trial with TE - APM config with Smruti.zip](https://github.com/DataDog/documentation/files/6383680/Re_.Datadog.Trial.with.TE.-.APM.config.with.Smruti.zip)

**Comment by apigirl** [comment]
Hi @Smruti-panda,

Feel free to reach out to our [awesome support team](https://docs.datadoghq.com/help/) - they can definitely help you get this sorted out. Since this isn't docs specific feedback, I am going to close this issue.

Kaylyn
