### ISSUE TITLE
Inconsistent average values on kubernetes.cpu.requests showing on Time Series dashboard

### ISSUE THREAD

**Issue by spaem66** [DataDog/documentation#10442]
**Environment**
The monitored environment is an openshift 3.11 cluster based on RHEL kernel 3.10.0-1062.13.1.el7.x86_64, datadog agent is 7.24.1. All the VM are the same Linux version.

**Describe the bug**
We defined a Time Series based dashboard in order to plot Kubernetes.cpu.requests values for an openshift 3.11 cluster. When we limit the plot to the last month, the lines are correctly represented, like in the picture below:
 
![image](https://user-images.githubusercontent.com/26812173/116520493-17745d80-a8d3-11eb-8621-4fc2c986153d.png)

As you can see, the sum of the requests is under the cluster total capacity. 
But, extending the time range from 1 month to a quarter, the values are the following:

![image](https://user-images.githubusercontent.com/26812173/116520541-265b1000-a8d3-11eb-8ea1-e943f8502010.png)

Here, you can see that the lines swapped and the total capacity is under the sum of the requests (clearly incorrect!).
We also tried to select one single past month (e.g: January, February, march, …) but the values are correctly shown, so, we guess this is not a problem related to the data but to the way data are summarized on a quarter.
**To Reproduce**
1)	just access the dashboard an try by yourself: https://app.datadoghq.eu/dashboard/9fz-c2k-k5s/ocp-svil2-bip?from_ts=1611910989000&live=true&to_ts=1619683389000 
2)	switch the global time from 1 month to 3 months and you will see the problem

**Expected behavior**
Considering that underlaying data are correctly sampled by the agent, the dashboard should plot consistent values over various time ranges

**Screenshots**
See descriptions above.

**Desktop (please complete the following information):**
 - OS: [Windows 7 / 10]
 - Browser [chrome]
 - Version [86.0.4240 / 90.0.4430.72]

**Comment by apigirl** [comment]
Hey @spaem66, 

Same as the other one you opened, [our support team](https://docs.datadoghq.com/help/)  is much better equipped to help you! Since this isn't docs specific feedback, I am going to close this issue.

Kaylyn
