### ISSUE TITLE
Inconsistent average values shown in a Query Values dashboard

### ISSUE THREAD

**Issue by spaem66** [DataDog/documentation#10440]
**Environment**
The monitored environment is an openshift 3.11 cluster based on RHEL kernel 3.10.0-1062.13.1.el7.x86_64, datadog agent is 7.24.1. All the VM are the same Linux version.

**Describe the bug**
We are using a Time Series dashboard (https://datadoghq.eu/dashboard/9fz-c2k-k5s/ocp-svil2-bip?from_ts=1617088073593&live=true&to_ts=1619680073593 ), in order to monitor several metrics belonging to our svil2 openshift cluster. Is is a cluster composed by vmware VMs divided in 3 roles: master nodes (3), infra nodes (4), worker nodes (13).
 
![image](https://user-images.githubusercontent.com/26812173/116517065-b5195e00-a8ce-11eb-99dc-cce913575928.png)

This dashboard uses 2 kinds of data: the top values (green in figure above) are cpu requests average over all the cluster nodes; the top list shows the same data 
The top Query Value plots: (Kubernetes.cpu.requests/ Kubernetes.cpu.capacity) x 100, ordered with “SumBy”, while the Top list (blue stripes) plots the same metrics but using the “SumBy Host” filter.
When we switch the time parameter from 1 minute to 1 month we see that the Query Value shown is not consistent with the average value shown in the Top List. Here is an example:
 
![image](https://user-images.githubusercontent.com/26812173/116517133-ce220f00-a8ce-11eb-8112-8dfc82919db7.png)

As you can see, the average on the Compute seems to be 86,57 while, calculating the average on the values shown in the Top List you can easily calculate a 67,88. The same applies to the Master Nodes Top List in the bottom (not shown in figure).
It seems that extending the time range from 1 week to more than that the average values in Top List become inconsistent.

**To Reproduce**
1)	https://datadoghq.eu/dashboard/9fz-c2k-k5s/ocp-svil2-bip?from_ts=1617088795533&live=true&to_ts=1619680795533 
2)	Just change the global time value and you will check the problem
**Expected behavior**
We expect to see correct average values (i.e: the global average in the Query Value should match the average on all the nodes in the Top List).

**Screenshots**
See descriptions above.

**Desktop (please complete the following information):**
 - OS: [Windows 7 / 10]
 - Browser [chrome]
 - Version [86.0.4240 / 90.0.4430.72]

**Comment by apigirl** [comment]
Hi @spaem66,

Feel free to reach out to our [awesome support team](https://docs.datadoghq.com/help/) - they can definitely help you get this sorted out. Since this isn't docs specific feedback, I am going to close this issue.

Kaylyn

**Comment by spaem66** [comment]
Hello, already done this afternoon. Officially opened 3 issues to support
(not Git).

Thanks a lot
Emanuele

Il giorno gio 29 apr 2021 alle ore 21:07 Kaylyn ***@***.***>
ha scritto:
