### ISSUE TITLE
Synthetics - Ability to extract text from body of datadog email and set to test variable

### ISSUE THREAD

**Issue by nickhodaly** [DataDog/documentation#10463]
**Is your feature request related to a problem? Please describe.**
Our applications login flow requires a user to input an email address and then enter a one-time-password which will be sent to the entered email address. This one-time-password must be manually entered (not a link that the user can click to login).  Currently there is no way to handle this flow with synthetic monitoring. It seems that you are only able to click links from emails currently.

**Describe the solution you'd like**
We would like a way to access the body of the email, use regex to parse out a specific string we are interested in (from email body) and set that to a test variable. In a subsequent step we would use the test variable to input text into an input element on the page. To re-cap: Enter unique datadog email to start login flow -> retrieve email sent to unique datadog email -> Regex body of email to extract MFA code -> save MFA code to variable -> use variable (MFA code) to enter into verification code input element on our verify page -> click verify button.

**Describe alternatives you've considered**
We attempted to use the existing email feature in datadog synthetics but it only supports clicking links in an email.

**Additional context**

Discussion in Slack:
https://datadoghq.slack.com/archives/CHK12ELBG/p1620038172209000?thread_ts=1619544607.183700&cid=CHK12ELBG
![Screen Shot 2021-05-03 at 11 42 14 AM](https://user-images.githubusercontent.com/54045346/116918421-b7e4bd80-ac04-11eb-85be-b74d98702f46.png)

**Comment by nickhodaly** [comment]
cc @MargotLepizzera

**Comment by MargotLepizzera** [comment]
Thanks a lot @nickhodaly! We actually track feature requests via support ticket and I saw that you opened one with Diana & Trejon that landed in our product backlog. So if that's fine with you I'm going to close that issue and we will follow up about that on the support ticket thread!
