### ISSUE TITLE
Wrong correlation between logs and traces of services of custpro.css and others like IDAM

### ISSUE THREAD

**Issue by robaca** [DataDog/documentation#10466]
**Describe the bug**
We see unrelated logs and trace info for some of our requests. Also, the trace infos from person-self-servce and IDAM are not correctly correlated in general (for example person-self-service requests are missing trace infos from sub-requests to IDAM).

**To Reproduce**
1. Go to https://metrodigital.datadoghq.eu/apm/trace/5752378242923514273?env=prod&graphType=flamegraph&shouldShowLegend=true&spanID=8992252297792728456&spanViewType=logs
1. Check the logs. You see logs from IDAM but also completely unrelated logs from custpro cdm3-data and person-self-service.

**Expected behavior**
We are able to see only all logs for one request independent of service boundaries.

**Screenshots**

**Comment by robaca** [comment]
I accidently created a bug report here because of the "Submit a request" Button on the [support page](https://www.datadoghq.com/support/). This might need some UX improvement.

**Comment by apigirl** [comment]
Oooh, yeah, thank you for letting us know that the button goes to an odd place!
