### ISSUE TITLE
Misleading "Submit A Request" button

### ISSUE THREAD

**Issue by zboni-gpsw** [DataDog/documentation#10531]
**Is your feature request related to a problem? Please describe.**
The "Submit A Request" button at https://www.datadoghq.com/support/ leads to this Datadog/Documentation Issues page. This is confusing because I would expect it to go to a general request form.

**Describe the solution you'd like**
Change the button text

**Comment by Ritish-Madan** [comment]
Exactly this Is what happened to me as well.

**Comment by apigirl** [comment]
thank you both, this is very weird and we didn't know it was linked from this page. We just pushed an update and it should be live in the next few hours!

If you are looking to make a general functionality request, you should still submit it to our support team. They keep track of all of them and they will be able to let you know when/if Datadog moves forward with your request.
