### ISSUE TITLE
Remove decimal from top list on dashboard

### ISSUE THREAD

**Issue by shayh1** [DataDog/documentation#10534]
<!-- Is this a documentation issue? If not, and you need help with using Datadog, please contact our support team at https://docs.datadoghq.com/help/ --!>

## Issue Description

hi

im trying to remove decimals from top list widget in dashboard. please help

**Comment by apigirl** [comment]
Hi @shayh1,

Feel free to reach out to our [awesome support team](https://docs.datadoghq.com/help/) - they can definitely help you get this sorted out. Since this isn't docs specific feedback, I am going to close this issue.

Kaylyn
