### ISSUE TITLE
API reference breadcrumbs are redundant

### ISSUE THREAD

**Issue by stevedatadog** [DataDog/documentation#10623]
## Documentation Page
[API Reference main page](https://docs.datadoghq.com/api/latest)

## Issue Description
Breadcrumbs on API reference are redundant. 
![image](https://user-images.githubusercontent.com/64433046/118874884-42cde500-b8a0-11eb-9e60-bab2eeeacb8a.png)

**Comment by bgdeutsch** [comment]
thanks for flagging @stevedatadog!   this is been resolved with #10670.
