### ISSUE TITLE
Broken Link for AWS integration configuration info

### ISSUE THREAD

**Issue by NouemanKHAL** [DataDog/documentation#10803]
## Documentation Page
[https://docs.datadoghq.com/api/latest/aws-integration/#generate-a-new-external-id](https://docs.datadoghq.com/api/latest/aws-integration/#generate-a-new-external-id)

## Issue Description
Under the **Generate a new external ID** endpoint, the link referring to **Datadog AWS integration configuration info** is broken, the broken link is: https://github.com/DataDog/documentation/blob/master/integrations/amazon_web_services/#installation

**Comment by jirikuncar** [comment]
closed via #10954
