### ISSUE TITLE
Stable Helm repository is deprecated

### ISSUE THREAD

**Issue by kbreit** [DataDog/documentation#10834]
## Documentation Page

https://docs.datadoghq.com/agent/kubernetes/?tab=helm

## Issue Description
This documentation points to stable but the stable repository has been deprecated. This change should be made that make any references to the stable Helm repository.

**Comment by apigirl** [comment]
Hey @kbrei, thanks for letting us know, it looks like we updated everything except this example when we migrated into https://github.com/DataDog/helm-charts
