### ISSUE TITLE
Do you integration with Icinga?

### ISSUE THREAD

**Issue by clofresh** [DataDog/documentation#110]
Since Icinga is a fork of Nagios, you should be able to use the Nagios integration to pull in Icinga events. In your `datadog.conf`, just set:

```
nagios_log: /var/log/icinga/icinga.log
```

Or where ever the Icinga server log lives, if you moved it from the standard location.

**Comment by pabloheimplatz** [comment]
Sorry for commenting on this very old Issue again.
Is there any option or plans to support also collecting data from Icinga v2 in Datadog?
