### ISSUE TITLE
Fix python documentation

### ISSUE THREAD

**Issue by c0rv4x** [DataDog/documentation#11067]
https://docs.datadoghq.com/tracing/connect_logs_and_traces/python/#no-standard-library-logging

The docs here have the code which cannot be executed. Could you guys give this a look?

**Comment by apigirl** [comment]
hi @c0rv4x - thanks, we can definitely take a look. which line specifically is giving you trouble?

**Comment by c0rv4x** [comment]
The big one under the link I have sent in the initial message. For example, here are the errors I can see:

![photo_2021-07-12_22-17-55](https://user-images.githubusercontent.com/7037785/125343685-075f0c80-e35f-11eb-8881-bdb7aa2ac960.jpg)

**Comment by Yun-Kim** [comment]
Hi @c0rv4x, I've made a PR for fixing the undefined variable and typo, thanks for the notes!

**Comment by c0rv4x** [comment]
@Yun-Kim Hi!


Thanks! I would say you don't need `import ddtrace` then
