### ISSUE TITLE
[JP,日本語] Link in the monitoring guide should be fixed. 

### ISSUE THREAD

**Issue by toolyee** [DataDog/documentation#1112]
There are 3 link to Monitoring Reference page and 2 of the 3 liked to English version, not to Japanese version.
http://docs.datadoghq.com/ja/guides/monitoring/

**Comment by jhotta** [comment]
I will fix this issue after the following PR is merged.
https://github.com/DataDog/documentation/pull/1108

**Comment by jyee** [comment]
#1108 has merged.

**Comment by jhotta** [comment]
OK will look at it, now.

**Comment by jhotta** [comment]
OK will look at it, now.
