### ISSUE TITLE
Datadog agent ECS sample JSON files link to compressed files

### ISSUE THREAD

**Issue by SebastiaanKlippert** [DataDog/documentation#11216]
## Documentation Page
https://docs.datadoghq.com/agent/amazon_ecs/?tab=awscli

## Issue Description
`For Linux containers, download datadog-agent-ecs.json (datadog-agent-ecs1.json if you are using an original Amazon Linux 1 AMI). `
The files datadog-agent-ecs.json and datadog-agent-ecs1.json are currently linking to compressed/zipped files while they download with a JSON extension. This makes it unreadable when opening with the default editor.
https://docs.datadoghq.com/resources/json/datadog-agent-ecs.json

The windows example is a JSON file which I think is the intended format.

**Comment by nsollecito** [comment]
Hi @SebastiaanKlippert we found the issue here and deployed a fix. Thanks for reporting!
