### ISSUE TITLE
Make it easier to find filebeat integration versions

### ISSUE THREAD

**Issue by OpeOnikute** [DataDog/documentation#11379]
I was using the filebeat integration for the first time and found it difficult to know what the integration versions were. Had to do some digging to figure out to check the changelog.

I've created a PR to address this [here](https://github.com/DataDog/integrations-extras/pull/953), but seen that I need to notify the docs team here as well.

**Comment by apigirl** [comment]
hey @OpeOnikute - thanks for the PR to fix and thanks for letting us know!
