### ISSUE TITLE
Serverless Go page misses some key information

### ISSUE THREAD

**Issue by speza** [DataDog/documentation#11393]
## Documentation Page

https://docs.datadoghq.com/serverless/installation/go

## Issue Description

1.

The page primarily guides users to use the Lambda Extension (https://docs.datadoghq.com/serverless/installation/go/#install-the-datadog-lambda-extension). 

Lambda Extensions are not supported with the `go1.x` runtime (https://docs.aws.amazon.com/lambda/latest/dg/using-extensions.html)

The issue is you have to have your Lambda setup in a very specific way to use Lambda Extensions with Go. You have to awkwardly use `provided.al2` over the standard `go1.x` runtime. 

I suspect the majority of Lambda users are still using `go1.x` and not `provided.al2`. So Lambda Extension won't be an option for people unless they migrate.

I think this doc needs to do a better job of showing the DD Log Forwarder approach vs the Lambda Extension approach. This used to be the case, but since Lambda Extension support has been added to Datadog Lambda Go it has been updated. I would suspect that most people will still require DD Log Forwarder due to the unsupported Lambda Extension in `go1.x`. 

Please see https://github.com/DataDog/datadog-lambda-go/issues/82.

2.

Since this doc guides the user to Lambda Extensions its actually incorrect that a user needs to set `DD_FLUSH_TO_LOG`. I had a look through the Datadog Lambda Go source code and this property isn't needed.

**Comment by tianchu** [comment]
@speza Thanks for your valuable feedback! I'm going to fix these now :)

**Comment by tianchu** [comment]
https://docs.datadoghq.com/serverless/installation/go has been udpated.
