### ISSUE TITLE
Datagram string data escaping rules

### ISSUE THREAD

**Issue by ngrodzitski** [DataDog/documentation#11552]
## Documentation Page

https://github.com/DataDog/documentation/blob/master/content/en/developers/dogstatsd/datagram_shell.md

## Issue Description

What are the escaping rules for events textual data (title,text,aggregation_key,source_type_name and tags)?
Documentation only describes escaping `\n` for text field. Can you please elaborate on other cases:

* `|` symbols in title, text, aggregation_key, source_type_name fields.
* unprintable characters in title, text, aggregation_key, source_type_name fields and tags(keys and values).
* `#` and `:` symbols in tags.

**Comment by apigirl** [comment]
Hi @ngrodzitski,

Feel free to reach out to our [awesome support team](https://docs.datadoghq.com/help/) - they can definitely help you get this sorted out.

We'll also look into getting the docs update here, but our support team will be able to help you much more specifically.

Kaylyn
