### ISSUE TITLE
Installation of datadog lambda extension using SAM is unsecured by definition, add support for DD_API_KEY_SSM_NAME

### ISSUE THREAD

**Issue by roimor** [DataDog/documentation#11787]
## Documentation Page
https://docs.datadoghq.com/serverless/installation/python/?tab=awssam#instrument

## Issue Description
Looking at the datadog lambda extension installation docs using SAM, in the **Instrument** section the user needs to _apiKey_  in an unsecured way. 
I found out that the extension does support using DD_API_KEY_SECRET_ARN or DD_API_KEY_SSM_NAME env vars, to fetch the api key in a secure manner. But the documentation does not mention anything about those two, and doesn't even explain what to do with the `apiKey: <DATADOG_API_KEY>` parameter in the **Instrument** section.

thanks!!

**Comment by cswatt** [comment]
Thank you so much for bringing this up! We'll be enhancing the documentation very soon!

**Comment by roimor** [comment]
@cswatt , thanks! in a technical manner, i would love to know what to do with the `apiKey` parameter in the Transform section, in case i use `DD_API_KEY_SECRET_ARN`
