### ISSUE TITLE
Prometheus integration - collect_counters_with_distributions is not documented 

### ISSUE THREAD

**Issue by stefangluszek** [DataDog/documentation#12191]
<!-- Is this a documentation issue? If not, and you need help with using Datadog, please contact our support team at https://docs.datadoghq.com/help/ --!>

## Documentation Page
https://docs.datadoghq.com/integrations/guide/prometheus-host-collection/

## Issue Description
collect_counters_with_distributions introduced in https://github.com/DataDog/integrations-core/pull/9301 is not documented.

**Comment by ruthnaebeck** [comment]
@stefangluszek - Thanks for reporting! We will look into this.
