### ISSUE TITLE
CloudSecurityPostureManagementPermissions Vs ResourceCollectionPermissions

### ISSUE THREAD

**Issue by tdimnet** [DataDog/documentation#12229]
## Documentation Page

- The English one: https://docs.datadoghq.com/integrations/amazon_web_services/?tab=roledelegation
- The French one: https://docs.datadoghq.com/fr/integrations/amazon_web_services/?tab=d%C3%A9l%C3%A9gationdesr%C3%B4les

## Issue Description

I don't really know if it's a mistake or not but I think there is an issue between the a link in the English and the French documentation :

![Screenshot 2021-11-09 at 16 32 11](https://user-images.githubusercontent.com/9935925/140954401-77e9a795-fa3f-4c8c-a296-d6afaf62dd97.png)

The property `ResourceCollectionPermissions` and the link don't exist in the French doc. In the English version, the property is called `CloudSecurityPostureManagementPermissions`.

![Screenshot 2021-11-09 at 16 36 28](https://user-images.githubusercontent.com/9935925/140954969-924ece86-b1a8-434a-a0d4-8463529b2433.png)

Do I miss something or am I right with this issue? If there is one, let me know and I'll create a PR and update the doc.

**Comment by apigirl** [comment]
Hi @tdimnet - thanks for letting us know about this! We send our docs to translators and the translations are started only when the english version is merged in, so this looks like it is a bit behind, but should be updated soon. Thanks for letting us know though, and next time, feel free to reach out in Slack or on our Jira board!
