### ISSUE TITLE
bitbucket integration page is outdated.

### ISSUE THREAD

**Issue by jhotta** [DataDog/documentation#1230]
Installation & Configuration section of bitbucket page uses a user to read information, but the integration tile uses webhook to read data now.

- http://docs.datadoghq.com/integrations/bitbucket/
- https://app.datadoghq.com/account/settings#integrations/bitbucket
- https://confluence.atlassian.com/bitbucket/manage-webhooks-735643732.html

**Comment by l0k0ms** [comment]
Hello,

The update is on its way, I'm closing this issue then.

Thank you very much for the feedback,
Best,
