### ISSUE TITLE
typo in info command: "sudo datadog-agent info"

### ISSUE THREAD

**Issue by hadasgo** [DataDog/documentation#1237]
Should be "sudo service datadog-agent info"

**Comment by jhotta** [comment]
@hadasgo Thank you for filing an issue.  We could use "sudo service datadog-agent info", but I had made changes according to the rest of docs.

"sudo /etc/init.d/datadog-agent info"

**Comment by hadasgo** [comment]
sure, my pleasure and thanks to you!
