### ISSUE TITLE
possible error/omission in ruby api doumentation

### ISSUE THREAD

**Issue by DougHughes** [DataDog/documentation#1241]
Both Python and Shell API show how to use Series to submit multiple metrics at once. This is very useful because the time to submit many metrics serially is bounded by the HTTP RTTs. It seems like this is plumbed (partially or fully?) into the Ruby v1 api via batch_metrics method, but it's not part of the documentation at all.

**Comment by l0k0ms** [comment]
Hello, 

Thanks for the feedback, doc has been updated!

Best,
