### ISSUE TITLE
Where is the latest version of SNMP integration documentation?

### ISSUE THREAD

**Issue by keisku** [DataDog/documentation#12461]
## Documentation Page

https://github.com/DataDog/documentation/blob/95928d43a4983ccc3271b5c9e717dd5c66f4bd6d/content/en/integrations/faq/snmp.md?plain=1#L8

## Issue Description

This link returns 404.

**Comment by apigirl** [comment]
hey @keisku - the SNMP documentation can all be found under our Network Device Monitoring documentation now - https://docs.datadoghq.com/network_monitoring/devices
