### ISSUE TITLE
Missing Datadog Lambda extension section for container-based Lambdas

### ISSUE THREAD

**Issue by cryptism** [DataDog/documentation#12522]
## Documentation Page
https://docs.datadoghq.com/serverless/libraries_integrations/extension/

## Issue Description

[This blog post](https://www.datadoghq.com/blog/datadog-lambda-extension/) makes reference that the extension works for lambda containers but I can see the section it refers to got removed [here](https://github.com/DataDog/documentation/commit/bba0aa3b04213e03784a70545f9aa6bacfd28e17#diff-959dea06ce27e000a30b869969a19b058fab299a6d01701d30db27fb7dfe7f80L51). Was this intentional? If so, what should container-based lambda function owners do?

**Comment by tianchu** [comment]
@cryptism The instructions were moved to the installations instructions for each individual runtime, for instance, you can find the instructions for Python Lambda using container images https://docs.datadoghq.com/serverless/installation/python/?tab=containerimage.
