### ISSUE TITLE
Inconsistency in ECS Task Definitions

### ISSUE THREAD

**Issue by colinbjohnson** [DataDog/documentation#12596]
## Documentation Page

There are two DataDog Agent ECS Task Definitions "linked to" in various places of DataDog yet the values are different in areas where I would expect them to remain consistent. The two files in question are here:

- https://docs.datadoghq.com/resources/json/datadog-agent-ecs.json
- https://docs.datadoghq.com/json/datadog-agent-ecs-logs.json

## Issue Description

Here are the key areas of difference:

1. `image`: the URL is different in each file (`public.ecr.aws/datadog/agent:latest` versus `datadog/agent:latest`)
2. `cpu`: the CPU is different in each file (either "10" or "100") where I'd expect the _logs_ agent to actually have higher CPU reservation
3. for each `mointPoint` the `readOnly` attribute is either `true` or `null` where I'd expect consistency regardless of the configuration (with the exception of `/opt/datadog-agent/run`)
4. for environment variables, `DD_SITE` is set to `datadoghq.com` or not set at all and `DD_HOST` is used elsewhere in documentation
5. Within `volumes` the source path of the `group` volume is either `/sys/fs/cgroup/` or `/cgroup/` - where I'm not sure what these values should be or if the variation is acceptable and `/host/sys/fs/cgroup` is referenced here: (https://app.datadoghq.com/logs/onboarding/container)

**Comment by kayayarai** [comment]
Hi! We made these consistent, here in the docs: https://github.com/DataDog/documentation/pull/13282 and also in the web ui. Thanks for the report!
