### ISSUE TITLE
[ecs] How to send custom metrics?

### ISSUE THREAD

**Issue by nojo** [DataDog/documentation#1279]
After following the steps in the "Datadog-AWS ECS Integration", I'm left with a DataDog agent running on each ECS server, but the applications running in my other containers can't send custom metrics to it.

**Comment by kmshultz** [comment]
@nojo Can you please follow up with our support team? See https://www.datadoghq.com/support.

Once Support helps you resolve your issue, they'll follow up with the Documentation team and we'll fill in any missing details or troubleshooting steps.

If you have solved this already, let us know how and we can update the documentation. Or, you can always submit a pull request yourself.

Thanks!
