### ISSUE TITLE
The sample in discription differs from the sample Image.

### ISSUE THREAD

**Issue by yutaro1985** [DataDog/documentation#13029]
## Documentation Page

https://github.com/DataDog/documentation/blob/master/content/en/logs/log_configuration/parsing.md
https://docs.datadoghq.com/logs/log_configuration/parsing/

## Issue Description

In the `Overview`  section on the parsing document, sample parsing rule is described as below.

```
MyParsingRule %{word:user} connected on %{date("MM/dd/yyyy"):connect_date}
```

But in the sample image, it is described as below.
```
MyParsingRule %{word:user} connected on %{date("MM/dd/yyyy"):date}
```

https://github.com/DataDog/documentation/blob/master/static/images/logs/processing/processors/_parser.png

It may be a good idea to replace the sample image with a fixed image.

**Comment by wangli1030** [comment]
Hi, I assumed the connect_date is a variable name. If I want to work on this, should I change the connect_date to date in docs, or take another screenshot and replace the image?

**Comment by rat114** [comment]
I will work on it
