### ISSUE TITLE
More information concerning DataDog Proxy Server

### ISSUE THREAD

**Issue by BenCoffeed** [DataDog/documentation#13186]
**Is your feature request related to a problem? Please describe.**
I’ve stumbled across 2 issues where both help articles recommended configuring a proxy server for DD logs. However, the documentation surrounding what is required for the proxy server/service is somewhat lacking.

References:
[Missing Data in RUM](https://docs.datadoghq.com/real_user_monitoring/browser/troubleshooting/#missing-data)
[Cross origin read blocking warning](https://docs.datadoghq.com/real_user_monitoring/browser/troubleshooting/#cross-origin-read-blocking-warning)

**Describe the solution you'd like**
I would like some more clear documentation about provisioning a serverless (Lambda) proxy server. Additionally, Adding something similar to the documentation for configuring the DataDog Forwarder CloudFormation templates wwould be ideal.

**Describe alternatives you've considered**
An alternative that would be acceptable would be custom domains to prevent CORS issues or network filters/tracking blockers.

**Comment by apigirl** [comment]
Hi @BenCoffeed,

Feel free to reach out to our [awesome support team](https://docs.datadoghq.com/help/) - they can definitely help you get this sorted out. The Serverless engineering team is also super responsive on our [Datadog public slack](https://chat.datadoghq.com/). We'll also look at updating the documentation, but these other channels can help with your specific problem sooner. 

Kaylyn

**Comment by BenCoffeed** [comment]
Thanks Kaylyn! I actually spoke with AJ over on the Slack channel thus my presence here :).

**Comment by apigirl** [comment]
Okay, cool! Thanks for letting us know.
