### ISSUE TITLE
Jira Integration Docs need updating

### ISSUE THREAD

**Issue by Talderon** [DataDog/documentation#1328]
Documentation located here is out of date:

http://docs.datadoghq.com/integrations/jira/

The information and instructions provided are out of date and do not cover the required fields in the setup on JIRA's end. 

- Request Token URL: Request Token URL is required.
- Access token URL: Access Token URL is required.
- Authorize URL: Authorize URL is required.

The fields are not in sync and causes confusion as to what data goes where. The documentation states field names:

Datadog
- Consumer key
- Consumer name
- Public key

But in Jira, they are:

JIRA
- Service Provider Name
- Consumer key
- Shared secret

The documentation needs to be more clear and match up to what we are seeing on the screens.

**Comment by l0k0ms** [comment]
Hello, 

Thanks for your feedback! 
After double checking, the screenshots are now up to date
![image](https://user-images.githubusercontent.com/3624790/28562026-fe177388-7120-11e7-9b42-a88a03539fda.png)

Best,

**Comment by jhohertz** [comment]
Not sure why this was closed, the docs are still not correct, and do not cover necessary fields as @Talderon indicated in the original issue text.

**Comment by jeffbyrnes** [comment]
I can confirm the docs do not specify the 3 additional fields that are now required (they did not used to be:

* Request Token URL
* Access token URL
* Authorize URL

![screen shot 2017-09-29 at 12 19 45 pm](https://user-images.githubusercontent.com/260553/31025420-97cac476-a510-11e7-8f27-8ce2b0638d28.png)

**Comment by irabinovitch** [comment]
@l0k0ms @DanielLanger  could you look into this and update the docs and integration tile?

**Comment by l0k0ms** [comment]
Hello, @jeffbyrnes 

Sorry for the delay,
It seems that you are hitting an issue because the “Service Provider Name” has been set in your screenshot. 

You should only fill in the boxes - “Application Name”, “Application Type” and “Create incoming link” at this step as specified in step 8 here https://docs.datadoghq.com/integrations/jira/#installation

Hope that helps, 
Best regards,
Pierre

**Comment by JamesEPohl** [comment]
If anyone is still searching the internet for the answer, you can just enter `https://app.datadoghq.com/` or `/` in those three additional required fields that are missing from the DD docs:

![image](https://user-images.githubusercontent.com/20049892/69461045-aa56b300-0d43-11ea-8983-0df814ae4f88.png)

**Comment by alfresanc** [comment]
Not sure why this was closed, the docs are still not correct, and do not cover necessary fields as @Talderon indicated in the original issue text. Tho,  you can just enter any data in the other required fields just to be able to advance to next step.

**Comment by icodeiexist** [comment]
I up vote following this through, we're heavy DD users and we're extremely interested in having a setup that works, we're currently testing endless combinations that won't work to enable this integration due to docs being incomplete / outdated . Thank you.

**Comment by ruthnaebeck** [comment]
Instructions updated to be clearer on fields that should be left blank.

**Comment by murrayb** [comment]
Instructions should be clearer
