### ISSUE TITLE
Traefik is written wrongly

### ISSUE THREAD

**Issue by dunklesToast** [DataDog/documentation#13442]
While reading the Docs I've noticed that Traefik is written wrong multilpe times. I've already created a patch because I've read too late, that I need to notify you / create an Issue. You can see the patch here: https://github.com/DataDog/integrations-extras/pull/1242
Hope I don't mess up the whole process too much 😅

**Comment by apigirl** [comment]
Hey @dunklesToast - thanks for the PR! This looks good to me and it is a great catch. If you take your PR out of draft mode, we can get it merged in!

**Comment by dunklesToast** [comment]
Hey! PR is now ready for review 🚀

**Comment by apigirl** [comment]
Awesome! Merged. Thanks again!
