### ISSUE TITLE
dns_check docs missing service check info

### ISSUE THREAD

**Issue by masci** [DataDog/documentation#1348]
http://docs.datadoghq.com/integrations/dnscheck/ doesn't mention how the `dns.can_resolve` can be used.

Feedback from a user:
> I’m having an issue getting `dns_check.yaml` to work.  I don’t see it show up under `New Monitor -> Network`… I just saw it show up under Custom Check `dns.can_resolve`

**Comment by l0k0ms** [comment]
Hello Masci, 

The update is on its way, thanks for the feedback!

Best,
