### ISSUE TITLE
Links to the different visualization types under the Select your visualization section go to anchor elements that do not exist

### ISSUE THREAD

**Issue by BeigeBadger** [DataDog/documentation#1353]
The problem is here: http://docs.datadoghq.com/graphing/#select-your-visualization

In the description text for each visualization type there is a link with the text of _click here_ that is supposed to link to an example of that visualization within the current page, but it appears that these elements no longer exist or the id has been changed.

This is the link for the Timeseries example: http://docs.datadoghq.com/graphing/#collapseTimeseries.

**Comment by l0k0ms** [comment]
Hello, this issue is now fixed.

Thanks you very much for your feedback, 

Best,
