### ISSUE TITLE
httpcheck integration: add documentation for reverse_content_match

### ISSUE THREAD

**Issue by iancward** [DataDog/documentation#1382]
A co-worker was looking for a way to invert the content_match for an http check, and I noticed that the code for the integration has a `reverse_content_match` switch that appears undocumented. 

https://github.com/DataDog/integrations-core/blob/master/http_check/check.py#L176
https://github.com/DataDog/integrations-core/blob/master/http_check/check.py#L302-L317

Would it be possible to add this to the documentation for the httpcheck integration?

Thanks!

**Comment by irabinovitch** [comment]
@iancward thanks for catching this, we can definitely address.

**Comment by kmshultz** [comment]
Fixed in #1384.
