### ISSUE TITLE
What is the equivalent of apt-get --purge for Amazon Linux?

### ISSUE THREAD

**Issue by ArashMehraban** [DataDog/documentation#13942]
## Documentation Page

https://github.com/DataDog/documentation/blob/master/content/en/agent/faq/how-do-i-uninstall-the-agent.md

## Issue Description
The above page appears to be missing the instruction on how to remove the following elements under CentOS, RHEL, Fedora, and Amazon Linux. It says how to remove the agent by `sudo yum remove datadog-agent` but not the following elements: 

- the datadog.yaml configuration file,
- user-created files in the /etc/datadog-agent configuration folder,
- user-created files in the /opt/datadog-agent folder,
- the dd-agent user.

In particular I am interested in Amazon Linux as I am doing some automated testing where I need everything removed every time I  run my installation script.

**Comment by apigirl** [comment]
Hey @ArashMehraban,

Thanks for letting us know! We can look at getting this added, but in the meantime, feel free to reach out to our [awesome support team](https://docs.datadoghq.com/help/) - they can definitely help you get this sorted out. 

Kaylyn

**Comment by hestonhoffman** [comment]
Hi @ArashMehraban, I took a look at this one. Unfortunately, there isn't an identical `--purge` command in other Linux package managers, but I added a command [in this PR](https://github.com/DataDog/documentation/pull/13985) that you can use to remove the agent user, config files, and logs.
