### ISSUE TITLE
Broken tables on MySQL Integration Page

### ISSUE THREAD

**Issue by ebpitts** [DataDog/documentation#1405]
https://docs.datadoghq.com/integrations/mysql/ has broken table formatting.

Here's a partial screenshot:

![screen shot 2017-07-13 at 4 04 59 pm](https://user-images.githubusercontent.com/10963385/28187669-1c14f210-67e5-11e7-8fe4-74d9f6511ba6.png)

**Comment by mstbbs** [comment]
thanks for reporting!
