### ISSUE TITLE
Ruby sample code for "Ignoring Unwanted Resources in APM" is out of date

### ISSUE THREAD

**Issue by mleiseca** [DataDog/documentation#14104]
## Documentation Page
https://docs.datadoghq.com/tracing/guide/ignoring_apm_resources/?tab=datadogyaml#tracer-configuration-options

## Issue Description
The code sample for ignoring a trace is only for the < 1.0.0 version of the gem:
```
Datadog::Tracing::Pipeline.before_flush do |trace|
  trace.delete_if { |span| span.resource =~ /Api::HealthchecksController#index/ }
end
```

I think the new equivalent should be
```
Datadog::Tracing::Pipeline.before_flush do |trace|
    trace.spans.delete_if { |span| span.resource =~ /Api::HealthchecksController#index/ }
    trace
end
```

**Comment by kayayarai** [comment]
Hi! Thanks for reporting this! I'll get your suggestion checked with our engineers and update the docs.
