### ISSUE TITLE
ECS Setup Scripts Not Properly Formatted

### ISSUE THREAD

**Issue by vishalkuo** [DataDog/documentation#1429]
https://docs.datadoghq.com/integrations/ecs/

Step 7 under `Create or Modify your IAM Policy` and Step 6 in `Create a new Amazon Linux instance` should be formatted using markdown. The latter code snippet is formatted according to the page's styling which uses terminal-unfriendly characters such as pretty quotes (“ and ” vs "), special double hyphens (– vs --), and more.

**Comment by l0k0ms** [comment]
Hello, 

Thanks for the feedback, fix is on its way!

Best,
