### ISSUE TITLE
Clarify array filter documentation

### ISSUE THREAD

**Issue by ntfc** [DataDog/documentation#14353]
## Documentation Page

https://docs.datadoghq.com/logs/log_configuration/parsing/

### Clarify `subRuleOrFilter` parameter

In https://docs.datadoghq.com/logs/log_configuration/parsing/?tab=filters#matcher-and-filter the `array` filter is documented as having 3 parameters: `array([[openCloseStr, ] separator][, subRuleOrFilter)`. However it is not clear how `subRuleOrFilter` can be used. Can you add some example? And if possible explain how to reference other parsing/helper rules? 

Additionally the example parsing rule in https://docs.datadoghq.com/logs/log_configuration/parsing/?tab=filters#list-to-array is not using double quotes and cannot be copied to Datadog. Could you replace the quotes such that `array(“[]“,”,“)` becomes `array("[]", ",")`?

Thanks!

**Comment by maycmlee** [comment]
Hi there! Thanks for your feedback! We're taking a look into it and will be back in touch.

**Comment by maycmlee** [comment]
Hi! We've fixed the quotes and added an example for the `subRuleOrFilter`: https://docs.datadoghq.com/logs/log_configuration/parsing/?tabs=filters#list-to-array. Thanks again for the feedback!
