### ISSUE TITLE
Clarify lack of GMSA support for agent install

### ISSUE THREAD

**Issue by lowlydba** [DataDog/documentation#14361]
## Documentation Page

https://docs.datadoghq.com/agent/guide/windows-agent-ddagent-user/#installation-in-a-domain-environment

## Issue Description

After working through a support ticket, I was told the current release does not support installing the datadog agent as a GMSA account. This isn't mentioned anywhere in the docs but is an important limitation to note as many folks may be trying/using a managed service account in this scenario.

**Comment by ian28223** [comment]
6/7.38.x released with support for gMSA
- https://github.com/DataDog/datadog-agent/pull/12372
- https://github.com/DataDog/datadog-agent/releases/tag/7.38.0

doc update tbd

**Comment by hestonhoffman** [comment]
This was documented in #14361. Thank you both!
