### ISSUE TITLE
/guides/network_checks redirects to japanese doc

### ISSUE THREAD

**Issue by aspope** [DataDog/documentation#1440]
When setting up a new network monitor, I click the guide link for a doc to create a new endpoint. The link consistently results in a `ja` language URL.

![1](https://user-images.githubusercontent.com/365006/28472506-af9597cc-6df5-11e7-9286-8a42a97c04cb.png)
![2](https://user-images.githubusercontent.com/365006/28472508-b1429a7a-6df5-11e7-82f9-c85057909398.png)

Browser: Google Chrome 59.0.3071.115 (Official Build) (64-bit)
Location: Vancouver, BC, Canada
OS: MacOS 10.12.5

**Comment by mstbbs** [comment]
This redirect is fixed. 
Thanks for reporting.
