### ISSUE TITLE
statsd event function parameters are outdated in documentation

### ISSUE THREAD

**Issue by mlanicaputo** [DataDog/documentation#14457]
# Issue:
The [documentation](https://docs.datadoghq.com/events/guides/dogstatsd/) for the statsd.event() function is out of date. The following parameters are listed in the function documentation:
`event(<TITLE>, <TEXT>, <TIMESTAMP>, <HOSTNAME>, <AGGREGATION_KEY>, <PRIORITY>, <SOURCE_TYPE_NAME>, <ALERT_TYPE>, <TAGS>)`

In the [codebase](https://github.com/DataDog/datadogpy/blob/0957786a1cac70b53bdc4af1cdc574b6ae4d9026/datadog/dogstatsd/base.py#L923), the event() function parameters are listed as follows:

```
def event(
        self,
        title,
        message,
        alert_type=None,
        aggregation_key=None,
        source_type_name=None,
        date_happened=None,
        priority=None,
        tags=None,
        hostname=None,
    ):
```

# Proposal:
This is misleading, as some of the function parameters are in a different order or called something else in the documentation. This could lead to misreported data and difficulties unpacking dictionaries, among other problems. **I propose changing the function parameters in the statsd.event() documentation to reflect the codebase.**

**Comment by kayayarai** [comment]
Thanks! Saw your PR, and will get it reviewed and updated as appropriate.
