### ISSUE TITLE
Consolidate the dotnet-framework and dotnet-core documentation for compatibility requirements.

### ISSUE THREAD

**Issue by zippy1981** [DataDog/documentation#14551]
## Documentation Page

* https://docs.datadoghq.com/tracing/setup_overview/compatibility_requirements/dotnet-framework/
* https://docs.datadoghq.com/tracing/setup_overview/compatibility_requirements/dotnet-core

## Issue Description

Specifically, because of the custom instrumentations, these pages should be merged. Those lists are incomplete. I added a [PR to the Tracer repo](https://github.com/DataDog/dd-trace-dotnet/pull/2953) to remind people to add to the list when they add a new auto instrumentator. However, I just think everything would be simpler if those two pages were combined.

If that is agreed I can submit a PR if that would get it done faster.

**Comment by kayayarai** [comment]
Hi @zippy1981 Thanks Justin, I'll look into this. Did you mean dotnet-framework and dotnet-core pages should be merged? (your issue description links to dotnet-framework twice)

**Comment by zippy1981** [comment]
@kayayarai  yes and i corrected that

**Comment by kayayarai** [comment]
We talked about it internally, and we're going to keep them separated, like most of the rest of the .NET setup instructions. We're prioritizing the experience of the reader -- not having to work through what applies to them or not in a given page -- over simplicity of maintenance. So do continue to point out missing info (as in your PR).
