### ISSUE TITLE
Script missing whitespace

### ISSUE THREAD

**Issue by icco** [DataDog/documentation#1461]
The script under https://docs.datadoghq.com/integrations/ecs/#create-a-new-amazon-linux-instance is missing whitespace and has magic quotes, making it hard to cut and paste and also hard to read.

**Comment by icco** [comment]
I believe the proper formatting should be:

```bash
#!/bin/bash
cluster="cluster_name"
task_def="dd-agent-task"
echo ECS_CLUSTER=$cluster >> /etc/ecs/ecs.config
start ecs
yum install -y aws-cli jq
instance_arn=$(curl -s http://localhost:51678/v1/metadata | jq -r '. | .ContainerInstanceArn' | awk -F/ '{print $NF}' )
az=$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone)
region=${az:0:${#az} - 1}
echo "cluster=$cluster az=$az region=$region aws ecs start-task –cluster $cluster –task-definition $task_def –container-instances $instance_arn –region $region" >> /etc/rc.local
```

**Comment by l0k0ms** [comment]
Hello Icco, 

Thanks for the feedback!
The fix is on its way: https://github.com/DataDog/documentation/pull/1446

I'm going to close this issue for now however If you notice something else on our doc, feel free to open a new one, 
Best,
Pierre
