### ISSUE TITLE
Should US-FED1 have non-FED URL in Jira page?

### ISSUE THREAD

**Issue by jlosito** [DataDog/documentation#14614]
## Documentation

https://docs.datadoghq.com/integrations/jira/#create-an-application-link-in-jira

## Issue Description

I was in the process of configuring Jira with my Datadog account in order to create Jira tickets when events happen. I noticed that in the documentation page linked in the section above under the US-FED1 site the URL under step 4 reads `https://app.datadoghq.com/` but from my experience dealing with the US-FED1 site the URL is usually `https://app.ddog-gov.com`. Is this page correct?

> Enter the URL https://app.datadoghq.com/ and click Create new link.

**Comment by urseberry** [comment]
Thank you so much for bringing this to our attention, jlosito. I'll take a look.

**Comment by jlosito** [comment]
@urseberry Someone from the support team confirmed that this indeed is incorrect. Can you point me to where I should make that update?

**Comment by urseberry** [comment]
@jlosito Most, but not all, of Datadog's documentation is open-source and can be updated by anyone. This particular page comes from a closed-source repository. I can make the update. You are correct that the link is wrong - thanks again for bringing it to our attention so we can fix it.
