### ISSUE TITLE
DD_TRACE_HEALTH_METRICS_ENABLED is true by default not false

### ISSUE THREAD

**Issue by froque** [DataDog/documentation#14639]
## Documentation Page
 * https://docs.datadoghq.com/tracing/trace_collection/library_config/java/

## Issue Description
 Documentation says DD_TRACE_HEALTH_METRICS_ENABLED is false by default, but since commit https://github.com/DataDog/dd-trace-java/commit/ea9c5fb8256f8298b7b7c441a715e9898ce82101 ( Oct 15, 2020, [v0.66.0](https://github.com/DataDog/dd-trace-java/releases/tag/v0.66.0)) is now true by default

**Comment by hestonhoffman** [comment]
Hi @froque! Thanks for the contribution. I've opened a PR to fix this ^
