### ISSUE TITLE
ECS Integration documentation renders text snippets poorly

### ISSUE THREAD

**Issue by mee** [DataDog/documentation#1466]
At https://docs.datadoghq.com/integrations/ecs/

The "Policy Document" text snippet uses "smart quotes" (that is, unicode `LEFT DOUBLE QUOTATION MARK` (`“`) and `RIGHT DOUBLE QUOTATION MARK` (`”`) instead of `QUOTATION MARK` (`"`)) and the asterisk is missing from the resource specifier.

![screenshot from 2017-07-25 12-07-26](https://user-images.githubusercontent.com/63307/28581989-dff47f66-7131-11e7-8fc3-176087d87c58.png)

And the user data text snippet is missing newlines (or semicolons) and uses "smart quotes",

![screenshot from 2017-07-25 12-12-21](https://user-images.githubusercontent.com/63307/28582194-8a585b76-7132-11e7-9935-8ac2329fd2cd.png)

**Comment by l0k0ms** [comment]
Hello Mee, 

Thanks for the feedback the doc have just been updated: https://docs.datadoghq.com/integrations/ecs/

![image](https://user-images.githubusercontent.com/3624790/28583694-5d0b648c-716a-11e7-80ee-650d44bcab75.png)

![image](https://user-images.githubusercontent.com/3624790/28583714-6910cba0-716a-11e7-8c6d-afcc3ea51a3e.png)

Best regards,
Pierre
