### ISSUE TITLE
Get the current timestamp in the dashabord

### ISSUE THREAD

**Issue by mtavaresmedeiros** [DataDog/documentation#14707]
I am try to calculate the uptime of my server, to do it I need the current timestamp in unix format.

Somithing like the time() in the prometheus.

example:
Start time of the process since unix epoch in seconds : 1658224768
Current time since unix epoch in seconds: 1658311494

Uptime = 1658311494 - 1658224768 = 86726s

I need put it in a widget in the dashboard

Actual result :
![image](https://user-images.githubusercontent.com/14811074/179956687-c8508227-6a5c-4a45-8a17-cd8a272ebcf4.png)

What I would like:
![image](https://user-images.githubusercontent.com/14811074/179957164-ffd586ca-4d77-4213-9158-d8fec2929c1b.png)

How I did it:
![image](https://user-images.githubusercontent.com/14811074/179957027-84f8256a-b8b8-430d-aedd-e360ecd099e2.png)

but for sure that the value: 1658311494 need be updated automatically.

Thanks.

**Comment by apigirl** [comment]
Hi @mtavaresmedeiros,

Feel free to reach out to our [awesome support team](https://docs.datadoghq.com/help/) - they can definitely help you get this sorted out. Since this isn't docs specific feedback, I am going to close this issue.

Kaylyn
