### ISSUE TITLE
The is_exact_match supports multiple comparison strings which isn't documented

### ISSUE THREAD

**Issue by jeroenj** [DataDog/documentation#14781]
## Documentation Page

https://docs.datadoghq.com/monitors/notify/variables/?tab=is_exact_match#conditional-variables

## Issue Description

The `is_exact_match` documentation does not mention the fact that you can have multiple comparison strings the same way you can have them with the `is_match` conditional.

It might make sense to add something like this as well:

> The `is_exact_match` condition also supports matching multiple strings:
> 
> {{#is_exact_match "host.name" "production" "staging"}}
>   This displays if the host that triggered the alert is exactly
>   named production or staging. @dev-team@company.com
> {{/is_match}}

**Comment by jeroenj** [comment]
I've created a PR for this: https://github.com/DataDog/documentation/pull/14782.

**Comment by maycmlee** [comment]
Thanks @jeroenj for opening the PR and for contributing to our docs! The PR is now merged.
