### ISSUE TITLE
What operational metrics are important for web services?

### ISSUE THREAD

**Issue by clofresh** [DataDog/documentation#15]
Explain throughput, latency, error rate.

**Comment by technovangelist** [comment]
Hi @clofresh 

Looks like you are wanting a guide on how to use datadog to get your ops job done. Is that correct?

**Comment by clofresh** [comment]
Yeah, I think this is the kind of stuff that @kky is working on

**Comment by technovangelist** [comment]
I think this is getting gradually addressed through the blog and will close this issue
