### ISSUE TITLE
Show example on how to ignore multiple resources or spans

### ISSUE THREAD

**Issue by mscoutermarsh** [DataDog/documentation#15132]
## Documentation Page
https://docs.datadoghq.com/tracing/guide/ignoring_apm_resources/?tab=kubernetesdaemonset

## Issue Description
On this page the examples show how to ignore 1. It's not clear how to do multiple (after some digging through the agent repo, I found it is comma delimited).

Would be helpful to show multiple in the examples.

**Comment by kayayarai** [comment]
Thanks for pointing this out, Mike. I'll work on getting an updated example in.

**Comment by kayayarai** [comment]
The page is updated with examples for multiple values. Thanks again for the report.
