### ISSUE TITLE
Link targets incorrect on "Install the Datadog Agent on Kubernetes" page

### ISSUE THREAD

**Issue by schisamo** [DataDog/documentation#15349]
## Documentation Page

The main [Install the Datadog Agent on Kubernetes](https://docs.datadoghq.com/containers/kubernetes/installation/) page.

I've seen the issue using the latest version of Safari and Firefox on my MBP.

## Issue Description

The links on the second two tabs ([Helm](https://docs.datadoghq.com/containers/kubernetes/installation/?tab=helm), [DaemonSet](https://docs.datadoghq.com/containers/kubernetes/installation/?tab=daemonset)) are completely wrong. For example:
- **Install Helm** goes to https://github.com/DataDog/datadog-operator but should be going to https://v3.helm.sh/docs/intro/install/
- **Datadog Helm repository README** goes to https://docs.datadoghq.com/agent/guide/operator-advanced but should be going to https://github.com/DataDog/helm-charts/blob/master/charts/datadog

Looking over the [source code for the file](https://github.com/DataDog/documentation/blob/master/content/en/containers/kubernetes/installation.md?plain=1) it appears the nesting of the [reference-style links](https://www.markdownguide.org/basic-syntax/#reference-style-links) isn't working as expected.

**Comment by maycmlee** [comment]
Thanks @schisamo for letting us know! We will look into this and get back to you on it.

**Comment by maycmlee** [comment]
Hi @schisamo, I just wanted to let you know that this has been fixed. Thanks again letting us know!
