### ISSUE TITLE
Undocumented API response 414 Request-URI Too Large for api/v1/slo/can_delete

### ISSUE THREAD

**Issue by Dombo** [DataDog/documentation#15343]
## Documentation Page

https://docs.datadoghq.com/api/latest/service-level-objectives/#check-if-slos-can-be-safely-deleted
https://github.com/DataDog/documentation/blob/master/data/api/v1/full_spec.yaml#L26636-L26660

## Issue Description

Your API is capable of returning a https://httpstatuses.io/414

It'd be nice to know what the limit is in the docs so those building integrations can design with that in mind.

Your docs mention some return codes but not this one.

**Comment by apigirl** [comment]
hey @Dombo, thanks for the heads up! We'll look at getting it added

**Comment by Dombo** [comment]
Thanks! Ended up handling the case in code but it'd be good to get the docs updated.
