### ISSUE TITLE
Wrong link? [DataDog Serverless Plugin](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/setting-credentials-node.html)?

### ISSUE THREAD

**Issue by eihli** [DataDog/documentation#15354]
## Documentation Page

https://github.com/DataDog/documentation/blob/d9b2644bc89d48b1ca70a0e378213eb0a9919d9f/content/en/serverless/installation/nodejs.md?plain=1#L99

## Issue Description

I expected the link to take me to something more closely related to the serverless plugin. Seems like this link might be a mistake.

**Comment by cswatt** [comment]
Thanks for raising this issue! This link appears to go to `https://docs.datadoghq.com/serverless/libraries_integrations/plugin/`, which is intended.
