### ISSUE TITLE
High water mark plan is different on different pages

### ISSUE THREAD

**Issue by caleb15** [DataDog/documentation#15465]
## Documentation Page
https://docs.datadoghq.com/account_management/billing/pricing/
https://docs.datadoghq.com/account_management/billing/

## Issue Description
In https://docs.datadoghq.com/account_management/billing/pricing/ the high water mark plan is described like so:
> On a high watermark plan (HWMP), these hourly measurements are ordered from highest to lowest at the end of the month, and Datadog charges based on the eighth highest measurement.

But in https://docs.datadoghq.com/account_management/billing/ it's described like this:
> Datadog meters the count of hosts and custom metrics hourly. The billable count of hosts is calculated at the end of the month using the maximum count (high-water mark) of the lower 99 percent of usage for those hours. Datadog excludes the top 1% to reduce the impact of spikes in usage on your bill. The billable count of custom metrics is based on the average number of custom metric hours for the month. See your [Usage](https://app.datadoghq.com/account/usage/hourly) in Datadog. Billing pages are only accessible to users with the Datadog Admin Role.

(I assume that's the high water mark plan they are talking about above, given the mention of high water mark)

I'm confused as to how the high water mark plan operates. Does it charge based on the eighth highest measurement, or does it charge based on the max count of the lower 99% of usage?

Also, the `/billing/` page only mentions one calculation for host pricing, when there's actually two? different calculations depending on whether you are a on-demand or commited plan.

**Comment by apigirl** [comment]
Hi @caleb15,

Thanks for letting us know about the discrepancy here, we'll look at getting it updated! In the meantime, feel free to reach out to our [awesome support team](https://docs.datadoghq.com/help/) - they can definitely clarify this for you.

Kaylyn

**Comment by neko-dd** [comment]
This issue was recently fixed.
