### ISSUE TITLE
Conflicting Node.js DD_TRACE_AGENT_HOST / DD_AGENT_HOST documentation

### ISSUE THREAD

**Issue by pinko-fowle** [DataDog/documentation#15554]
## Documentation Page

* https://docs.datadoghq.com/tracing/trace_collection/dd_libraries/nodejs?tab=containers 
* https://docs.datadoghq.com/tracing/trace_collection/library_config/nodejs/

## Issue Description

https://docs.datadoghq.com/tracing/trace_collection/dd_libraries/nodejs?tab=containers documents the use of `DD_AGENT_HOST`

meanwhile https://docs.datadoghq.com/tracing/trace_collection/library_config/nodejs/ and [`dd-trace-js`'s `docs/API.md`](https://github.com/DataDog/dd-trace-js/blob/master/docs/API.md#tracer-settings) document the use of slightly different `DD_TRACE_AGENT_HOST`.

ideally the documentation for Node.js ought be consistent & comprehensive.

**Comment by pinko-fowle** [comment]
For reference, in `dd-trace-js`:

* https://github.com/DataDog/dd-trace-js/blob/94edef76f120389c5f31e0ff4d907342780aaab9/packages/dd-trace/src/profiling/config.js#L62 accepts only `DD_AGENT_HOST`
* https://github.com/DataDog/dd-trace-js/blob/master/packages/dd-trace/src/config.js#L75-L76 accepts either `DD_AGENT_HOST` or `DD_TRACE_AGENT_HOST`.

**Comment by pinko-fowle** [comment]
For reference, in `dd-trace-js`:

* https://github.com/DataDog/dd-trace-js/blob/94edef76f120389c5f31e0ff4d907342780aaab9/packages/dd-trace/src/profiling/config.js#L62 accepts only `DD_AGENT_HOST`
* https://github.com/DataDog/dd-trace-js/blob/94edef76f120389c5f31e0ff4d907342780aaab9/packages/dd-trace/src/config.js#L75-L76 accepts either `DD_AGENT_HOST` or `DD_TRACE_AGENT_HOST`.

**Comment by kayayarai** [comment]
Hi @pinko-fowle Thanks for raising this. I'll look into it
