### ISSUE TITLE
What operational metrics are important for queueing?

### ISSUE THREAD

**Issue by clofresh** [DataDog/documentation#16]
* size of the queue
* queue processing throughput
* length of time spent in queue
* error rate in processing

**Comment by technovangelist** [comment]
Hi @clofresh 

Where do you think something like this should go?

**Comment by clofresh** [comment]
Another thing that @kky is working on. Probably would be a guide on the docs site, specific a particular integration we do, and also linked off our blog

**Comment by technovangelist** [comment]
This is being addressed in the how to monitor blog series
