### ISSUE TITLE
PHP: invalid  Monolog snippet

### ISSUE THREAD

**Issue by gnumoksha** [DataDog/documentation#16068]
## Documentation Page
- file [other_telemetry/connect_logs_and_traces/php.md](https://github.com/DataDog/documentation/blob/master/content/en/tracing/other_telemetry/connect_logs_and_traces/php.md)
- url https://docs.datadoghq.com/tracing/other_telemetry/connect_logs_and_traces/php/

## Issue Description
The following snippet does not work because Monolog does not allow the processor to set the message:
```php
<?php
  $logger->pushProcessor(function ($record) {
      $context = \DDTrace\current_context();
      $record['message'] .= sprintf(
          ' [dd.trace_id=%s dd.span_id=%s]',
          $context['trace_id'],
          $context['span_id']
      );
      return $record;
  });
?>
```

That throws a `LogicException` with the message `Unsupported operation: setting message`.

**Comment by kayayarai** [comment]
Hi! Thanks for raising this Tobias. I'll look into what it should say and fix it.

**Comment by bwoebi** [comment]
This changed in monolog v2 - the code snippet here is compatible with v1.

For v2 use:
```
<?php

  $logger->pushProcessor(function ($record) {
      $context = \DDTrace\current_context();
      return $record->with(message: $record['message'] . sprintf(
          ' [dd.trace_id=%s dd.span_id=%s]',
          $context['trace_id'],
          $context['span_id']
      ));
  });
```

**Comment by kayayarai** [comment]
https://github.com/DataDog/documentation/pull/16333
