### ISSUE TITLE
 DataDog / integrations-extras / grpc_check: deadlink

### ISSUE THREAD

**Issue by aleveille** [DataDog/documentation#16217]
## Documentation Page

https://docs.datadoghq.com/integrations/grpc_check/

## Issue Description

The link in footnote #4 is a dead link. Here's a PR to fix it:
https://github.com/DataDog/integrations-extras/pull/1696

**Comment by urseberry** [comment]
Thank you so much for submitting this issue and PR! The team approved and merged your PR last week.
