### ISSUE TITLE
Update java documentation to use OpenTelemetry API

### ISSUE THREAD

**Issue by MasterOdin** [DataDog/documentation#16307]
## Documentation Page

https://docs.datadoghq.com/tracing/trace_collection/custom_instrumentation/java/ (and maybe others?)

## Issue Description

This page uses the [OpenTracing](https://opentracing.io/) APIs, which according to https://www.cncf.io/blog/2022/01/31/cncf-archives-the-opentracing-project/ has been archived and that the java implementation at https://github.com/opentracing/opentracing-java states it's been deprecated. My understanding successor is the [OpenTelemetry](https://opentelemetry.io) project is its successor, but I'm not sure if DD supports it and if I could switch over to the [OpenTelemetry Java library](https://opentelemetry.io/docs/instrumentation/java/). Some other DD docs mention OpenTelemetry, but I think it'd be good to make all the pages use the currently supported standard.

**Comment by kayayarai** [comment]
Hi Matthew! Indeed, we have a project this quarter to add pages for custom instrumentation with OpenTelemetry information and examples. It's supported, and the docs should be up soon (Java will be a priority for sure). I'll leave this issue open until I have a link to docs I can send to you.

**Comment by kayayarai** [comment]
Following up on this: We now have https://docs.datadoghq.com/tracing/trace_collection/otel_instrumentation/ (for supported languages). Not all OpenTracing docs have been removed -- there's still some demand for those docs, but this new link is certainly the recommended way.
