### ISSUE TITLE
Setting up log drain for heroku unclear about host value

### ISSUE THREAD

**Issue by mkrtchian** [DataDog/documentation#17127]
## Documentation Page
[Collect Heroku logs](https://docs.datadoghq.com/logs/guide/collect-heroku-logs/)

## Issue Description

For setting up the logs drain on heroku, the documentation says to set a `host`, but says at the same time that it's not possible to set the host according to the dyno name. It says then that we can use `dyno` and `dynotype` tags to correlate with logs.

I have several questions when I read this doc:
* If we choose to correlate by using `dyno` and `dynotype` tags, what should we put as `host`?
* Does the setup of the `dyno` and `dynotype` tags automatically activate the correlation between logs and traces, regardless of the host?
* How do we add these tags in logs? As JSON metadata on each log?

There is another example in the doc page [Instrumenting a Ruby on Rails application on Heroku with Datadog](https://docs.datadoghq.com/agent/guide/heroku-ruby/#setting-up-heroku-log-drain).
It shows this command:
```bash
heroku drains:add "https://http-intake.logs.datadoghq.com/api/v2/logs?dd-api-key=$DD_API_KEY&ddsource=heroku&env=$DD_ENV&service=$DD_SERVICE&host=${APPNAME}.web.1" -a $APPNAME
```
But here we hardcode the dyno name in the `host`. This will not work if we scale the dynos to have `web.2`, `web.3` etc. 

I've also read [the discussions in this PR](https://github.com/DataDog/documentation/pull/3530), but it's still unclear for me.

**Comment by buraizu** [comment]
@mkrtchian thanks for reaching out with these questions. We've created a ticket to investigate any potential updates to the documentation in this regard. For a more immediate response and troubleshooting, it may also be worthwhile to open a support ticket with the support team:
https://docs.datadoghq.com/help/

**Comment by buraizu** [comment]
Hi @mkrtchian, thank you for your patience. I'm not sure if you opened a support ticket or not, but we took a look at these questions from a documentation perspective -- please see the below follow ups to each of your questions:

> 1. If we choose to correlate by using dyno and dynotype tags, what should we put as host?

You can use `DD_DYNO_HOST` to cause the Agent to report the hostname as the app and dyno name. This is mentioned in the following doc:
https://docs.datadoghq.com/agent/basic_agent_usage/heroku/#hostname

> 2. Does the setup of the dyno and dynotype tags automatically activate the correlation between logs and traces, regardless of the host?

In testing, this does appear to be the case. In my test application, logs and traces were correlated even when `DD_DYNO_HOST` was set to `false`. As such, the existing doc seems to be accurate in this case.

> 3. How do we add these tags in logs? As JSON metadata on each log?

These are automatically added by the buildpack, as mentioned in the Heroku buildpack doc:
https://docs.datadoghq.com/agent/basic_agent_usage/heroku/#installation
> The buildpack automatically adds the tags dyno which represent the dyno name, such as web.1, and dynotype (the type of dyno, e.g run or web). See the [Guide to tagging](https://docs.datadoghq.com/tagging/) for more information.

As we were able to find this information in the existing docs, it's not currently clear what documentation-side updates would be helpful in this scenario. Could you provide any specific examples of documentation updates that you feel would enhance these instructions?

Thanks again for reaching out to help us improve the documentation, and for your patience!

**Comment by buraizu** [comment]
Hi @mkrtchian, just following up once again to let you know that we've added a note to the Collect Heroku Logs page clarifying the origin of the `dyno` and `dynotype` tags for log and trace correlation in the following PR:
https://github.com/DataDog/documentation/pull/18462

Feel free to let me know if this is something that might be helpful, or if you have any other questions or suggestions.

**Comment by buraizu** [comment]
Hi @mkrtchian I'll close this issue for now, but please feel free to reopen if you have any other questions or suggestions. Thanks again for reaching out!
