### ISSUE TITLE
Android platform listed in iOS Integration documentation page

### ISSUE THREAD

**Issue by psynix** [DataDog/documentation#17321]
On page: https://docs.datadoghq.com/integrations/rum_ios/

Replace _Android_ with _iOS_

> [Service Checks](https://docs.datadoghq.com/integrations/rum_ios/#service-checks)
The ~~Android~~ **iOS** integration does not include any service checks.

**Comment by hestonhoffman** [comment]
Hi @psynix, thanks for the contribution. A fix has been merged 👍
