### ISSUE TITLE
Wrong tag in kube core metric doc

### ISSUE THREAD

**Issue by linceaerian** [DataDog/documentation#17324]
## Documentation Page

https://docs.datadoghq.com/integrations/kubernetes_state_core/?tab=helm

kubernetes_state.endpoint.address_not_ready
    Number of addresses not ready in endpoint. Tags:endpoint kube_namespace.

## Issue Description

Should be: kube_endpoint

`avg:kubernetes_state.endpoint.address_not_ready{lbnref:127672} by {kube_namespace,kube_endpoint}`

![image](https://user-images.githubusercontent.com/1318470/225583216-46140139-c3ba-48ea-a984-63ec48a52866.png)

**Comment by cswatt** [comment]
Thank you for raising this! The discrepancy has been resolved.
