### ISSUE TITLE
Unclear documentation - Clarification needed

### ISSUE THREAD

**Issue by flysen** [DataDog/documentation#17427]
Response from Datadog support how they calculate rate:
```
So I was able to check all your assumptions with the team and I think I can explain to you exactly how it goes.
 
Here you choose your metric type as a rate. The rate, as I shared with you above is calculated like that: new value - old value with both values beeing gauges.
Now, how does the agent send a gauge?
Assuming streaming JMX points = 10, 5, 2, 2, 0, 5, the agent will keep as a gauge the last datapoint as a gauge, meaning here 5. This is our first gauge value.
Now, in order to send a rate, the agent would need a second value.
So in the next round of streaming JMX points, the agent would once again keep as a gauge the last datapoint.
 
Now that the agents has in memory two different gauge values, then it will be able to calculate a rate based on new value - old value.

```
 
https://github.com/DataDog/documentation/blob/365c7e4b45598975c29bc95f54d1d8a95aeb69a5/content/en/metrics/types.md?plain=1#L164-L170

**Comment by estherk15** [comment]
Thank you @flysen for bringing this to our attention and for your detailed notes! Our team will take a look and review the documentation.

**Comment by tina550** [comment]
Fayette report 13 nonfatal 6 fatal 2023 
Range December 11,2022 February 24,2023
Injection opioid and/or Fentyal 
Marijuana laced with Fentyal >>> January 18,2023 
ADENA MC / F 26 call in >> transport >> 
600026000am call in  F / unknown >>> overdose >> postal office corner lot. 
Transport >>>> Adena
