### ISSUE TITLE
how to filter out chrome extension console errors

### ISSUE THREAD

**Issue by saibs** [DataDog/documentation#17594]
## Documentation Page
https://docs.datadoghq.com/logs/log_collection/javascript/#advanced-usage

## Issue Description
- I found out in the documentation that we can filter out some logs but couldn't figure it out how filter console errors originating from chrome extensions when 'forwardErrorsToLogs' is enabled

**Comment by maycmlee** [comment]
Thanks @saibs for opening this PR! We'll take a look and be back in touch.

**Comment by maycmlee** [comment]
Hi @saibs,

Please feel free to reach out to our [Support team](https://docs.datadoghq.com/help/) as they can definitely help you get this sorted out. I am going to close this since it is not really a documentation update.

May
