### ISSUE TITLE
Update MongoDB Atlas integrations page with new metrics

### ISSUE THREAD

**Issue by sunfranklin** [DataDog/documentation#17707]
MongoDB has added new metrics to the MongoDB - DataDog integration. The documentation page [here](https://docs.datadoghq.com/integrations/mongodb_atlas/#data-collected) should be updated with these new metrics to match what MongoDB has added in their [documentation](https://www.mongodb.com/docs/atlas/tutorial/datadog-integration/#performance-metrics-available-to-datadog).

**Comment by sunfranklin** [comment]
Created [this PR](https://github.com/DataDog/integrations-extras/pull/1814) to address the issue.

**Comment by hestonhoffman** [comment]
Hi @sunfranklin, thanks for the contribution! Once that PR is merged, the metrics will be pulled into the docs 🙌
