### ISSUE TITLE
Update Monitor options default should be empty dict

### ISSUE THREAD

**Issue by onlyanegg** [DataDog/documentation#1774]
I think the default for the options parameter in the update monitor endpoint should be documented as an empty dict instead of as None. When I pass None for options, I get a 400, and the message says that query is specified incorrectly. When I pass an empty dict, it works as expected.

I'm happy to submit a PR for this. I just wanted to confirm that that's the case.

**Comment by jeremy-lq** [comment]
Thanks for the issue, @onlyanegg. We've addressed this with https://github.com/DataDog/documentation/pull/1980
