### ISSUE TITLE
Databricks Integrations: clarify parameter

### ISSUE THREAD

**Issue by LucasC** [DataDog/documentation#17879]
## Documentation Page
https://docs.datadoghq.com/integrations/databricks/?tab=driveronly

## Issue Description
The 3rd instruction step mentions that the `SITE URL` must be used in an environment variable for `DD_SITE`.

The link points to  to use the [this page](https://docs.datadoghq.com/getting_started/site/).
On it, there's a column named `Site URL` with the following format: `https://app.datadog.eu`
This could lead to confusion as the actual format expected by the Databricks integration is the `Site Parameter`: `datadog.eu`

## Impact
If the wrong parameter is used, the integration will not point to the right datadog site and the telemetry won't be sent accordingly.

## Recommendation
Replace:
> Set DD_SITE to your [site URL](https://docs.datadoghq.com/getting_started/site/).

By:
> Set DD_SITE to your [site parameter](https://docs.datadoghq.com/getting_started/site/) (for example `datadog.eu`).

## Side note
I wanted to push a PR directly, but `/content/en/integrations/databricks.md` does not exist?

**Comment by aliciascott** [comment]
Thanks so much, I've opened https://github.com/DataDog/integrations-core/pull/14483 to clarify this.
