### ISSUE TITLE
CSP Browser Intake URL for EU

### ISSUE THREAD

**Issue by KarlKl** [DataDog/documentation#17882]
## Documentation Page
https://docs.datadoghq.com/integrations/content_security_policy_logs/

## Issue Description
After switching DATADOG SITE to EU, nothing changes on the page. But if you want to report to an eu-site with the .com URL, you get a 403 Forbidden response. If I try the same url with the .eu TLD, it works like expected.

**Comment by hestonhoffman** [comment]
Hi @KarlKl, thanks for reporting this issue! There's a fix in the attached PR.
