### ISSUE TITLE
Add documentation for the network related metrics to the DataDog - MongoDB integration

### ISSUE THREAD

**Issue by sunfranklin** [DataDog/documentation#17893]
This is a request to update the DataDog - MongoDB integration [documentation](https://docs.datadoghq.com/integrations/mongodb_atlas/#data-collected) with the new network-related metrics. Specifically, the integration will be updated to add the following metrics:

MAX_SYSTEM_NETWORK_IN("mongodb.atlas.system.network.max.bytes.in") | SYSTEM (gauge) | The maximum Network Bytes In value over the time period specified by the metric granularity
MAX_SYSTEM_NETWORK_OUT("mongodb.atlas.system.network.max.bytes.out") | SYSTEM (gauge) | The maximum Network Bytes Out value over the time period specified by the metric granularity
SYSTEM_NETWORK_BYTES_IN("mongodb.atlas.system.network.bytes.in") | SYSTEM (rate) | The average rate of physical bytes received per second
SYSTEM_NETWORK_BYTES_OUT("mongodb.atlas.system.network.bytes.out") | SYSTEM (rate) | The average rate of physical bytes transmitted per second
NETWORK_BYTES_IN("mongodb.atlas.network.bytes.in") | PROCESS (rate) | The average rate of physical (after any wire compression) bytes sent to this database server per second
NETWORK_BYTES_OUT("mongodb.atlas.network.bytes.out") | PROCESS (rate) | The average rate of physical (after any wire compression) bytes sent from this database server per second
NETWORK_NUM_REQUESTS("mongodb.atlas.network.num.requests") | PROCESS (rate) | The average rate of requests sent to this database server per second

I'll be opening up a PR soon to add this to the documentation

**Comment by sunfranklin** [comment]
Created https://github.com/DataDog/integrations-extras/pull/1829 to address the issue.

**Comment by hestonhoffman** [comment]
Thanks for the contribution @sunfranklin! Looks like these are [live on the site](https://docs.datadoghq.com/integrations/mongodb_atlas/#data-collected), so I'll go ahead and close this ticket.
