### ISSUE TITLE
Application Security, Add User Info Java example wrong

### ISSUE THREAD

**Issue by mksplg** [DataDog/documentation#18103]
## Documentation Page
https://docs.datadoghq.com/security/application_security/threats/add-user-info/?s=custom+tags+trac&tab=set_user&code-lang=java#adding-authenticated-user-information-to-traces-and-enabling-user-blocking-capability

## Issue Description
Java example imports `datadog.trace.api.GlobalTracer` and calls `GlobalTracer.get().activeSpan()` on this class. 

`GlobalTracer.get()` returns a `datadog.trace.api.Tracer` which does not have an `activeSpan()` method. Only the `io.opentracing.Tracer` has this method.

Also the link in first sentence `You can [add custom tags to your root span](https://docs.datadoghq.com/security/application_security/threats/add-user-info/#adding-business-logic-information-login-success-login-failure-any-business-logic-to-traces), or use the instrumentation functions described below.` is wrong. It should instead link to https://docs.datadoghq.com/tracing/trace_collection/custom_instrumentation/java/#add-custom-span-tags.

**Comment by kayayarai** [comment]
Hello, Markus! Thanks for pointing out these problems. I'll confirm and make updates to the docs.

**Comment by kayayarai** [comment]
Hi! Fixed both of these. Thanks for reporting the problems.
