### ISSUE TITLE
Suggestion that GitHub webhook events changed to URL links.

### ISSUE THREAD

**Issue by taku333** [DataDog/documentation#18129]
**Is your feature request related to a problem? Please describe.**
GitHub webhook events may be added.
It would be a good idea to paste the URL of the GitHub documentation, as it is difficult to modify the documentation each time.

https://docs.datadoghq.com/integrations/github/#events

**Describe the solution you'd like**
The following URLs are available
https://docs.datadoghq.com/integrations/github/#events

```
6.In the Which events would you like to trigger this webhook? section, click Let me select individual events. and select from the following supported options to send events to Datadog:
```

Change to paste the following URL.
https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads

**Comment by alai97** [comment]
Hi @taku333, thanks for opening this issue! I've opened a PR to add the GitHub doc links into the table entries. Thanks again :D
