### ISSUE TITLE
APM Service representation initiative (versioned service name schemas)

### ISSUE THREAD

**Issue by willianccs** [DataDog/documentation#18164]
We didn`t found any documentation about this initiative and I think is necessary clarification about the roadmap.

### Service names for spans are currently inconsistent, both within and across tracers, leading to several issues:

1. Inconsistent naming across tracer libraries in different languages (e.g., `grpc-client` vs `grpc.client`).
2. Inconsistency in operation names across integrations, even within a single tracer (e.g., `requests` vs `httplib`).
3. Overly generic service names acting as naming 'sinks' (e.g., all databases for 'postgres' are represented as `postgres`).
4. Some clients (e.g., grpc) are represented as full-on services, which is generally unexpected.

These issues arise because DataDog's features, such as metrics and flame graphs, require tracer libraries to differentiate between services accurately. The existing mechanism for doing so involved specifying a separate service within an application (either manually or by integration default). This problem is exacerbated by a lack of standardization across DataDog's libraries and the selection of overly broad fakes and defaults.

**Describe the solution you'd like**

It's important to know if the actual version (`v0`) will be deprecated in future and If the full implementation of this is stable.

### Versioned service name "schemas":

- `v0`: The existing mechanism for determining service names
- `v1`: Replacing the 'default' contrib-specific service name with the environment variable `$DD_SERVICE`

These changes are being implemented alongside updates to `peer.service` to provide a better service-naming experience for customers.

Specifically, these changes will:

- Eliminate the creation of fake services, such as `grpc.client`
- Standardize service names across and within tracers
- Reduce the need to create *as many* fake services to leverage DataDog features, like metrics
- Make service names more intuitive for humans

Currently, these changes are opt-in via a feature flag: `DD_TRACE_SPAN_ATTRIBUTE_SCHEMA`

**Describe alternatives you've considered**
An oficial documentation about this feature.

**Additional context**

* v0
![image](https://github.com/DataDog/documentation/assets/7793624/84f3c7a3-402b-421f-9438-ed0fd2fd61a4)

* v1
![image](https://github.com/DataDog/documentation/assets/7793624/8b30f770-4c25-4f5a-a2ef-767c8b699024)

The feature flag must function correctly to switch between behaviors. Due to the way DataDog utilizes metrics and other features, users may encounter the following issues with existing applications:

- False alarms being triggered
- Alarms not being triggered when they should be
- Unanticipated phase shifts in metrics
- Disappearance or changes in services

> PRs: https://github.com/search?q=DD_TRACE_SPAN_ATTRIBUTE_SCHEMA&type=pullrequests

**Comment by kayayarai** [comment]
Thanks, Willian! I'm looking into this.

**Comment by kayayarai** [comment]
Hi Willian, thanks for your patience on this. Right now my direction from Product is to not document this in the public Datadog docs. If you're looking for a Roadmap statement, its best to talk with someone from APM product management. Let me know if you need a contact name/email.
