### ISSUE TITLE
Smoothing: Broken link to Stanford ASAP algorithm page

### ISSUE THREAD

**Issue by aaronrl** [DataDog/documentation#18434]
## Documentation Page
[Dashboards > Functions > Smoothing](https://docs.datadoghq.com/dashboards/functions/smoothing/)

## Issue Description
In the [Autosmooth](https://docs.datadoghq.com/dashboards/functions/smoothing/#autosmooth) section, the link to more information about Stanford's ASAP algorithm is no longer accessible (in repo reference: [smoothing.md#L158](https://github.com/DataDog/documentation/blob/master/content/en/dashboards/functions/smoothing.md?plain=1#L158)).  It appears to have moved but it's not clear where.  I attempted to see if archive.org had captured the contents of the site before it was moved, but the page is not part of the index unfortunately ([src](https://archive.org/search?query=futuredata.stanford.edu%2Fasap)).  As such, I'm not sure what a viable alternative link would be to illustrate comparable information.

**Comment by estherk15** [comment]
Thank you for bringing this to our attention, it does seems to lead to a broken link! I will replace the link with https://github.com/stanford-futuredata/ASAP , hope that helps!
