### ISSUE TITLE
Two different names for enabling tracing via environment variable

### ISSUE THREAD

**Issue by andyshinn** [DataDog/documentation#18882]
## Documentation Page

* https://github.com/DataDog/documentation/blob/b7e7d4b42c042e6480e3c9c03b23777341f80bea/content/en/serverless/installation/python.md?plain=1#L242
* https://github.com/DataDog/documentation/blob/160886e968f042861d840e2c6ad45edcda885f62/content/en/serverless/distributed_tracing/_index.md?plain=1#L41

## Issue Description

These two documentation pages seem to have two different environment variables for enabling tracing. One is `DD_TRACE_ENABLED` and the other is `DD_ENABLE_TRACING`. I am assuming only one is valid. Which one is correct?

**Comment by urseberry** [comment]
Fixed on https://github.com/DataDog/documentation/pull/18972
