### ISSUE TITLE
Metric advanced filtering: mixing wildcards and variables?

### ISSUE THREAD

**Issue by miparnisari** [DataDog/documentation#18910]
Saw this: 

https://github.com/DataDog/documentation/blob/ad561a60e5ec5cf9d2d162a2c1d76c318de2a8e6/content/en/metrics/advanced-filtering.md?plain=1#L71-L90

Is it possible to mix wildcard queries with template variables? E.g. 

```
pod_name:$environment.value-*
```

where `$environment` is the variable

**Comment by estherk15** [comment]
Hi @miparnisari, thanks for your question! Wild card support between metrics and dashboard template variables are a bit different. For more information on using the wildcard for Dashboard Template Variables, see this [documentation](https://docs.datadoghq.com/dashboards/template_variables/#text). If this does not answer your question, please reach out to our [Support team](https://www.datadoghq.com/support/) so they can get a better understanding of your use case.

**Comment by miparnisari** [comment]
> Note: The wildcard syntax is not supported following a template variable.

Boo :(
