### ISSUE TITLE
Log monitors - Log samples and breaching values toplist

### ISSUE THREAD

**Issue by adillonjc** [DataDog/documentation#18922]
## Documentation Page
https://docs.datadoghq.com/monitors/types/log/

## Issue Description
In the table here (https://github.com/DataDog/documentation/blob/master/content/en/monitors/types/log.md#log-samples-and-breaching-values-toplist), `Grouped Multi Alert Log count` is listed twice. Is this intentional?

**Comment by estherk15** [comment]
Thanks for pointing this out @adillonjc! I'm looking into this and will let you know.

**Comment by estherk15** [comment]
Hi @adillonjc , thanks again for pointing this out, this issue was resolved in https://github.com/DataDog/documentation/pull/18983!
