### ISSUE TITLE
/integrations/kubernetes missing service checks

### ISSUE THREAD

**Issue by saj** [DataDog/documentation#1904]
## Documentation Page

https://docs.datadoghq.com/integrations/kubernetes/

## Issue Description 

Quoting from the article:

> The Kubernetes check does not include any service check at this time.

However, after enabling the Datadog Kubernetes integration, I can see the following three service checks on https://app.datadoghq.com/check/summary (Kubernetes 1.8):

- `kubernetes.kubelet.check`
- `kubernetes.kubelet.check.ping`
- `kubernetes.kubelet.check.syncloop`

Without reading the [source code](https://github.com/DataDog/integrations-core/blob/c5d048170965fbf196bdd1ea5dad071311597b77/kubernetes/check.py#L130-L161), it is not  possible for users to understand what purpose these service checks serve.

```
# curl http://127.0.0.1:10255/healthz?verbose=True
[+]ping ok
[+]syncloop ok
healthz check passed
```

Unfortunately, I don't think upstream have sufficiently documented the meaning of these kubelet subsystems (`ping`, `syncloop`, etc.) so we may be out of luck there.

Suggest:

- An explicit note that `kubelet.check` will go critical if any of the more specific checks go critical.
- Some language that explains where the data for the more specific checks originate.

**Comment by l0k0ms** [comment]
Hello, 

Thank you very much for your feedback!  I have added the service checks description in this PR: https://github.com/DataDog/documentation/pull/1905
This should be merged as soon as someone reviews it on our side. 

Feel free to open new issues if you have other feedbacks 👌.
Best regards,
Pierre

**Comment by l0k0ms** [comment]
Hello, 

Since the PR is merged, I'm closing this issue.

Thanks again for the feedback 🙇 
Best regards,
Pierre
