### ISSUE TITLE
Log Status Remapper example is incorrect

### ISSUE THREAD

**Issue by oliviercar0n** [DataDog/documentation#19566]
## Documentation Page

https://docs.datadoghq.com/logs/log_configuration/processors/?tab=ui#log-status-remapper

## Issue Description

The log status remapper screenshot shows the fields being populated as 

```
Name the processor: level
Set the status attribute(s): Remapping status from the level attribute
```

whereas it should be the other way around

```
Name the processor: Remapping status from the level attribute
Set the status attribute(s): level
```

**Comment by maycmlee** [comment]
Thanks @oliviercar0n for opening this issue! We're taking a look into it and will be back in touch.

**Comment by maycmlee** [comment]
This has been fixed. Thanks again @oliviercar0n for bringing our attention to this!
