### ISSUE TITLE
New configuration options for windows_service integration

### ISSUE THREAD

**Issue by derekwbrown** [DataDog/documentation#1963]
## Issue Description 
Added new configuration options for the Windows Service agent integration https://github.com/DataDog/integrations-core/pull/1035.

**Comment by l0k0ms** [comment]
Plop,

Many thanks for the notification :bow: :bow:

Since it's an advanced configuration option we are going to keep the doc in the `windows_sercice.yaml` file. (Thanks for the typo fix btw) 

Keep it up with the good work!
Best,
Pierre
