### ISSUE TITLE
Incorrect unit of measurement for GCP Big query metric

### ISSUE THREAD

**Issue by Ricky-Thomas** [DataDog/documentation#1965]
## Documentation Page
https://docs.datadoghq.com/integrations/google_cloud_big_query/

See screenshot: https://cl.ly/233s2O0g463g

## Issue Description 
I'm pushing a change to prod soon that will update the unit of measurement for the metric gcp.bigquery.storage.uploaded_row_count from bytes to the correct unit from Google, which is rows.

**Comment by l0k0ms** [comment]
Hello, 

Thank you very much for the update Ricky! 

Documentation pulls automatically the content of `metadata.csv` files to [generate its content in the ### Metrics sub-section](https://github.com/DataDog/documentation/wiki/How-to-display-an-Integration-in-documentation-integrations-page-%3F)

Documentation should be up-to-date on its next build following your PR merging.

Keep it up with the good work 🙇 
Best regards,
Pierre
