### ISSUE TITLE
Inaccurate documentation image for funnel filtering

### ISSUE THREAD

**Issue by matthewhaywardyum** [DataDog/documentation#19702]
## Documentation Page
https://docs.datadoghq.com/real_user_monitoring/funnel_analysis/#filtering

## Issue Description
![image](https://github.com/DataDog/documentation/assets/112869784/0cd6dee4-6fe0-429f-90f6-d5902bc41127)
The above image in the documentation does not match what is available in the interface.

![image](https://github.com/DataDog/documentation/assets/112869784/f15bc34b-2ca0-43fc-b9bc-f1ff812541a2)

**Comment by urseberry** [comment]
Resolved by https://github.com/DataDog/documentation/pull/19831
