### ISSUE TITLE
AWS EC2 instance age metric is not default

### ISSUE THREAD

**Issue by Ricky-Thomas** [DataDog/documentation#1987]
## Documentation Page
https://docs.datadoghq.com/integrations/amazon_ec2/

## Issue Description 
The metric aws.ec2.instance_age is not actually something that's on by default. We have to enable this on a per customer basis.

Can we add a note there just saying that this metric is something we can enable upon request?
https://cl.ly/2h090t290C1B

**Comment by l0k0ms** [comment]
Hello Ricky,

Many thanks for this feedback!

AWS EC2 Integration page is now updated. The disclaimer will be made public during next doc build.

Keep it real,
Best regards,
Pierre
