### ISSUE TITLE
wrong `metrics` entry in the API Doc?

### ISSUE THREAD

**Issue by nekottyo** [DataDog/documentation#19928]
## Documentation Page
https://docs.datadoghq.com/ja/api/latest/

## Issue Description
In the list on the left side of the page, the link for `metrics` is https://docs.datadoghq.com/ja/.

However, this `metrics` item appears to be unnecessary since there is another correct one called `メトリクス`.

![image](https://github.com/DataDog/documentation/assets/4465795/a49ce033-648f-4ae0-952c-5a2d27635eb9)
![image](https://github.com/DataDog/documentation/assets/4465795/ca593140-18f5-46d3-b417-60bbe2913e58)

**Comment by hestonhoffman** [comment]
Thanks for filing the issue! This is probably an issue with our translation pipeline, I'll take a look

**Comment by hestonhoffman** [comment]
Hi @nekottyo, thanks for alerting us to this. It should be fixed now!

**Comment by nekottyo** [comment]
Thanks!

Out of curiosity, was the modification completed in this repository?
Or was the change made in a private repository?

**Comment by hestonhoffman** [comment]
Yes! Sorry, I should have linked the PR - https://github.com/DataDog/documentation/pull/20053. The issue was an untranslated string in our menu file

**Comment by nekottyo** [comment]
I see, I looked for a while but couldn't find it.
So it was here :+1:
