### ISSUE TITLE
Clarity around JVM metrics with the Open Telemetry collector

### ISSUE THREAD

**Issue by zachauten** [DataDog/documentation#20061]
## Documentation Page
[Runtime Metrics](https://docs.datadoghq.com/opentelemetry/runtime_metrics/java)
and
[OTLP ingest in the agent](https://github.com/DataDog/documentation/blob/master/content/en/opentelemetry/otlp_ingest_in_the_agent.md?plain=1#L20C107-L20C107)

## Issue Description
I think the docs could be a little clearer on whether or not the JVM metrics dashboard will work if you're using the otel collector instead of the datadog agent. The "OTLP ingest in the agent" page states that it wouldn't be supported if you don't use the agent, but the "Runtime Metrics" page states that the only prerequisites are that you are sending otel metrics to datadog, and that you are using the Java integration.

I'm using the collector, and i'm able to see the metrics in datadog, but the runtime metrics dashboard isn't enabled on the service page. Does this feature only work if you use the datadog agent?

**Comment by brett0000FF** [comment]
@zachauten - Thanks for submitting this issue. Just wanted to let you know that we're looking into this.

**Comment by liustanley** [comment]
@zachauten Apologies for the confusion, the section you flagged in the "OTLP ingest in the agent" page is out of date and we'll update this. OTel JVM runtime metrics work with both the Collector and the Datadog Agent. Could you open a support request with more details so that we can help diagnose your issue? Thanks!

**Comment by zachauten** [comment]
Will do, thanks!
