### ISSUE TITLE
RUM: Incorrect documentation

### ISSUE THREAD

**Issue by ziquanmiao** [DataDog/documentation#20533]
https://github.com/DataDog/documentation/blob/8b46829c99e791bbf6c076aed6978ea72492d1fc/content/en/real_user_monitoring/browser/troubleshooting.md?plain=1#L127

Redirects to https://docs.datadoghq.com/integrations/content_security_policy_logs which is talking about the content security policy log integration not the requirement content security policy configurations required to make sure RUM browser SDK (and sessionReplay features) works properly

**Comment by ziquanmiao** [comment]
I am looking for Datadog RUM documentation's equivalent to step 3 here: https://help.hotjar.com/hc/en-us/articles/115011640307-Content-Security-Policies

**Comment by jhgilbert** [comment]
Hi @ziquanmiao, thanks for your patience on this one. I believe the linked page has what you're looking for under this header: https://docs.datadoghq.com/integrations/content_security_policy_logs#use-csp-with-real-user-monitoring-and-session-replay

Is this what you were looking for? If so, I can update the documentation. Thank you!

**Comment by jhgilbert** [comment]
I've updated the documentation as described above. Thanks for reporting this!
