### ISSUE TITLE
Make clear that snapshot has some delay before being available

### ISSUE THREAD

**Issue by nicgirault** [DataDog/documentation#2074]
## Documentation Page

https://docs.datadoghq.com/api/?lang=python#graphs

## Issue Description 

Hello and thanks for your awesome product.

I have lost an afternoon struggling with custom Slack integration because my snapshot was not displayed in Slack. I thought I was misusing the Slack API but actually this is coming from datadog. It's not really a documentation issue but I don't know where to report this issue and a quick fix could be to add the info in the documentation.

The problem is that when the snapshot is created, it's not available right now. There is some delay before it is available. Someone else reported this bug (http://andreafalzetti.github.io/blog/2017/04/17/datadog-png-snapshot-not-showing.html). For a few seconds, the content length of the resource is 179b. I wrote custom code waiting for the content length to change... this is not really a convenient usage on dd api.

(By the way, I've the same issue with posting a metric point and then querying the snapshot that should include the last posted point... it's not included right now in the snapshot or metric query so I've to watch for the metric to include the new point)

**Comment by l0k0ms** [comment]
Hello @nicgirault, 

Thank you very much for the feedback, we are going to look into it!

Best regards,
Pierre

**Comment by l0k0ms** [comment]
Hello again, 

A disclaimer has been added to warn about the snapshot generation delay.
Many thanks for the feedback once again 🙇 

If you spot another weird behaviour of Datadog, feel free to open an issue for a doc update.
Best regards,
Pierre
