### ISSUE TITLE
Document on connecting OpenTelemetry logs and traces for Java/Spring Boot/Logback unclear

### ISSUE THREAD

**Issue by budjb** [DataDog/documentation#20931]
## Documentation Page
https://docs.datadoghq.com/tracing/other_telemetry/connect_logs_and_traces/opentelemetry/?tab=java

## Issue Description
In the document that outlines how to translate OpenTelemetry trace and span IDs in logs to formats expected by DataDog, there is a Java sample that mentions that it's intended for Spring Boot and Logback.

<img width="823" alt="image" src="https://github.com/DataDog/documentation/assets/1370939/e025c029-4793-4a0b-bced-63aa1c028004">

However, it gives no indication of how to integrate into Spring Boot or Logback to perform this translation. It is seemingly non-trivial to tie into Logback's logging lifecycle, and a more complete description or example would go a long way towards helping developers in this ecosystem utilize OpenTelemetry as the instrumentation layer.

**Comment by maycmlee** [comment]
Thanks @budjb for opening this issue! We're taking a look into it and will be back in touch.

**Comment by maycmlee** [comment]
Hi @budjb! I added a link to our Java log collection docs in the the doc. I'll go ahead and close this issue, but if that link isn't what you are looking let me know. Thanks!

**Comment by budjb** [comment]
Thanks @maycmlee! I'm not sure the existing content in that page addresses the translation concern, but I also have discovered that converting trace IDs from open telemetry to datadog format doesn't seem to be necessary anymore. So this may be a moot issue.

One of the things that still needs addressing is converting the `trace_id` and `span_id` properties to use the `dd.` prefix if you are using open telemetry automation instrumentation. I have a working example of this with json logging. Are you interested in a contribution for this?

**Comment by maycmlee** [comment]
> One of the things that still needs addressing is converting the trace_id and span_id properties to use the dd. prefix if you are using open telemetry automation instrumentation. I have a working example of this with json logging. Are you interested in a contribution for this?

Thanks @budjb! Yes, if you'd like to open a PR for it, that'd be great! Or I can create a card for us to add that info on my side.
