### ISSUE TITLE
Make clear that Django does not send traces when Debug = True

### ISSUE THREAD

**Issue by ndkv** [DataDog/documentation#2105]
## Documentation Page
http://pypi.datadoghq.com/trace/docs/#module-ddtrace.contrib.django

## Issue Description 
It is not sufficiently clear that traces will not be sent when `Debug = True` in a Django app when landing on the above page from the Datadog dashboard -> APM Docs -> Python -> Advanced configuration -> Django.

The two places that mention this fact 

- https://docs.datadoghq.com/tracing/languages/python/
- the _last sentence_ of the `ENABLED` setting description

are not visited and easily overlooked, respectively, when setting the tracer up for the first time.

A solution might be to state this fact more clearly in the documentation page seeing that most users will probably instrument their development environment first. A suitable spot might be right under the first code block.

**Comment by l0k0ms** [comment]
Hello, 

Thank you very much for this feedback 🙇, I'm going to include this in the new APM tracing doc refactoring.

Best regards,
Pierre

**Comment by l0k0ms** [comment]
PR updated, ping @palazzem maybe we should update the pypi doc too

**Comment by palazzem** [comment]
@l0k0ms we actually have:

> ENABLED (default: not django_settings.DEBUG): defines if the tracer is enabled or not. If set to false, the code is still instrumented but no spans are sent to the trace agent. This setting cannot be changed at runtime and a restart is required. By default the tracer is disabled when in DEBUG mode, enabled otherwise

is it enough? consider that anyway I'm planning to rewrite the documentation so any input would be great.

**Comment by ndkv** [comment]
I'm sure it's just me but I missed it when hooking up the tracer for the first time. I was not expecting tracing to be off in the environment most people will try it out in first: their development box.

Adding a super short notice that tracing is off in DEBUG mode would've helped and removed the need to contact support. You provide this notice here https://docs.datadoghq.com/tracing/languages/python/ but one does not encounter this page when following the Django install steps in the APM module.

**Comment by palazzem** [comment]
@ndkv yes, actually it's pretty hidden in the documentation so it's something that probably happens to many users! Rewriting the documentation and being clear is an action item that I've added this week in our backlog. Would be great if I can keep you @ndkv in the loop when it's finished!

Your feedback will be very welcome!

**Comment by palazzem** [comment]
@ndkv this should be a bit clearer: https://github.com/DataDog/dd-trace-py/pull/476
We're deeply working in re-writing the document, it should be way better after. I'll ping you once it's ready. Thanks for this feedback!

cc @l0k0ms @burningion

**Comment by palazzem** [comment]
Hey @ndkv ! the linked PR should address the issue, making clear it's going to disable the Tracer when debug mode is enabled. We continue to work on docs anyway, so probably another refactoring will take place.

Closing the issue for now, thank you very much!
