### ISSUE TITLE
Relationship between ddtrace-run and the ddtrace module is unclear

### ISSUE THREAD

**Issue by ndkv** [DataDog/documentation#2107]
## Documentation Page
http://pypi.datadoghq.com/trace/docs/#get-started

## Issue Description 
 I fail to discern the relationship between `ddtrace-run` and the `ddtrace` Python module: when should I use which one? 

Suppose I want to instrument a worker that uses `requests` to call external endpoints. Should I run it with `ddtrace-run worker.py` or do I need to instrument `requests` explicitly in the worker's code through `from ddtrace.contrib.requests import patch()`. Or do I need to do both i.e. instrument it explicitly AND run it with `ddtrace-run`?

The last sentence in the `Get Started` section  seems to give the answer

> Please read on if you are curious about further configuration, or would rather set up Datadog Tracing explicitly in code.

but it still leaves me wondering what `ddtrace-run` instruments exactly i.e. is it the same as `patch_all` or does it trace less/more than that. Also, how does it relate to the automated web framework tracers on offer e.g. `ddtrace.contrib.django`. For example, I've a Django app that sends requests through the `elasticsearch` and `requests` modules. I've instrumented this app with `ddtrace.contrib.django`. While in my Dashboard I receive traces from the Django app I do not get anything from `elasticsearch` and `requests`. I assume that  I need to instrument them explicitly as well, but: would they be instrumented by `ddtrace-run` automatically? This is to illustrate my confussion about what does `ddtrace-run` auto trace and went to use it. 

I'd suggest splitting the `Get Started` section in two sections. The first part discusses `ddtrace-run` and explicitly mentions what it traces automatically and when it should/can be used. The second part discusses the `ddtrace` module and the various middlewares you've created for each web framework and library. 

Please feel free to ignore any of this if it's on your roadmap for the doc rewrite you are currently performing.

**Comment by l0k0ms** [comment]
Hello, 

The APM section refactoring has started: https://github.com/DataDog/documentation/pull/2909

We are going to include your feedback into it. Feel free to join us into this refactoring 👍 

Best regards,
Pierre
