### ISSUE TITLE
Request response mismatch for integrations/pagerduty API

### ISSUE THREAD

**Issue by rlhh** [DataDog/documentation#2165]
## Documentation Page
https://github.com/DataDog/documentation/blob/1823cfe0c5cb1d72d2a0a2c224139fd5522fe0e9/content/api/integrations/pagerduty.md

## Issue Description 
The integrations/pagerduty API uses "service_key" and "service_name" for the request but "service" and "key" for the response. See https://github.com/zorkian/go-datadog-api/pull/144 for more.

This is most likely the wrong place to raise the core issue where the API uses the mismatching request and response keys (please point me to the right place) but it will be helpful to have it documented.

**Comment by l0k0ms** [comment]
Hello,

Thanks for the feedback! 
We can't fix it on our side indeed but I'm going to transmit this info to our engineering team. 

Best regards,
Pierre
