### ISSUE TITLE
Documentation on the integration page is outdated

### ISSUE THREAD

**Issue by EugenKon** [DataDog/documentation#21862]
## Documentation Page

https://app.datadoghq.com/integrations?integrationId=postgres

## Issue Description
Update the corresponding `postgres` integration page with the information from https://docs.datadoghq.com/database_monitoring/setup_postgres/rds/?tab=postgres15#grant-the-agent-access page which contains actual information.

**Comment by jhgilbert** [comment]
Hi @EugenKon, which parts of the integration page were incorrect for you? The instructions are intentionally different for Database Monitoring vs. the standalone Postgres integration, but if something in the standalone instructions didn't work, happy to get it updated. Thank you!

**Comment by EugenKon** [comment]
@jhgilbert Probably it will be useful to outline diagram how this or that integration will work. I thought that instructions should be the same. If these integrations are different then I do not understand how they are differ.

**Comment by jhgilbert** [comment]
@EugenKon Thanks for the quick response -- I'll dig into this more on my side. I know the two are different, but would have to speak with the team to get a better sense. 

What problem did you run into that you were struggling to solve? That would help the team understand the goal you weren't able to meet with the existing information.

**Comment by jhgilbert** [comment]
Got it, thanks @EugenKon. I'm going to close this issue since there isn't an acute problem that needs to be fixed, but I've made a note to follow up with the PMs to ensure that the differences in these docs are intentional. Thanks again!

**Comment by EugenKon** [comment]
@jhgilbert No, Problem still exists. The question is still unanswered: why these pages are differ, how they differ. In which situation I should use one or other solution.
