### ISSUE TITLE
Remove rsyslog obsolete legacy imfile module directive PollingInterval

### ISSUE THREAD

**Issue by jasonsketchup** [DataDog/documentation#22150]
## Documentation Page

The following documentation contains outdated information that will cause rsyslog integration to fail:
* https://docs.datadoghq.com/integrations/rsyslog/?tab=ubuntuanddebian
* https://github.com/DataDog/documentation/edit/master/content/en/integrations/rsyslog.md

Relevant excerpt:

`module(load="imfile" PollingInterval="10") #needs to be done just once`

## Issue Description

TL;DR For Rsyslog version >= 8.2112, module `imfile` fails to load when obsolete legacy directive `PollingInterval` is set.

See https://www.rsyslog.com/doc/configuration/modules/imfile.html

Relevant excerpt:

> Traditionally, imfile used polling mode, which is much more resource-intense (and slower) than inotify mode. It is suggested that users turn on “polling” mode only if they experience strange problems in inotify mode. In theory, there should never be a reason to enable “polling” mode and later versions will most probably remove it.

In attempting to configure Ubuntu 22.04.1 with [rsyslog](rsyslogd: version 8.2112.0), per the documentation, the systemd journal is spammed with messages similar to:

```
mar 11 18:01:23 subuilds rsyslogd[2045687]: action 'action-9-builtin:omfile' resumed (module 'builtin:omfile') [v8.2112.0 try https://www.rsyslog.com/e/2359 ]
mar 11 18:01:23 subuilds rsyslogd[2045687]: action 'action-9-builtin:omfile' suspended (module 'builtin:omfile'), retry 0. There should be messages before this one giving the reason for suspension. >
mar 11 18:01:23 subuilds rsyslogd[2045687]: action 'action-9-builtin:omfile' suspended (module 'builtin:omfile'), next retry is Mon Mar 11 18:01:53 2024, retry nbr 0. There should be messages before>
```

Looking further back in the systemd journal, the following events are captured:
```
mar 07 20:42:10 subuilds rsyslogd[4136391]: error during parsing file /etc/rsyslog.conf, on or before line 30: parameter 'PollingInterval' not known -- typo in config file? [v8.2112.0 try https://ww>
mar 07 20:42:10 subuilds rsyslogd[4136391]: input module name 'imfile' is unknown [v8.2112.0 try https://www.rsyslog.com/e/2209 ]
```

**Comment by maycmlee** [comment]
Hi @jasonsketchup, thanks for opening this issue! We'll take a look into it and be back in touch.
