### ISSUE TITLE
Link to config.go is broken in french documentation

### ISSUE THREAD

**Issue by Anto59290** [DataDog/documentation#22390]
## Documentation Page

[Documentation page](https://docs.datadoghq.com/fr/agent/guide/environment-variables/#exceptions)

I know for sure it is incorrect in the FR version and correct in the EN version, maybe the other languages should be checked.

## Issue Description

The link number 4 : https://github.com/DataDog/documentation/blob/master/content/fr/agent/guide/environment-variables.md?plain=1#L101 should be linked [to this page](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/setup/config.go) instead [of this page](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config.go)

**Comment by hestonhoffman** [comment]
Thanks @Anto59290, I've put a PR up to fix this
