### ISSUE TITLE
MongoDB Atlas mongoprocess max normalized metrics incorrect

### ISSUE THREAD

**Issue by TechnicalFox** [DataDog/documentation#22610]
https://docs.datadoghq.com/integrations/mongodb_atlas/

Four instances of mongoprocess.norm.max should actually be mongoprocess.max.norm, as that is the metric actually being ingested. Confirmed in US3 and EU.

**Comment by neko-dd** [comment]
This was fixed through another channel. Thank you for raising the issue!
