### ISSUE TITLE
Missing a Content-Type header in restriction query code sample

### ISSUE THREAD

**Issue by jmeickle-theaiinstitute** [DataDog/documentation#22646]
## Documentation Page

https://docs.datadoghq.com/api/latest/logs-restriction-queries/#grant-role-to-a-restriction-query

## Issue Description

Granting a role to a restriction query needs a `-H "Content-Type: application/json"` like the other curl POST examples or it will result in JSON parsing errors. As-is, the example doesn't work when copied.

**Comment by clementgbcn** [comment]
This [PR](https://github.com/DataDog/documentation/pull/22985) fixed this issue.
<img width="994" alt="image" src="https://github.com/DataDog/documentation/assets/101127904/d924e112-4f3e-40fc-9345-c3941a9afb8d">
