### ISSUE TITLE
Code blocks should not allow word breaks

### ISSUE THREAD

**Issue by jyee** [DataDog/documentation#2280]
I encountered an issue writing some code within a table. It looks like the general problem is that code is inheriting a word-break style to break words:
https://github.com/DataDog/documentation/blob/master/src/scss/pages/_global.scss#L119

That doesn't seem to make sense. I can't imagine a scenario where we really want code to break in the middle of words. It seems if that were to occur, people cutting and pasting code would experience issues.

I'd opt to have `word-break: normal;` and `word-wrap: normal;` or just remove those properties, since normal is default).

**Comment by jeremy-lq** [comment]
Closed by: https://github.com/DataDog/documentation/pull/2284
