### ISSUE TITLE
Visiting app.datadoghq.eu in Firefox results in "This URL matches a known tracker and it would be blocked with Content Blocking enabled"

### ISSUE THREAD

**Issue by marcindulak** [DataDog/documentation#22914]
## Documentation Page

https://docs.datadoghq.com/data_security/real_user_monitoring/

## Issue Description

This issue was reported also to Datadog support 1647065.

### Introduction

The link present at https://docs.datadoghq.com/data_security/real_user_monitoring/ pointing to https://www.datadoghq.com/privacy/ describes Datadog approach to privacy.

<img width="1155" alt="Screenshot 2024-04-29 at 20 19 50" src="https://github.com/DataDog/documentation/assets/3178318/4bb7413b-d151-4e4f-8a1c-1308fb8c0f3b">

### The problem

However, Datadog web UI appears to be blocked by Firefox in Strict mode. When the Firefox Strict mode is relaxed, the following informational message is printed in relation to various datadoghq.com domains which serve assets for Datadog web UI

> This URL matches a known tracker and it would be blocked with Content Blocking enabled

<img width="1302" alt="Screenshot 2024-04-29 at 20 17 59" src="https://github.com/DataDog/documentation/assets/3178318/fe5d095d-1164-4a32-a600-00d821990cfc">

### Request for resolution

With the Firefox Strict mode on, the Datadog web UI is blocked with CORS errors

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://static.datadoghq.com/static/...

<img width="1301" alt="Screenshot 2024-04-29 at 20 14 04" src="https://github.com/DataDog/documentation/assets/3178318/4b3d31da-b0df-4eb7-8146-faa63ae597d7">

According to https://support.mozilla.org/en-US/kb/enhanced-tracking-protection-firefox-desktop#w_what-enhanced-tracking-protection-blocks, Firefox uses a third party [Disconnect](https://disconnect.me/trackerprotection) for the list of trackers.

Please note that user tracking of users is against certain enterprise policies. Please work with Firefox/Disconnect to remove Datadog from the list of trackers, or remove the tracking activities from the domains used by the main Datadog product.

**Comment by rtrieu** [comment]
Hi @marcindulak, thank you for calling our attention to this issue. I see that our support team has reached out to our internal team regarding this topic, so I will close this issue. If you have further suggestions on how we can improve our documentation, please feel free to make a [contribution](https://github.com/DataDog/documentation/tree/master) or leave us feedback!

**Comment by marcindulak** [comment]
I'm sorry, but I agreed to close the internal Datadog support issue on the condition that the Datadog team is informed about it, and the public issue present.

Please keep this issue open, until it is fixed, or Datadog publicly explains why it won't be fixed.

**Comment by ldynia** [comment]
As an independent viewer, it's scandalous to see this issue being closed so quickly. Please read the detailed description, comprehend it, and respond to it, not just redirect it and close it due to some KPIs.
