### ISSUE TITLE
Team ame and Handle creation rules

### ISSUE THREAD

**Issue by htnosm** [DataDog/documentation#23076]
## Documentation Page

https://docs.datadoghq.com/account_management/teams/#navigation
https://github.com/DataDog/documentation/blob/master/content/en/account_management/teams/_index.md?plain=1#L28

## Issue Description

I have identified discrepancies in the current documentation regarding the rules for creating team names and handles.
I would like you to revise the documentation to match the actual naming rules.

### Team Name:

The documentation states that allowed characters for team names include `a-z`, `A-Z`, `0-9`, and special characters `._-:/`. However, it appears that other symbols, like `^`, can also be used in team names.

### Team Handle:

The current document suggests that team handles are automatically derived from team names and include the same range of characters. 
Yet, there are specific rules about the handle that need corrections.
The documentation states 'replace spaces with underscores', however in reality, both spaces and underscores are replaced with hyphens.

Below is an example of the errors when directly entering a team handle on the Web UI:

- A team handle can only consist of letters, numbers, underscores "_", hyphens "-", colons ":", periods ".", or slashes "/"
- A team handle cannot contain any capital letters.
- The last character of a Team handle cannot be an underscore "_".
- A team handle cannot contain spaces.

**Comment by neko-dd** [comment]
Changes have been made to this document, and I think that your issue has been addressed. Thank you for raising it!
