### ISSUE TITLE
[Active Directory Integration] Broken link to active directory check sample configuration

### ISSUE THREAD

**Issue by jeff-jk** [DataDog/documentation#2328]
## Documentation Page
https://docs.datadoghq.com/integrations/active_directory/

## Issue Description 
The link to the configuration sample is broken. The link is currently https://github.com/DataDog/integrations-core/blob/master/active_directory/conf.yaml.example but should be https://github.com/DataDog/integrations-core/blob/master/active_directory/datadog_checks/active_directory/conf.yaml.example.

**Comment by jeff-jk** [comment]
I can fix this one & open a PR since I'm reviewing the active directory check implementation before pulling it into a project this week 👍

**Comment by l0k0ms** [comment]
PR merged and issue solved :)

Many thanks for your contribution 🙇
