### ISSUE TITLE
Document differences between statsd and dogstatsd

### ISSUE THREAD

**Issue by remh** [DataDog/documentation#233]
(Was https://github.com/DataDog/dd-agent/issues/605 )

* Statsd has an option to keep sending gauges at the same value forever.
* Statsd has an option to immediately stop sending data after flush

**Comment by avaughan89** [comment]
Do we feel this is sufficiently covered between? @remh @technovangelist 

https://help.datadoghq.com/hc/en-us/articles/203761125-Can-I-use-my-own-StatsD-client-What-is-DogStatsD-

http://docs.datadoghq.com/guides/dogstatsd/

**Comment by technovangelist** [comment]
looks like this was solved a while back
