### ISSUE TITLE
Unclear billing information for APM hosts

### ISSUE THREAD

**Issue by plumdog** [DataDog/documentation#23992]
## Documentation Page

https://docs.datadoghq.com/account_management/billing/pricing/#apm

See https://github.com/DataDog/documentation/blob/master/content/en/account_management/billing/pricing.md?plain=1#L24

## Issue Description

Says:

> On a high watermark plan (HWMP), the hourly measurements are ordered from highest to lowest at the end of the month, and Datadog charges based on the ninth highest measurement. The month of February is an exception and Datadog charges based on the ninth highest measurement.

Is February an exception? Or are all months the same? Eighth? Ninth?

Further, this issue was introduced here https://github.com/DataDog/documentation/commit/006d4639356d065bcb57e8e54a70f7743159c8e9#diff-3651004f37105b2a20901637edbdc626247310ff471c4626a0b5d899ec2ba5a0L25-R25 which changed the documented information for APM hosts from eighth to ninth. Unclear if that was an intentional change or just a c&p from the other similar lines.

**Comment by urseberry** [comment]
Thanks for reporting this issue! I'll look into it.

**Comment by urseberry** [comment]
Resolved by #23957
