### ISSUE TITLE
Consul Docs Update / Consul Docs Missing?

### ISSUE THREAD

**Issue by TylerLubeck** [DataDog/documentation#2449]
## Documentation Page
Consul

## Issue Description 
I'd like to update some consul docs to match my proposed change in DataDog/integrations-core/pull/1479, but I can't seem to find them anywhere. Any suggestions on where I should look?

**Comment by jeremy-lq** [comment]
@TylerLubeck Appreciate you also updating the docs! The Consul docs can be found here: https://github.com/DataDog/integrations-core/blob/37b753863e130621ff27a9fa62178db4cb4b20a1/consul/README.md

**Comment by TylerLubeck** [comment]
Thanks!
