### ISSUE TITLE
Integration API changes

### ISSUE THREAD

**Issue by sjenriquez** [DataDog/documentation#2469]
## Documentation Page
https://docs.datadoghq.com/api/?lang=bash#integrations

## Issue Description 
We have removed `run_check` argument, this can be removed from argument list and `curl` examples for:

- PagerDuty
- Slack
- Webhooks

**Comment by l0k0ms** [comment]
Hello, @sjenriquez 

Thanks for the feedback, A PR have been submitted to fix this, could you take a look ? :)

Many thanks,
Best,
Pierre
