### ISSUE TITLE
Existing page has gone 404

### ISSUE THREAD

**Issue by rmoff** [DataDog/documentation#25046]
## Documentation Page

https://docs.datadoghq.com/service_management/workflows/actions_catalog/metrics_submitmetric/

## Issue Description

I work at Decodable and we link from [our docs](https://docs.decodable.co/connect/sink/datadog.html) to https://docs.datadoghq.com/service_management/workflows/actions_catalog/metrics_submitmetric/. This started throwing 404s last week (some time after 27 August 0200 BST, when our automated link checking worked fine, and flagged this problem at 0200 the next day). It's perhaps caused by #24649?

When I try to find the page from https://docs.datadoghq.com/service_management/workflows/actions_catalog/ and click on Submit metric link I end up at a login page (https://app.datadoghq.com/account/login?next=/workflow/action-catalog#/com.datadoghq.dd.metrics/com.datadoghq.dd.metrics.submitMetric).

Is this the intended behaviour? Is there a non-login page that we can link to for the reference page? 

To be clear, this is only for the documentation, and not to use the API itself.

thanks!

**Comment by hestonhoffman** [comment]
Hi @rmoff, thanks for reaching out! This is intended behavior. We've removed these pages and the action catalog now links to each action in the app. We were seeing very low usage on these docs and they were difficult to maintain. We may revisit reference pages for the actions in the future if we can find a scalable way to document them, but this work hasn't been prioritized. Sorry for the inconvenience.
