### ISSUE TITLE
Add new function

### ISSUE THREAD

**Issue by LaRenegaws** [DataDog/documentation#2511]
## Documentation Page
https://docs.datadoghq.com/graphing/miscellaneous/functions/

## Issue Description 
We've added a new function `exclude_null` that removes null values of tags in the query result. 
Note: This is not currently available in the query editor, but can be added via the "formula" functionality in the query editor
Relevant trello issue: https://trello.com/c/Sots0aaE/477-n-a-group-filter-foon-a
PR: https://github.com/DataDog/dogweb/pull/26579

**Comment by l0k0ms** [comment]
Hello @LaRenegaws 

I just added the text for the new function, feel free to review the PR :) 

Best regards,
Pierre
