### ISSUE TITLE
dogapi w dogstatsd clarification

### ISSUE THREAD

**Issue by MisterRayCo** [DataDog/documentation#252]
By default, dogapi isn’t using DogStatsD to send points.
It’s doing it by itself (aggregation + flush), and the way it resolve hostname isn’t as powerful as the Agent.

Somewhere in your code you call :
dog_stats_api.start(api_key=‘my_api_key’)

Please use instead:
dog_stats_api.start(api_key=‘my_api_key’, statsd=True)

This will use the local DogStatsD and solve the hostname issue.

**Comment by technovangelist** [comment]
Hi Ray, 

Where do you think info like this should go?

**Comment by technovangelist** [comment]
dogapi was deprecated and a new method is used to work with dogstatsd. see http://datadogpy.readthedocs.io/en/latest/#datadog-dogstatsd-module for more info
