### ISSUE TITLE
Java Log Collection JSONLayout deprecated

### ISSUE THREAD

**Issue by florianmutter** [DataDog/documentation#25211]
## Documentation Page

https://docs.datadoghq.com/logs/log_collection/java/?tab=log4j2

## Issue Description

`JSONLayout` is considered deprecated. See https://logging.apache.org/log4j/2.x/manual/layouts.html#JSONLayout

The documentation should be updated to use `JSONTemplateLayout`. See https://logging.apache.org/log4j/2.x/manual/layouts.html#JSONTemplateLayout

**Comment by estherk15** [comment]
Thanks for raising this issue @florianmutter! I've created a task for the documentation team to update this after the new `JSONTemplateLayout` is tested by engineering!
