### ISSUE TITLE
Confusing naming about span tags

### ISSUE THREAD

**Issue by theo303** [DataDog/documentation#25630]
Hello !

## Documentation Page
https://docs.datadoghq.com/tracing/trace_collection/tracing_naming_convention/#span-attributes

## Issue Description
In this page fields are named "Span attributes" which are said to be different from "Span tags". But in datadog it seems to me that they are named "Span tags": 
![Image](https://github.com/user-attachments/assets/d6e4d699-13a8-4a72-bce2-2ea2c836b0e5). 
Same in the golang lib, the function is named SetTag: https://github.com/DataDog/dd-trace-go/blob/main/ddtrace/tracer/span.go#L113
Am I misunderstanding something ?

Thanks

**Comment by brett0000FF** [comment]
@theo303 - Thanks for reaching out! You are correct--this is misleading.

I confirmed with our Product team that the definitions on the [page you linked](https://docs.datadoghq.com/tracing/trace_collection/tracing_naming_convention/#span-attributes) are correct. To address this, they are going to update the UI to no longer say "Span Tags" where you highlighted.

I am going to close this for now, but don't hesitate to re-open if you need any further clarification. Thanks again!
