### ISSUE TITLE
sqlserver has additional ado connection string option

### ISSUE THREAD

**Issue by derekwbrown** [DataDog/documentation#2594]
## Issue Description 
See PR https://github.com/DataDog/integrations-core/pull/1673.  Created a new configuration option to deal with the fact that MS has stated they're deprecating the current ADO connection string.

**Comment by l0k0ms** [comment]
@derekhowles Thanks for the heads up! 🙇  
We are going to look into this and see if there is a need for a doc update.

Best,
Pierre
