### ISSUE TITLE
Explain to customers how to handle large numbers of MONITORING log lines for lambda log-based monitoring

### ISSUE THREAD

**Issue by peterashwell** [DataDog/documentation#2605]
## Documentation Page

https://www.datadoghq.com/blog/how-to-monitor-lambda-functions/

## Issue Description 

Our lambda log based monitoring is error prone and we should tell customers how to use it effectively, namely, if large numbers of log lines are published from lambda invocations we cannot collect them all and turn them into metrics.

Opening this issue as a starting point to add a section here explaining what the event means (we publish and event telling you you have too many events) and how to fix it.

We get lots of support cases on this.

In general, the way to fix is to publish at most one log line per invocation for either a count or a gauge. Customers tend to publish lots in a single invocation, usually inside a for loop.

**Comment by l0k0ms** [comment]
@peterashwell Is it still a thing?
