### ISSUE TITLE
Wrong address to api_host

### ISSUE THREAD

**Issue by osnibjunior** [DataDog/documentation#26330]
## Documentation Page
Documentation: https://github.com/DataDog/documentation/blob/master/content/en/developers/guide/dogshell.md
Public: https://docs.datadoghq.com/developers/guide/dogshell/

## Issue Description
In this page, the item `api_host` is passed using only `https://datadoghq.com`, but this is wrong. Is necessary to add `api` in this URL to work. Like this: `https://api.datadoghq.com`. Look the example

### Wrong configuration
![Image](https://github.com/user-attachments/assets/561991b0-d6d7-4ece-a2b7-99a1d36dbff1)

### Right configuration
![Image](https://github.com/user-attachments/assets/fc4da8d0-e3b6-4afa-a114-ebfee2a5f60d)

**Comment by hestonhoffman** [comment]
Hi @osnibjunior, thanks for the suggestion! The above PR should fix this :)
