### ISSUE TITLE
Documentation on Integration functions

### ISSUE THREAD

**Issue by Xorima** [DataDog/documentation#2697]
**Is your feature request related to a problem? Please describe.**
I am unable to find documentation around the datadog_checks python libary especially functions used in the new integration section of the documentation, eg:
```
    c.check(instance)
    aggregator.assert_service_check('my_check.all_good', MyCheck.OK)
```

**Describe the solution you'd like**
Documentation for the datadog_checks libary and the functions which we should be using when building integrations

I am still learning python and datadog so if I am incorrect please do offer some guidance

**Comment by jeremy-lq** [comment]
The check API is documented [here](https://github.com/DataDog/datadog-agent/blob/master/docs/dev/checks/python/check_api.md), with the rest of the developer docs [here](https://github.com/DataDog/datadog-agent/tree/master/docs/dev). We're currently working on a more comprehensive "Developer Tools" section as part of the main docs. Does this contain the information you need?

**Comment by Xorima** [comment]
Hi @jeremy-lq,

They cover the creation of checks but not the testing of the checks, in the example above I gave I do not know what my_check.all_good and MyCheck.OK relate too

I am of the understanding that to contribute to the upstream integrations-core/extra I will need to supply decent test coverage?

**Comment by jeremy-lq** [comment]
Submissions to integrations-extras do require tests. The doc for writing integration tests is [here](https://github.com/DataDog/integrations-core/blob/master/docs/dev/new_check_howto.md#writing-tests).

**Comment by Xorima** [comment]
I am still struggling to find documentation for the function: ```aggregator.assert_service_check```

This is not covered in the linked to documentation, it is called but never explained.

**Comment by jeremy-lq** [comment]
Thanks for the feedback. I've passed this along to the integrations team and @phrawzty, who is currently working on our developer docs. Stay tuned for continued improvements. Also a heads up that we run [Community Office Hours](https://github.com/DataDog/dd-agent/wiki/Community-Office-Hours) twice monthly.

**Comment by jeremy-lq** [comment]
I've confirmed we'll be updating the doc next sprint. Thanks again for the feedback.
