### ISSUE TITLE
How do I get the list of hosts and their IDs?

### ISSUE THREAD

**Issue by alq666** [DataDog/documentation#31]
Other API endpoints require the host_id to be passed, yet there is no clear way to get these IDs without clicking around on the infrastructure overview.

This will drive API changes, but it's probably a good place to start.

**Comment by technovangelist** [comment]
Due to a change in the API a year or so back I believe we stopped showing host IDs and only get host names. There were some API calls that required host IDs but they don't anymore. There is no need for them and no way to get them.  This is further described in #472
