### ISSUE TITLE
`is_match` monitor conditional variable isn't clear

### ISSUE THREAD

**Issue by LotharSee** [DataDog/documentation#3112]
## Documentation Page

See https://docs.datadoghq.com/monitors/notifications/?tab=is_matchis_exact_match#message-template-variables

https://github.com/DataDog/documentation/blob/master/content/monitors/notifications.md#conditional-variables

## Issue Description

The examples of `is_match` doesn't show how the substring matching works. Examples are of the same nature as `is_exact_match` aka. they are examples with exactly the same strings.
Examples illustrating the partial matching would be more useful.

I'd open a PR myself but I actually don't know which way it works (is it `COMPARISON_STRING` in `tag` or `tag` in `COMPARISON_STRING`?). 

Nit: in the table, I'd put `is_exact_match` just below `is_match`, not below `is_recovery`.

PS: there is no "Monitor" label, I'm not sure which one to apply in Github.

**Comment by l0k0ms** [comment]
Hello @LotharSee,

Many thanks for this feedback. 🙇  I just opened a PR to correct the doc.

If you spot other glitches feel free to open us another issue

Best,
Pierre
