### ISSUE TITLE
GCP integration documentation

### ISSUE THREAD

**Issue by andor44** [DataDog/documentation#3128]
It'd be good to have official documentation on the GCP integration API, so it could be referenced for other projects, such as the [Datadog Terraform provider](https://github.com/terraform-providers/terraform-provider-datadog).

**Comment by l0k0ms** [comment]
Hello, 

Many thanks for this feedback, but I'm not entirely sure to understand what you have in mind.
Do you mean documenting the GCP integration configuration as here: https://docs.datadoghq.com/api/?lang=python#integrations ?

Best regards,
Pierre

**Comment by andor44** [comment]
Yep, that's exactly what I'm looking for. I talked to our DD account manager recently and I was told that a GCP integration already exists. It'd be good to get it documented.

**Comment by l0k0ms** [comment]
ok, many thanks for the precision. I'm going to look internally if such API is available. 

We indeed have a GCP integration available, its documentation can be found in the public documentation: https://docs.datadoghq.com/integrations/google_cloud_platform/ or directly in your Datadog application: https://app.datadoghq.com/account/settings#integrations/google_cloud_platform

I'm getting back to you as soon as I have some updates from our engineering teams.

**Comment by l0k0ms** [comment]
Hello, 

The API is available 🥂, this PR adds it to the main doc: https://github.com/DataDog/documentation/pull/3181 we still need to validate it but it should be publicly displayed soon. 

Many thanks for your feedback 🙇 I'm going to close this issue, but if you spot other glitches in the documentation feel free to open another one.

Best,
Pierre
