### ISSUE TITLE
Update editconfig

### ISSUE THREAD

**Issue by chenrui333** [DataDog/documentation#3255]
When I submit [my PR](https://github.com/DataDog/documentation/pull/3254), it seems incurs lots of file format changes like removing the trailing spaces. 

After looking at the repo's [editorconfig](https://github.com/DataDog/documentation/blob/master/.editorconfig), I found there is not much file formatting rules there, so it may be good to incorporate some rules to normalize the file changes.

**Comment by l0k0ms** [comment]
Hello,

The PR is now merged, many thanks for this doc update 🙇 

If you spot other glitches or possible improvements feel free to submit more PR. 🎉 

Best,
Gus
