### ISSUE TITLE
Let's remove APM API "Send services" section

### ISSUE THREAD

**Issue by LotharSee** [DataDog/documentation#3290]
"Send services" API (https://docs.datadoghq.com/api/?lang=python#send-services) is deprecated, it got replaced with the usage of the "span.type" attribute https://docs.datadoghq.com/tracing/visualization/services_list/#services-types

I'd suggest we fully remove that part of the documentation.

**Comment by l0k0ms** [comment]
Hello @LotharSee,

Many thanks for this feedback, PR has been opened to fix this :) 

If you see other glitches in the documentation, feel free to report them 🙇 

Best,
Pierre
