### ISSUE TITLE
Reference language integrations in Kubernetes APM documentation

### ISSUE THREAD

**Issue by ntbrittain** [DataDog/documentation#3374]
**Is your feature request related to a problem? Please describe.**
https://docs.datadoghq.com/tracing/setup/kubernetes/?tab=go
This page describes setting up APM tracing in Kubernetes. The language specific implementation provides an example for setting up tracing. Reading that page, it is not obvious that further framework/library specific integrations must also be included to get anything useful out of the APM tracing.

**Describe the solution you'd like**
I would like to see a link to the language specific framework/library integrations listed on the language specific pages, such as https://docs.datadoghq.com/tracing/setup/go/#integrations

**Describe alternatives you've considered**
The same information could be duplicated into the kubernetes page, but that seems less than ideal.

**Additional context**
N/A

**Comment by cswatt** [comment]
Thanks for your feedback! We've completely restructured this whole section. Hopefully it's clearer now!
