### ISSUE TITLE
Status URL typo in documentation

### ISSUE THREAD

**Issue by stakoz** [DataDog/documentation#350]
In agent guide (Windows version), a specified port number in status URL is incorrect. This URL `http://localhost:17125/status` should be `http://localhost:17123/status` instead.

**Comment by technovangelist** [comment]
Hi @stakoz - Thanks for alerting us to this. I just talked with a few others about this. Port 17123 is actually the listening port for the forwarder. The web endpoint for the status page has been removed. The info is now available from Settings -> Agent Status. I will fix that in the docs right away.

Thanks again for pointing this out and please do let us know if you find any other inaccuracies in the docs.
