### ISSUE TITLE
Document the metric query language and data model

### ISSUE THREAD

**Issue by clofresh** [DataDog/documentation#36]
For example, the differences between functions and aggregators:

 Yes, min, max and avg aren't functions per se, they're aggregators. We haven't documented our model as well as we should, but we consider functions as transforms of a single metric series, whereas aggregators combine many metric series's across tags. For example, if we had a metric called foo with values:

host:a = 1,1,4,1,1
host:b = 2,2,0,2,2

Using the min aggregator like min:foo{*} would turn the two series into a single series:

1,1,0,1,1

If we added a min function like min(foo{host:a}), we would get just a single value of 1.

If we had min(foo{*}), we'd still need an aggregator, in this case avg is assumed, so that would be:

avg:foo{*} = 1.5, 1.5, 2, 1.5, 1.5
min(avg:foo{*}) = 1.5

If we wanted the hosts in tact, we would say min(foo{*} by {host}), then we'd apply the function to each series:

min(host:a) = 1
min(host:b) = 0

**Comment by technovangelist** [comment]
Hi @clofresh , 

Is the info here still accurate?

**Comment by clofresh** [comment]
The particular example is still accurate and we still don't document how aggregation works in the [graphing guide](http://docs.datadoghq.com/graphing/), and now we do both space and time aggregation depending on the feature.

**Comment by technovangelist** [comment]
great, I am looking at a rewrite of that guide and will incorporate this in as well.

**Comment by technovangelist** [comment]
the guide has been updated and I think i address the original request
