### ISSUE TITLE
HDFS integration documentation is a stub

### ISSUE THREAD

**Issue by StephenWeber** [DataDog/documentation#373]
http://docs.datadoghq.com/integrations/hdfs/ has essentially no information, especially compared to the best-documented integrations. Needs links to check and to example, discussion of example configuration file, and any troubleshooting that Datadog support has found to be useful. 

The entirety of the current documentation:
![screenshot 2015-04-17 09 55 26](https://cloud.githubusercontent.com/assets/153632/7206623/1348ad2a-e4e8-11e4-9330-1b9d9274c445.png)

File in question: https://github.com/DataDog/documentation/blob/master/content/integrations/hdfs.md

**Comment by technovangelist** [comment]
PR #393 doesnt answer all your questions, but its a start. Did you end up getting something that works?

**Comment by StephenWeber** [comment]
That gives us enough to go by, the example in that documentation is roughly what we wrote but have not deployed. Thanks!
