### ISSUE TITLE
Datadog Agent - Validating python version 

### ISSUE THREAD

**Issue by sysadmin-x** [DataDog/documentation#378]
In the debian and ubuntu agent usage section (http://docs.datadoghq.com/guides/basic_agent_usage/deb/ and http://docs.datadoghq.com/guides/basic_agent_usage/ubuntu/) the documentation mentions using a python command to validate the python version installed on the host the agent is running on:

![image](https://cloud.githubusercontent.com/assets/599677/7303775/b918bff6-e9a7-11e4-950a-11e661ddc55a.png)

1)   /etc/init.d/datadog-agent is not a directory, but is instead the agent wrapper script.  The 'cd' command as a result fails.
     a) What is the goal of of changing directory to whatever the intended directory would have been?  Is the assumption that you should be changing to a directory python can be executed from?
2)  I'm using a newer version of python (2.7.8), and there is not a config module that can be imported (at least not with this version).  I would need to test on an older version of python such as 2.4 if this module exists and can be validated using the method in the screenshot above.  In 2.7.8, using the following command will work:  
            `python -c 'import sys; print (sys.version)'`

Could this information be updated to ensure when users are pointed at the documentation they can correctly validate their python version for troubleshooting purposes?

**Comment by technovangelist** [comment]
Hi there @sysadmin-x , 

Thanks for creating this issue. Thats a good catch. I will look into why its there (1a) and fix it.

**Comment by technovangelist** [comment]
Hi @sysadmin-x 

This made a lot more sense in the agent before v5. The correct command in v5+ is 
```/opt/datadog-agent/embedded/bin/python -c 'import config; print config.get_version()’```

but since the agent now includes python, it may not make any sense to include the section. What was the problem you were trying to troubleshoot?

**Comment by sysadmin-x** [comment]
Hi @technovangelist ,

Thanks for the reply and info!  I tried using the updated command you have above on another Linux OS today to see if perhaps the OS image I was using was at fault.  Today I'm using RHEL 6.6 and I'm still not getting the command you have specified using the embedded python to work.

I get the following:
`sudo /opt/datadog-agent/embedded/bin/python -c 'import config; print (config.get_version)’`
`Traceback (most recent call last):`
`File "<string>", line 1, in <module>`
`ImportError: No module named config`

However, my original command continues to work when using the embedded python from the agent:

`sudo /opt/datadog-agent/embedded/bin/python -c 'import sys; print (sys.version)'`
`2.7.9 (default, Apr 16 2015, 17:05:52)`
`[GCC 4.1.2 20080704 (Red Hat 4.1.2-55)]`

As for your last question, I wasn't trying to troubleshoot anything in particular, but rather following all documentation myself to be familiar for when any potential users I support ask questions.

**Comment by technovangelist** [comment]
since the command no longer has any value it has been removed. Thanks for pointing out the issue.
