### ISSUE TITLE
Indicated Winston configuration generates an error.

### ISSUE THREAD

**Issue by wildapt01** [DataDog/documentation#4070]
## Documentation Page
[https://github.com/DataDog/documentation/blob/master/content/en/logs/log_collection/nodejs.md](https://github.com/DataDog/documentation/blob/master/content/en/logs/log_collection/nodejs.md)
## Issue Description
The `winston` configuration example uses `winston v2.x` syntax to declare the logger.

If used with `winston v3.x`, it will generate an error `TypeError: winston.Logger is not a constructor` and kill the application execution.

## Suggested modification
Replace the _Log to file_ section by:

 ## Log to File

**Note**: the following instructions apply to **winston v3.x**.
Read the [winston v2.x documentation](https://github.com/winstonjs/winston/tree/2.x) if using winston v2.x.

Install the dependencies:

```js
// ~/.../my-app
npm install morgan winston app-root-path --save
```

Create a configuration file for winston as follow:

```js
// ~/.../my-app/winston-config.js

const { createLogger, format, transports } = require('winston');
const appRoot = require('app-root-path'); // Or 'path' if preferred

const logger = createLogger({
  level: 'info',
  exitOnError: false,
  format: format.json(),
  transports: [
    new transports.File({ filename: `${appRoot}/logs/<FILE_NAME>.log` }),
  ],
});

if (process.env.NODE_ENV !== 'production') {
  logger.add(
    new transports.Console({
      format: format.simple(),
    })
  );
}

logger.stream = {
  write: function(message) {
    logger.info(message);
  },
};

module.exports = logger;
```

Then in the file where the middleware is set up:

```js
// ~/.../my-app/index.js

//...
const morgan = require('morgan'); // or other HTTP logger
const logger = require('/winston-config.js');

// ...
// Logging middleware
app.use(morgan('common', { stream: logger.stream }));

// ...
// Error handling endware - example
app.use((err, req, res, next) => {
  winston.error(
    `${err.status || 500}
    - ${err.message} - ${req.originalUrl} - ${req.method} - ${req.ip}`
  );
  res.status(err.status || 500).send(err.message || 'Internal server error.');
});

// ...
```

In `<FILE_NAME>.log` the following JSON can be seen:

```js
{"message":"::ffff:10.0.2.2 - - [20/Feb/2019:00:40:37 +0000] \"GET / HTTP/1.1\" 304 -\n","level":"info"}
{"message":"404 - Not found! - /foo - GET - ::ffff:10.0.2.2","level":"error"}
{"message":"::ffff:10.0.2.2 - - [20/Feb/2019:00:41:11 +0000] \"GET /foo HTTP/1.1\" 404 10\n","level":"info"}
{"message":"::ffff:10.0.2.2 - - [20/Feb/2019:00:58:49 +0000] \"GET / HTTP/1.1\" 304 -\n","level":"info"}
>```

**Comment by l0k0ms** [comment]
Hello, 

Sorry for the delay here, I created a PR to update the code displayed in order to take into account the Winston version. 

Your code examples are great! but I removed the morgan logic to only focus on Winston in order to be as general as possible, what do you think about it? Any feedback is more than welcome :) 

Best regards,
Pierre

**Comment by l0k0ms** [comment]
Hello Again, 

We merged the PR, If you have any feedback feel free to add it here or to open a new issue :)

Best regards,
Pierre

**Comment by wildapt01** [comment]
Hi Pierre,

No problem, I added the morgan logic because it's what I use as a logger
and it's one of the most popular in the Node-verse. As well, it was an
example all baked in, just needing a copy-and-paste. It is totally
understandable you wish to keep it more general.

Besides, my guess is log files leverage is probably done through APM much
more often than through the Node integration.

Thank you for your follow-up!

Best regards,

Patrick Boutier
