### ISSUE TITLE
Kubernetes docs + links unclear

### ISSUE THREAD

**Issue by tonglil** [DataDog/documentation#4167]
**Describe the bug**
The docs and links are unclear.

**Expected behavior**
1. Is there some difference between these two setups? It is not clear from the reading what is recommended and if one is a prerequisite of another.
https://docs.datadoghq.com/agent/kubernetes/daemonset_setup/
https://docs.datadoghq.com/agent/kubernetes/cluster/

Am I suppose to choose between DaemonSet, Host, Cluster, Helm, or is it suppose to be some combination of them (DaemonSet + Cluster)? What are the tradeoffs?

2. It would be great if the docs outlined that the DaemonSet solution does not collect kube-state-metrics `kubernetes_state.*` nor `kubeproxy.*` metrics (or at least it doesn't seem to for me).

3. https://docs.datadoghq.com/agent/kubernetes/cluster/#setup
there is no "datadog-agent" dir in https://github.com/DataDog/datadog-agent/tree/master/Dockerfiles/manifests/cluster-agent/rbac.

4. https://docs.datadoghq.com/agent/kubernetes/cluster/#create-the-cluster-agent-and-its-service
> "Locate the following manifests"
where? from github or was I suppose to download this earlier?

It is hard to review the various files for the cluster agent setup which is discouraging. I'd like to understand what I am applying and more clarity around which file belongs to which agent and is doing what.

Getting lost in the docs is the easiest way to abandon trying something.

**Comment by cswatt** [comment]
Hi, thanks for your feedback!

We're currently working on a better "landing" experience for explaining which Kubernetes install to use.  In the meantime, feel free to reach out to Datadog support for any specific questions you may have!
