### ISSUE TITLE
API For Event Stream Query using Shell

### ISSUE THREAD

**Issue by sysadmin-x** [DataDog/documentation#419]
Just curious what shell the examples are being written against for the Event Stream Query API?  It looks like in bash and tsch that the 2nd date variable encounters an error due to the '-v' parameter being passed that is invalid.

I've found that using the syntax below works for a proper epoch date matching what I presume was the intended output.
currentttime2=$(date --date='1 day ago' +%s)

Second, in the Shell example, should the use of "$currenttime" and "$currenttime2" be switched for the start and end values being passed in the cURL statement?  In the current documentation, the query would be evaluating "$currenttime" as the start date" and 1 day ago as the end date which will always return an empty "events:[]" JSON string.

currenttime=$(date +%s)
currenttime2=$(date -v -1d +%s)
curl -G -H "Content-type: application/json" \
    -d "start=${currenttime2}" \
    -d "end=${currenttime}" \
    -d "api_key=9775a026f1ca7d1c6c5af9d94d9595a4" \
    -d "application_key=87ce4a24b5553d2e482ea8a8500e71b8ad4554ff" \
    'https://app.datadoghq.com/api/v1/events'

Thanks,
Aaron

**Comment by technovangelist** [comment]
Hi Aaron, 

Thats a good point. I will go through and review the examples for use with bash as thats more standard. 

Thanks for pointing this out.

**Comment by technovangelist** [comment]
Originally I was thinking it might use the shell I am configured to use. Sometimes thats zsh but now mostly fish. I see in the code for nanoc that we test using /bin/sh so the code samples have been updated with a #! at the beginning
