### ISSUE TITLE
Negotiation Typo on AWS ELB Page

### ISSUE THREAD

**Issue by Phansa** [DataDog/documentation#4202]
## Documentation Page
https://docs.datadoghq.com/integrations/amazon_elb/#data-collected
## Issue Description
For aws.elb.client_tlsnegotiation_error_count the description says "Number of TLS negociation errors"
For aws.applicationelb.client_tlsnegotiation_error_count the description says "Number of TLS negociation errors".
I was trying to copy paste this description and found the typo. I'm not seeing where in the codebase this gets populated, I only see this file which is making a call to "get-metrics-from-git" -> https://github.com/DataDog/documentation/blob/master/ja/content/integrations/awselb.md

**Comment by l0k0ms** [comment]
Hello, 

Many thanks for this feedback 🙇 
This is indeed coming from an internal repo of Datadog. We fixed the the issue, the metric desc should be updated soon. :) 

Best regards,
Pierre
