### ISSUE TITLE
How do I track cron jobs Missing Comma

### ISSUE THREAD

**Issue by homelinen** [DataDog/documentation#424]
In "How do I track cron jobs?" section there is the following:

```
dogwrap -n "Vacuuming mytable" -k $API_KEY --submit_mode errors "psql -c 'vacuum verbose my_table' 2>&1 /var/log/postgres_vacuums.log
```

Which is missing the final comma. This is also misleading because the `>>` is missing before `/var/log/postgres_vacuums.log` which makes it look like dogwrap would be logging to the file which I do not believe is the way it works.

**Comment by technovangelist** [comment]
So what should the command be?

**Comment by technovangelist** [comment]
what comma are you referring to?

**Comment by technovangelist** [comment]
I can't see any comma that is missing, but there is a quote missing.
