### ISSUE TITLE
Abusive `Make sure you replace the API ` comment in snippets

### ISSUE THREAD

**Issue by yannmh** [DataDog/documentation#427]
`Make sure you replace the API and or APP key below with the ones for your account` [comment] (https://github.com/DataDog/documentation/blob/master/lib/snippets.rb#L27) is displayed automatically on code snippets, since https://github.com/DataDog/documentation/commit/494337ca140f119f4d4d0b62b548261f75a3782d.

We should add more controls on where we want this comment to be printed, for instance on
http://docs.datadoghq.com/guides/metrics/, we have

```
# Make sure you replace the API and or APP key below with the ones for your account

pip install datadog
```
or
```
# Make sure you replace the API and or APP key below with the ones for your account

from datadog import stats
```

@technovangelist can you have a look ?

**Comment by technovangelist** [comment]
these aren't code samples. they shouldn't be added as stand alone code samples but rather be added inline.

**Comment by yannmh** [comment]
I found also the comment in 
http://docs.datadoghq.com/guides/agent_checks/

**Comment by degemer** [comment]
Some people seems to be confused by this comment everywhere.

The issue is that by default this option is applied, unless `:nocomments` is set to true. It should probably be the opposite, a opt-in option, since I guess it's not needed everywhere.

What do you think @technovangelist ?

**Comment by technovangelist** [comment]
Its needed in most places, but many of the examples given here shouldn't be done as separate code samples but rather inline since they are unable to be run as is. I am going through all the ones mentioned and converting to inline in both english and japanese right now.

**Comment by yannmh** [comment]
Thanks a lot @technovangelist

**Comment by degemer** [comment]
My bad, I just had a quick look at the code. It seems to be fixed for both pages. Thanks!

**Comment by technovangelist** [comment]
just finished all the code samples that had the problem.
