### ISSUE TITLE
Missing "get all dashboards" section

### ISSUE THREAD

**Issue by eocantu** [DataDog/documentation#4303]
## Documentation Page
https://docs.datadoghq.com/api/#dashboards

## Issue Description
The GET `https://api.datadoghq.com/api/v1/dashboard` API is not documented (listing all dashboards). Based on https://github.com/DataDog/datadogpy/blob/master/datadog/api/dashboards.py#L7 it seems this operation is supported.

**Comment by ruthnaebeck** [comment]
Hello @eocantu,
Thanks for your comment. We are working to add this to our documentation with #4180.
