### ISSUE TITLE
Invalid link on agent/apm page for primary tags

### ISSUE THREAD

**Issue by JordanSussman** [DataDog/documentation#4369]
## Documentation Page

https://docs.datadoghq.com/agent/apm/

## Issue Description

Currently, the [primary tag](https://docs.datadoghq.com/agent/apm/#primary-tags) and [Learn how to configure primary tags](https://docs.datadoghq.com/agent/apm/#primary-tags) hyperlinks go nowhere.

**Comment by l0k0ms** [comment]
Hello, many thanks for this feedback, I have opened a PR to fix those links and others that were outdated :)

If you spot other glitches, feel free to open another issue 🙇 

Best,
Pierre
