### ISSUE TITLE
Docker logs configuration is different than docker-less logs configuration

### ISSUE THREAD

**Issue by satiani** [DataDog/documentation#4371]
## Documentation Page

https://docs.datadoghq.com/logs/log_collection/?tab=streamlogsfromtcpudp
https://docs.datadoghq.com/logs/log_collection/docker/?tab=containerinstallation

## Issue Description
This page describes logs collection configuration for the agent:

https://docs.datadoghq.com/logs/log_collection/?tab=streamlogsfromtcpudp

Adding `logs_enabled: true` to `datadog.yaml` did not do the trick for the `datadog/agent` docker image. Instead, following the instructions here worked (i.e. `-e DD_LOGS_ENABLED=true`)

https://docs.datadoghq.com/logs/log_collection/docker/?tab=containerinstallation

The two pages above should probably reference each other to reduce frustration by people trying the agent for the first time using docker containers.

**Comment by l0k0ms** [comment]
Hello, 

Many thanks for this feedback 🙇  
I have opened a PR to add a note in order to avoid confusion on those instructions in the future, feel free to review it and leave a comment if need be. 

If you spot other glitches in our doc, feel free to open another issue ;)

Best,
Pierre
