### ISSUE TITLE
Incorrect paths in Mac OS X doc

### ISSUE THREAD

**Issue by tomruggs** [DataDog/documentation#451]
Based on an install I did today the instructions in http://docs.datadoghq.com/guides/basic_agent_usage/osx/ are full of inconsistencies.

~/.datadog-agent/bin/agent is actually found at /usr/local/bin/datadog-agent

The info command is 
/usr/local/bin/datadog-agent info

and not 
~/.datadog-agent/bin/info

The config files are 
~/.datadog-agent/datadog.conf
~/.datadog-agent/datadog.conf

and not 
~/.datadog-agent/agent/datadog.conf
~/.datadog-agent/agent/conf.d

All logs are in 
/var/log/datadog

and not 
~/.datadog-agent/supervisord/logs/

**Comment by technovangelist** [comment]
Hi Tom,

Thanks for leaving this comment. We recently changed the paths for the mac agent. Looks like we missed updating the documentation. Thanks for catching that. Fixed in #462
