### ISSUE TITLE
Downtimes are Immutable

### ISSUE THREAD

**Issue by platinummonkey** [DataDog/documentation#4553]
For monitor-app we are making downtimes immutable. For the UI user, there will be no difference in behavior we will automatically orchestrate the cancellation and creation of it's replacement. The default behavior for API users is the same as well.

We will want to update the documentation to reflect this behavior as downtime ID's will change if the conditions are met. There are a few exceptions below where we won't change the ID, but have to deal with updating timeline for future downtimes or extending the life of an existing downtime.

```
Immutable downtimes which have stricter requirements. Essentially:
        1. future downtime start times can be changed (so long as they do not start within 1 minute)
        2. end times are allowed to be extended (or shortened up to 1 minute out)
        3. downtimes can still be cancelled immediately.
        4. all other modifications to a downtime are strictly prohibited. Except `message`
```

**Comment by l0k0ms** [comment]
Hello, 

Many thanks for the ping, I'm going to track this in our internal trello board. 

Best regards,
Pierre
