### ISSUE TITLE
Dead Link in http://docs.datadoghq.com/guides/monitoring/

### ISSUE THREAD

**Issue by giviz** [DataDog/documentation#479]
Creating a Monitor
Nagivate to the Create Monitors page by highlighting the “Monitors” tab in the top menu and selecting the “Create Monitors” sub-tab. You will be presented with a list of monitor types on the left. This guide will walk through the configuration of each type.

Link on Create Monitors is 404

**Comment by technovangelist** [comment]
Thanks for catching that. I have fixed the issue.
