### ISSUE TITLE
Support HTTP headers without `X-` prefix

### ISSUE THREAD

**Issue by sebdeckers** [DataDog/documentation#5041]
**Is your feature request related to a problem? Please describe.**

The use of `X-` prefix on HTTP headers used by Datadog seems outdated.

See: https://github.com/DataDog/documentation/blob/f8a0c7e68c75699ab5de510f9c9cb48e58897e08/content/en/synthetics/apm/_index.md#how-are-traces-linked-to-tests

> Datadog uses the distributed tracing protocol and sets up the following HTTP headers:
> 
> * `x-datadog-trace-id`, generated from the Synthetics backend. Allows Datadog to link the trace with the test result.
> * `x-datadog-parent-id: 0`
> * `x-datadog-origin: synthetics`, to make sure the generated traces don't affect your APM quotas. See below.
> * `x-datadog-sampling-priority: 1`, [to make sure that the Agent keeps the trace][9].

As per RFC 6648 & RFC 7231:

> 3.  Recommendations for Creators of New Parameters
> 
>    Creators of new parameters to be used in the context of application
>    protocols:
> 
>    1.  SHOULD assume that all parameters they create might become
>        standardized, public, commonly deployed, or usable across
>        multiple implementations.
> 
>    2.  SHOULD employ meaningful parameter names that they have reason to
>        believe are currently unused.
> 
>    3.  SHOULD NOT prefix their parameter names with "X-" or similar
>        constructs.
> 
>    Note: If the relevant parameter name space has conventions about
>    associating parameter names with those who create them, a parameter
>    name could incorporate the organization's name or primary domain name
>    (see Appendix B for examples).

https://tools.ietf.org/html/rfc6648#section-3

>    Authors of specifications defining new fields are advised to keep the
>    name as short as practical and not to prefix the name with "X-"
>    unless the header field will never be used on the Internet.  (The
>    "X-" prefix idiom has been extensively misused in practice; it was
>    intended to only be used as a mechanism for avoiding name collisions
>    inside proprietary software or intranet processing, since the prefix
>    would ensure that private names never collide with a newly registered
>    Internet name; see [BCP178] for further information).

https://tools.ietf.org/html/rfc7231#section-8.3.1

**Describe the solution you'd like**

Support for all Datadog headers without the `X-` prefix. Backwards compatibility can be maintained, if desired.

**Describe alternatives you've considered**

Register the non-prefixed headers with IANA. Perhaps administratively excessive.

- Registry: https://www.iana.org/assignments/message-headers/message-headers.xhtml
- Procedure: https://tools.ietf.org/html/rfc3864

**Additional context**

**Comment by apigirl** [comment]
Hi @sebdeckers - thanks so much for this feedback! Since this is a product enhancement request, we ask that you [file a ticket with our support team](https://docs.datadoghq.com/help/) - they have a system in place to follow up on and track enhancement requests, and they will also let you know if we eventually do end up deciding to support this. 

Since this is not a documentation related issue or request, I am going to close this issue, but please don't hesitate to reach out to us again or to our support team if you notice any issues or have any other suggestions.

~ Datadog Documentation Team

**Comment by sebdeckers** [comment]
@apigirl Apologies for the misplaced issue. Email sent to support@datadoghq.com
