### ISSUE TITLE
tooltip says agent age out in 3 hours, but docs say 2 hours

### ISSUE THREAD

**Issue by jeffwidman** [DataDog/documentation#5111]
https://docs.datadoghq.com/graphing/faq/historical-data/ says after removing an agent it'll stop reporting in 2 hours, yet when I go to the [infrastructure list page](https://app.datadoghq.com/infrastructure) and find a host that I've removed an agent from, it has a `???` next to it... when I roll over that, the tooltip that pops up says 3 hours:
<img width="267" alt="Screen Shot 2019-07-30 at 11 13 59 AM" src="https://user-images.githubusercontent.com/483314/62157765-c630d780-b2c2-11e9-87bd-4d04cfdfd60d.png">

2 hours != 3 hours

**Comment by l0k0ms** [comment]
Hello, 

Many thanks for this feedback 🙇 
We just fixed the tooltip within the app, it should be shipped in prod very soon. The doc was right, the real value is `2 hours`.

If you find other glitches, feel free to open more issues. 
Best regards,
Pierre
