### ISSUE TITLE
Network Dashboard Widget Documentation

### ISSUE THREAD

**Issue by jnelken** [DataDog/documentation#5289]
AKA something to go here https://docs.datadoghq.com/graphing/infrastructure/network/
that looks like https://docs.datadoghq.com/graphing/infrastructure/process/

This is still a work in progress, but target release is before the end of Q3
https://github.com/DataDog/web-ui/pull/4418
https://trello.com/c/la3y6YrZ
You can ping me on Slack (@)jake.nelken or (@)sunny for updates

**Comment by sunny** [comment]
(👋)

**Comment by l0k0ms** [comment]
Hello, 

Thanks for pinging us 🙇, i'm going to close this issue and track this on our internal trello board.

Best,
Pierre
