### ISSUE TITLE
Update to call out Kubernetes non local traffic in integration documentation

### ISSUE THREAD

**Issue by dominic-sigsci** [DataDog/documentation#5398]
- Updated step two of the setup process to call out Kubernetes non local traffic
- Added quotes to statsd-address="<datadog agent hostname:port>"

https://github.com/DataDog/integrations-extras/pull/477

**Comment by l0k0ms** [comment]
Hello, 

Many thanks for the heads up :) i just left a small review on your PR. 

Closing this issue and following it up on the PR directly.
Best,
Pierre
