### ISSUE TITLE
API Documentation for starting a synthetic test mentions incorrect http method

### ISSUE THREAD

**Issue by eleni-salamani** [DataDog/documentation#5473]
**Describe the bug**
According to the DataDog API Documentation, the way to start or pause a synthetic test is to issue a POST request. This however is incorrect, a PUT request is correct, as also included in the example for the curl command.
Additionally, the datadog postman collection has the request as POST, this should also be amended.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://docs.datadoghq.com/api/?lang=bash#start-or-pause-a-test
2. Check the description on the right
i.e. copied pasted here:
Signature
**POST** /v1/synthetics/tests/<SYNTHETICS_TEST_PUBLIC_ID>/status

Example Request
#!/bin/bash

api_key=<YOUR_API_KEY>
app_key=<YOUR_APP_KEY>
public_id=<SYNTHETICS_TEST_PUBLIC_ID>

curl -X **PUT** -H "Content-type: application/json" \
-d '{"new_status":"paused"}' \
"https://api.datadoghq.com/api/v1/synthetics/tests/${public_id}/status?api_key=${api_key}&application_key=${app_key}"

**Expected behaviour**
- Update the documentation  (section: Signature) to reference a PUT request
- Update the postman collection, to perform a PUT action for this request

**Screenshots**
![image](https://user-images.githubusercontent.com/54802933/65505660-ffa05080-dec9-11e9-8e6f-73ad9a295f64.png)

**Comment by l0k0ms** [comment]
Hello, 

Many thanks for this feedback :) Indeed you're right, I tested it on my side and the correct method is `PUT` and not `POST`.

I passed an update into this PR that impacts this part of the documentation: https://github.com/DataDog/documentation/pull/5458/commits/bdb94c5d13536c77fcb264b43e220b66cab94ddb

It should be merged soon :) If you spot other glitches within the documentation, feel free to open a new issue. 

Best regards,
Pierre
