### ISSUE TITLE
How do I capture custom Windows performance counters in Datadog?

### ISSUE THREAD

**Issue by conorbranagan** [DataDog/documentation#56]
This should have its own guide I think, stepping through adding your performance counters to a .NET application, get the WMI class of the performance counters and handling common issues (like [counters not being published to WMI](http://blogs.msdn.com/b/dougste/archive/2009/02/11/net-performance-counters-missing-when-using-wmi-to-access-them.aspx))

We still need to figure out the step from performance counter => WMI class.

**Comment by mhinze** [comment]
I found this, which is a good start: https://help.datadoghq.com/hc/en-us/articles/205016075-How-to-retrieve-WMI-metrics
