### ISSUE TITLE
Synthetics: check interval when status is ALERT

### ISSUE THREAD

**Issue by blaxter** [DataDog/documentation#5698]
**Is your feature request related to a problem? Please describe.**
I want to obtain an **accurate** SLO value based on several synthetics tests.

Right now to have this I'd need to set all synthetic tests frequency to 1min. This is because when a synthetic test fails, there is no retry until next scheduled time. Let's say you have an api tests with a frequency of 15 minutes, it fails, next time (15 minutes after failure) succeeds, from Synthetics point of view the service was down 15 minutes but that's not the real value (maybe it was down for 10 seconds... or maybe it was 15 minutes, you don't actually know)

**Describe the solution you'd like**
Be able to configure the frequency of the test depending current status, i.e. optional override of frequency for `alert` status.

**Describe alternatives you've considered**
Config option to say: retry tests x times in case of failure

**Additional context**
This is a common feature in health checkers (e.g. [haproxy's](https://www.haproxy.com/documentation/aloha/10-0/traffic-management/lb-layer7/health-checks/#check-interval), [aws elb's](https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/elb-healthchecks.html#health-check-configuration))

**Comment by apigirl** [comment]
Hey @blaxter - Since this is not a documentation related issue or request, I am going to close this issue, but please don't hesitate to reach out to us again or to our support team if you have any other suggestions or issues.
