### ISSUE TITLE
How do I share or embed graphs?

### ISSUE THREAD

**Issue by conorbranagan** [DataDog/documentation#57]
Needs a simple guide by itself.

**Comment by cricket007** [comment]
Got here from Google. The above link no longer seems to point to any information that is asked here.

**Comment by tobiaspal** [comment]
This seems to be the place for the generate embed code documentation now: https://docs.datadoghq.com/graphing/dashboards/shared_graph/

**Comment by pmadeya-bit** [comment]
Are embedded graphs still available after that Datadog dashboard/metrics are no longer available and can you specify a time range for embed graphs?
