### ISSUE TITLE
DataDog agent docker-compose volume bind error

### ISSUE THREAD

**Issue by DaniSchenk** [DataDog/documentation#5750]
## Documentation Page
https://docs.datadoghq.com/integrations/faq/compose-and-the-datadog-agent/
## Issue Description
The docs state that it's necessary to bind:
```
volumes:
     - /proc/mounts:/host/proc/mounts:ro
```
This threw errors in my case. After checking your [docker-compose example](https://github.com/DataDog/docker-compose-example) I found this volume bind, which solved my problem:
```
volumes:
     - /proc/:/host/proc/:ro
```

I don't know if this is general issue. If it is, maybe it's worth updating the docs. Users could start using docker-compose.yml without errors.

**Comment by apigirl** [comment]
@DaniSchenk - thanks for this feedback! we're looking into this

**Comment by l0k0ms** [comment]
Hello @DaniSchenk, 

We fixed the documentation. Many thanks again for this feedback. I'm going to close this issue, but if you have any questions or feedback feel free to add them here.

Best,
Pierre
