### ISSUE TITLE
Translate New Relic Beta Alerts section into Japanese

### ISSUE THREAD

**Issue by JohnLZeller** [DataDog/documentation#583]
There is a new section now on New Relic Beta Alerts that needs to be translated into Japanese.

The PR for the English section is here: https://github.com/DataDog/documentation/pull/582

And this part of the Japanese section has a commented out English version of what we need translated: https://github.com/DataDog/documentation/pull/582/files#diff-6aeb3747326f7b995ad8445ae6732af8R101

**Comment by irabinovitch** [comment]
@jhotta Were you able to take a look at this one?
