### ISSUE TITLE
Japanese document rendering broken

### ISSUE THREAD

**Issue by hitsumabushi** [DataDog/documentation#5981]
**Describe the bug**

In the introduction page about apm, some rendering are broken.
https://docs.datadoghq.com/ja/agent/docker/apm/

I found, even in markdown level, some code blocks are invalid.
https://github.com/DataDog/documentation/blob/master/content/ja/agent/docker/apm.md

**To Reproduce**
1. Go to https://docs.datadoghq.com/ja/agent/docker/apm/?tab=java#%E3%83%9B%E3%82%B9%E3%83%88%E3%81%8B%E3%82%89%E3%81%AE%E3%83%88%E3%83%AC%E3%83%BC%E3%82%B9
2. You can find some strange `<<` and `>>`. and invalid h1 elements like https://docs.datadoghq.com/ja/agent/docker/apm/?tab=java#datadog-agent.

**Expected behavior**

code blocks are rendered as the English version.

**Additional context**

(This is just format problem, not language specific problem. So, I think, even you are not familiar with Japanese, you can fix this. But, if you need help me, I will create a PR for this after several days.)

**Comment by l0k0ms** [comment]
Hello, 

Many thanks for this feedback, i think i see where it's coming from. I'm going to fix this.

**Comment by l0k0ms** [comment]
Hello again, 

The issue should now be fixed :) thanks again for the heads up !
