### ISSUE TITLE
Docs for new Azure Usage and Quotas integration?

### ISSUE THREAD

**Issue by flushentitypacket** [DataDog/documentation#6039]
The PR template led me here. I'm new at DD, so apologies in advance if this is the wrong place to put things!

I'm in the process of adding a new integration, Azure Usage and Quotas. According to [the new dogweb integration wiki](https://github.com/DataDog/devops/wiki/Adding-A-New-Dogweb-Integration), the docs team is supposed to be notified to get a new `README.md` and `manifest.json`, so I think that's why I'm here. [This doc](https://docs.google.com/document/d/192QBmkjfI__wdtls0MWuArx5uC4B9WG5jDBQFemM84Y/edit) might be a useful reference.

I'm also down to create a draft myself--I'm just not entirely sure what the protocol is.

**Comment by l0k0ms** [comment]
Hello, let's go DM to talk about this :) but many thanks for the ping 🙇
