### ISSUE TITLE
[URGENT] Missing metrics on Postgres integration

### ISSUE THREAD

**Issue by pedroletra-topdocs** [DataDog/documentation#611]
Hi,

We are using DataDog with the Postgres integration to monitor our database and we needed to access some stats like postgresql.seq_scans and postgresql.index_scans (and others) but they are not available in the metric list (none of the gauges are). what is happening?

Thank you for your time

**Comment by CharlyF** [comment]
Hey!

I have two suggestions as a first shoot for your issue. 
1) Have you set the dbname ?(see [here](https://github.com/DataDog/dd-agent/blob/master/conf.d/postgres.yaml.example#L8))
2) Is your PG version in the list of the ones we integrate with? see [here](https://github.com/DataDog/dd-agent/blob/master/.travis.yml#L66-L70).

Finally, would it be possible for you to reach out to support@datadoghq.com, it is easier for us to be alerted and answer as fast as possible.
Let me know if that works for you.

Regards,
Charly

**Comment by technovangelist** [comment]
Closing since this is a support issue and not an issue with the documentation
