### ISSUE TITLE
typo in java tags example

### ISSUE THREAD

**Issue by packeteer** [DataDog/documentation#6164]
**Describe the bug**
On this page https://docs.datadoghq.com/tracing/advanced/adding_metadata_to_spans/?tab=java#adding-tags-globally-to-all-spans
There is a typo when talking about the switch for global tags

The specific line is:
-dd.trace.global.tags='env:dev,<TAG_KEY>:<TAG_VALUE>' \

It should be:
**-Ddd**.trace.global.tags='env:dev,<TAG_KEY>:<TAG_VALUE>' \

**Comment by l0k0ms** [comment]
Hello,

Many thanks for this feedback, i've went ahead and opened a PR to fix this issue. I'm going to close this PR for now, but if you have any questions or feedback feel free to add them here.

Best,
Pierre
