### ISSUE TITLE
Hosts and tag example responses are inconsistent.

### ISSUE THREAD

**Issue by jerdd** [DataDog/documentation#6189]
Under [search hosts](https://docs.datadoghq.com/api/?lang=python#search-hosts), the example responses for curl, ruby and python do not match. e.g. the curl example response has `is_muted` as true and a `mute_timeout` field.

The [get tags](https://docs.datadoghq.com/api/?lang=python#get-tags) example response for python is incorrect. "tags" is a map of key to array. It should be replaced with:

```
{
    "tags": {
        "role:database": [
          "test.example.com.host"
        ],
        "env:test": [
            "test.metric.host"
        ]
    }
}
```

**Comment by shadiakiki1986** [comment]
Piggybacking off this issue, the docs for `search hosts` also doesn't document the format of the `filter` option. I figured out it should be `host:i-12345` from the docs for [search metrics](https://docs.datadoghq.com/api/?lang=python#search-metrics). Probably worth adding this to the docs.

**Comment by l0k0ms** [comment]
Hello,

Many thanks for this feedback, i've went ahead and open a PR to fix this issue. 

Feel free to add any comments there :) 

Best regards,
Pierre

**Comment by shadiakiki1986** [comment]
Thanks Pierre. Happy new year!
