### ISSUE TITLE
Add outlier/query alert to API documentation

### ISSUE THREAD

**Issue by ojongerius** [DataDog/documentation#622]
Hey folks,

The Outlier alert (in your UI,  'query alert' according to the API) has been around for a while, but has yet to be added to the API documentation at https://github.com/DataDog/documentation.

Cheers,

Otto

**Comment by technovangelist** [comment]
Thanks for creating the issue. I will update the docs to include an example for creating a monitor that is an Outlier Monitor. In a nutshell, use outlier detection method in the query for a monitor (http://docs.datadoghq.com/api/#monitors). So modifying the example for python, you might have something like this:

`from datadog import initialize, api

options = {
	'api_key': 'xxxx',
	'app_key': 'xxxx'
}

initialize(**options)

# Create a new monitor
options = {
	"notify_no_data": True,
	"no_data_timeframe": 20
}
tags = ["app:webserver", "frontend"]
api.Monitor.create(type="metric alert", query="avg(last_30m):outliers(avg:system.cpu.user{role:es-events-data} by {host}, 'dbscan', 7) > 0", name="matttest2-Bytes received on host0", message="We may need to add web hosts if this is consistently high.", tags=tags, options=options)`

**Comment by ojongerius** [comment]
:+1:
