### ISSUE TITLE
How does is_match support matching multiple tags when do notification/

### ISSUE THREAD

**Issue by wirybeaver** [DataDog/documentation#6292]
## Documentation Page
https://docs.datadoghq.com/monitors/notifications/?tab=is_matchis_exact_match#conditional-variables
## Issue Description
The documentation only gives an example how to use `is_match` to match one tag. 
```
{{#is_match "<TAG_VARIABLE>.name" "<COMPARISON_STRING>"}}
  This shows if <COMPARISON_STRING> is included in <TAG_VARIABLE>
{{/is_match}}
```

My question is that what correct grammar of `is_match` I can use to support matching multiple Tags?

For example, I want to be paged only when TAG1.name=XXX and TAG2.name=YYY. Can I write it down in the following way?

```
{{#is_match "TAG1.name" "XXX"}}
        {{#is_match "TAG2.name" "YYY"}}
              triggered_severity: 2
        {{/is_match}}
{{/is_match}}
```

**Comment by l0k0ms** [comment]
Hello, 

Indeed this should work :) Note that the indentation is not required but could help writing down the notification template. 

I'm going to close this issue for now, but if you have any question feel free to re-open it or directly reach support@datadoghq.com 

Best regards,
Pierre
