### ISSUE TITLE
Istio scraping and monotonic counts

### ISSUE THREAD

**Issue by jaygorrell** [DataDog/documentation#6376]
## Documentation Page
https://docs.datadoghq.com/integrations/istio/
https://www.datadoghq.com/blog/istio-datadog/

## Issue Description
Prometheus data uses monotonically increasing counts, which Datadog can handle, but the issue is when scraping through a service that will load-balance across individual pods. In this case, the telemetry pods behind `istio-telemetry.istio-system` will very likely have different counts. In order to properly scrape this data, Datadog instructions should call for annotating the pods themselves rather than using a cluster check to query the k8s service.

See https://github.com/istio/istio/issues/20102 for more context.

**Comment by l0k0ms** [comment]
Hello, 

Many thanks for the feedback and sorry for the latency on this. I have transmitted your feedback to the Datadog blog team. It's currently being fixed, the update should soon be published.

I'm going to close this PR for now as it's more blog than doc related.
If you have other feedback related to the Datadog documentation, feel free to open a new issue :) 

Best,
Pierre

**Comment by maxenglander** [comment]
@l0k0ms this is still an issue for me following the current documentation for Istio 1.4. I believe this issue should be re-opened.
