### ISSUE TITLE
CoreOS not listed in Agent Guides

### ISSUE THREAD

**Issue by mmell** [DataDog/documentation#638]
On [Getting Started with the Agent](http://docs.datadoghq.com/guides/basic_agent_usage/) it says "Run the info command (find this based on your OS in the left column above)." CoreOS is not listed in the column on the left even though it is listed in [installing the agent](https://app.datadoghq.com/account/settings#agent).

In particular, I need to know where the conf.d/*.yml files live in CoreOS.

**Comment by technovangelist** [comment]
thanks for submitting this. I will find a way to add some instructions, but the gist is to use the docker installation

**Comment by mmell** [comment]
I found the answer I needed here: https://github.com/DataDog/docker-dd-agent#enabling-integrations

**Comment by technovangelist** [comment]
docker / coreos instructions added, pointing to the docker integration doc
