### ISSUE TITLE
Invalid Permission UUID section hyperlinks

### ISSUE THREAD

**Issue by JordanSussman** [DataDog/documentation#6546]
## Documentation Page

https://docs.datadoghq.com/api/?lang=bash#permission-uuids

## Issue Description

All hyperlinks with the title of "Permission UUID section" lead nowhere.

**Comment by l0k0ms** [comment]
Hello,

Many thanks for this feedback! I've went ahead and opened a PR to fix this.
I'm going to close this issue, but if you have any questions feel free to re-open it :) 

Best,
Pierre
