### ISSUE TITLE
SLO query with tags returns 502

### ISSUE THREAD

**Issue by billyshambrook** [DataDog/documentation#6587]
**Describe the bug**

When I try to follow the example on how to query SLO's using tags, I get a 502 from the api - https://github.com/DataDog/documentation/blob/db0b71bc831509ee62717d2a71ef21eb73af0fbf/content/en/api/service_level_objectives/code_snippets/api-slo-search.py#L17

The error is:

```
Datadog returned a bad HTTP response code: 502 - Bad Gateway. Please try again later. If the problem persists, please contact support@datadoghq.com
```

**To Reproduce**
1. Run the code snippet linked to above, and it will fail on line 17

**Expected behavior**
Return list of SLO's, or empty list if none found

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by l0k0ms** [comment]
Hello, 

Many thanks for this feedback. The query only applies to the SLO name for now, not on all attributes available, sorry for the confusion.

I've went ahead and updated the comments to make it more consistence with the current parameter description. 

I'm going to close this issue, but feel free to re-open it if you spot other inconsistency like this one :) 

Best regards,
Pierre
