### ISSUE TITLE
SSL Windows Certificate store monitoring

### ISSUE THREAD

**Issue by guidovbrakel** [DataDog/documentation#6609]
I would like to have an integration that automatically reads the Windows Certificate store and monitors all the certificates and their expiry date. We already have an Powershell script for that, so it should be possible.

**Comment by l0k0ms** [comment]
Hello,

You should reach out to `support@datadoghq.com` for this, they will take care to forward and follow your feature request. :)

I'm going to close this issue as it's not related to the Datadog public documentation, but feel free to comment below if you have any questions.

Best regards, 
Pierre
