### ISSUE TITLE
Running .net data dog tracer with docker

### ISSUE THREAD

**Issue by chetanmangsuli84** [DataDog/documentation#6670]
## Documentation Page
Hello I needed your help in using data dog tracer while running a containerized .net web application.
## Issue Description
There is very little or no description about how to use .net datadog tracer in docker.

**Comment by l0k0ms** [comment]
Hello, 

Many thanks for this feedback, we are going to improve this documentation moving forward, it's now tracked internally. 

In the meantime, you can reach out to support@datadoghq.com to get help on this particular topic.  

Closing this Issue for now, but feel free to comment or open a new one if you have other feedback about our documentation.

Best,
Pierre
