### ISSUE TITLE
Missing redirection in French Agent log collection Documentation 

### ISSUE THREAD

**Issue by loitho** [DataDog/documentation#6706]
Hi there, 
The French documentation page has an issue with a missing redirection 
## Documentation Page
https://github.com/DataDog/documentation/blob/master/content/fr/agent/logs/_index.md
https://docs.datadoghq.com/fr/agent/logs/?tab=taildefichiersexistants#envoyer-des-logs-via-https

## Issue Description
The following line : 
> La valeur par défaut est 6. Consultez la [section sur le traitement de l’Agent Datadog][11

Doesn't properly redirect to this I assume : 

https://docs.datadoghq.com/fr/agent/basic_agent_usage/?tab=compressionhttpniveau6#charge-syst%C3%A8me-de-l-agent

Regards,

loitho

**Comment by l0k0ms** [comment]
Hello,

Indeed there is a bug, many thanks for flagging it. I'm going to take care of this :)

**Comment by l0k0ms** [comment]
PR:

* Adding link: https://github.com/DataDog/documentation/pull/6699/
* Fixing link: https://github.com/DataDog/documentation/pull/6705

**Comment by l0k0ms** [comment]
This is now fixed: https://docs.datadoghq.com/fr/agent/logs/?tab=taildefichiersexistants#envoyer-des-logs-via-https 

Closing this issue for now, but if you spot other glitches within the documentation feel free to open a new one :)

Best,
Pierre
