### ISSUE TITLE
Tracing .NET Automatic Instrumentation Linux

### ISSUE THREAD

**Issue by verdie-g** [DataDog/documentation#6783]
## Documentation Page
[Tracing .NET Framework Applications](https://docs.datadoghq.com/tracing/setup/dotnet-framework/)

## Issue Description
In this page it doesn't state which OS are supported for automatic instrumentation.

In Automatic Instrumentation / Installation it says
> To use automatic instrumentation on Windows, ...

But nothing about Linux.

In Manual Instrumentation though it clearly says
> Manual instrumentation is supported on .NET Framework 4.5 and above on Windows and on .NET Core 2.1, 3.0, and 3.1 on Windows and Linux.

Can we get the same for automatic instrumentation and an explanation if it is not supported on Linux? Thanks.

PS: The page name is misleading because .NET Framework often relates to .NET <= 4.X and not .NET Core.

**Comment by l0k0ms** [comment]
Hello, 

The page you are referencing is specifically for .NET Framework, which only runs on Windows.
[We have a separate page for .NET Core](https://docs.datadoghq.com/tracing/setup/dotnet-core), which is cross-platform and runs on Windows, Linux, and macOS (but we only support auto-instrumentation on Windows and Linux for now)

I'm going to close this issue, but feel free to add comments to it, or open a new issue if you spot another glitch with the documenation.

Best,
Pierre
