### ISSUE TITLE
Undocumented metric types TIMER and SET

### ISSUE THREAD

**Issue by verdie-g** [DataDog/documentation#6852]
## Documentation Page

[Datagram Format and Shell Usage](https://docs.datadoghq.com/developers/dogstatsd/datagram_shell/?tab=metrics)

## Issue Description

In the metrics table, it says
> c for COUNT, g for GAUGE, ms for TIMER, h for HISTOGRAM, s for SET. See the [metric type documentation](https://docs.datadoghq.com/developers/metrics/types).

But in the [metric type documentation](https://docs.datadoghq.com/developers/metrics/types), the list of types if the following:
- COUNT
- RATE
- GAUGE
- HISTOGRAM
- DISTRIBUTION

There is no TIMER or SET. However it mentions two new metrics: RATE and DISTRIBUTION.

**Comment by l0k0ms** [comment]
Hello, 

I have open a PR to fix those misses.

RATE is not mentioned as it's not supported: https://github.com/DataDog/datadog-go/blob/master/statsd/format.go#L8

a COUNT should be used instead in combination with [in-app modifiers](https://docs.datadoghq.com/developers/metrics/type_modifiers/?tab=count#in-application-modifiers)


SET and TIMER are related to StatsD directly and not to DogStatsD, their behavior is the same as within the StatsD protocol hence the lack of in-depth documentation in the Datadog documentation.

- SET is referenced here: https://docs.datadoghq.com/developers/metrics/types/?tab=histogram#submission-types-and-datadog-in-app-types 
- TIMER is mentioned here: https://docs.datadoghq.com/developers/metrics/types/?tab=histogram#submission as it's like an histogram from the DogStatsD perspective

I'm going to close this issue for now, if you have more question about metric types, feel free to reach out to support@datadoghq.com. 

Best,
Pierre
