### ISSUE TITLE
Explanation of trace ids/span ids format used by Datadog

### ISSUE THREAD

**Issue by rawicki** [DataDog/documentation#6906]
## Documentation Page

https://docs.datadoghq.com/getting_started/tracing/

## Issue Description

I've just spend some time fixing interoperability issues related to Datadog and some of our services using Kamon to report metrics.

In theory Kamon has a Datadog reporter module, in practice we had to replace Kamon's default implementation of trace id/span id identifiers which assumed the identifiers are serialized into 8 or 16 byte hexadecimal number with our implementation that uses decimal numbers as Datadog does.

While the bug itself wasn't in Datadog, it would _save me a lot of time_ if I could see a description of how exactly Open Tracing is implemented in Datadog, for example what format is used for trace ids.
For now the only confirmation I see is in this ticket: https://github.com/DataDog/documentation/issues/1271

I would like to suggest to add to the getting started page explanation of basic tracing concepts with exact definitions relating to Datadog (Open Tracing documentation is not useful here) and what is expected from the service implementation.

**Comment by rawicki** [comment]
Also, I think it would be useful to add this specific problem to Troubleshooting section:
https://docs.datadoghq.com/tracing/troubleshooting/

**Comment by l0k0ms** [comment]
Hello, 

Many thanks for the feedback we are going to look into it !

**Comment by nampas** [comment]
Hello, I would like to second this request. We have a client that needs to manually generate a traceId, and it would have saved me a lot of time if there was documentation on DD's expected trace id format.

Thanks.

**Comment by skeenan947** [comment]
I've just run into this issue as well - spitting out the trace/span id's as hex in the logger but numeric in the datadog apm integration causes us to be unable to correlate the data between logs and traces

**Comment by kayayarai** [comment]
Initial page published here https://docs.datadoghq.com/tracing/faq/span_and_trace_id_format/ Feedback and PRs to it are welcome!
