### ISSUE TITLE
Sample jmx config file has incorrect indentation

### ISSUE THREAD

**Issue by greenrd** [DataDog/documentation#693]
The sample jmx config at the top of http://docs.datadoghq.com/integrations/java/ has incorrect indentation which makes it invalid YAML.

**Comment by technovangelist** [comment]
I looked at the config at the top of the file and tried it with the datadog-agent configcheck as well as a number of online yaml linters and cannot find any errors. Was it the very first config that had a problem, or another one?

**Comment by technovangelist** [comment]
I'll go ahead and close this issue. If i got the wrong yaml file, let me know by reopening the issue.
