### ISSUE TITLE
Snake case conversion of JMX aliases not documented

### ISSUE THREAD

**Issue by greenrd** [DataDog/documentation#694]
Camel case JMX aliases in jmx.yaml config files are converted into snake case names automatically, but this is not mentioned anywhere on http://docs.datadoghq.com/integrations/java/

Unless this is an actual bug, in which case the bug should be fixed!

**Comment by technovangelist** [comment]
Thanks @greenrd for pointing that out. This is done to ensure continuity of metric names, for instance when no alias is specified...

`
include:
    attribute:
        HeapMemoryUsage.used:
            metric_type: gauge
    domain: java.lang
`

would report a metric on jmx.heap_memory_usage.used

I will update the docs to reflect this
