### ISSUE TITLE
No example of check configuration file

### ISSUE THREAD

**Issue by kreempuff** [DataDog/documentation#6942]
## Documentation Page
https://docs.datadoghq.com/agent/guide/agent-configuration-files/?tab=agentv6v7
https://docs.datadoghq.com/developers/write_agent_check/?tab=agentv6v7

## Issue Description
I was looking for an example check configuration file. The docs says to look in a folder on the host to find an example. The docs should show what fields are supported on a check configuration instead of requiring a user to install the agent just to get an example

**Comment by apigirl** [comment]
Hi @kreempuff,

Thanks so much for this feedback! We're going to look into this. In the meantime, if you're still having issues, feel free to [reach out to our awesome support team](https://docs.datadoghq.com/help/) - they can definitely help you get this figured out.

Kaylyn

**Comment by kreempuff** [comment]
@apigirl okay, thank you!
