### ISSUE TITLE
ECS integration docs has a mistake

### ISSUE THREAD

**Issue by MaikuMori** [DataDog/documentation#698]
In this code block

```bash
#!/bin/bash
cluster="cluster_name"
task_def="dd-agent-task"
echo ECS_CLUSTER=$cluster >> /etc/ecs/ecs.config
start ecs
yum install -y aws-cli jq
instance_arn=$(curl -s http://localhost:51678/v1/metadata \
  | jq -r '. | .ContainerInstanceArn' | awk -F/ '{print $NF}' )
az=$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone)
region=${az:0:${#az} - 1}
echo "
cluster=$cluster
az=$az
region=$region
aws ecs start-task --cluster $cluster --task-definition $task_def \
  --container-instances $instance_arn --region $region" >> /etc/rc.local
```

You're not defining `instance_arn` environment variable for `rc.local`.

**Comment by MaikuMori** [comment]
Looks like that isn't the issue. There is a race condition between the curl call and ecs-agent starting up in time. Adding `sleep 5` after `start ecs` fixed the issue for me.

**Comment by irabinovitch** [comment]
@MaikuMori Thanks for the feedback. We continue look for methods to improve the setup here. We hope to see AWS add something similar to kubernetes' DaemonSets at some point in the future so that this start script isn't required.
