### ISSUE TITLE
Tracing API

### ISSUE THREAD

**Issue by pauldraper** [DataDog/documentation#6995]
## Documentation Page

https://docs.datadoghq.com/api/?lang=bash#tracing

## Issue Description

1. Signature is `http://localhost:8126/v0.3/traces`, but examples are `http://localhost:8126/v0.4/traces`.

2. Is there any utility in grouping spans into traces? Instead of just sending `[[span1],[span2],[span3]]`?

3. There is no documentation about msgpack, which it appears the APM libraries use. This is significant, because several values are 64-bit integers, which can be difficult to serialize in some languages (name JS itself).

**Comment by sarina-dd** [comment]
Hi @pauldraper ,

Thanks so much for your feedback! We have recently updated our API page and it now includes the correct examples [here](https://docs.datadoghq.com/api/v1/tracing/).

There is no utility in grouping spans into traces. It's advised to follow the given example to avoid issues.

Documentation does not currently exist for msgpack and isn't currently in the works. However, we recommend using 63-bit over 64-bit to rectify this issue. We'd love to help you with your specific use case regarding this issue, feel free to [reach out to our awesome support team](https://docs.datadoghq.com/help/) - they can help you with any questions you have regarding msgpack.

Thanks,
Sarina

**Comment by pauldraper** [comment]
> However, we recommend using 63-bit over 64-bit to rectify this issue.

53-bit. By default, that's the JSON-serializable integer range of JavaScript.
