### ISSUE TITLE
Wrong parameters in "Setting permissions when ACLs are not present"

### ISSUE THREAD

**Issue by felix-voicehub** [DataDog/documentation#7028]
**Describe the bug**
The Docs describe 2 parameters which are typed wrong: `missing ok` should be `missingok` and `Compress` should be `compress` (see https://linux.die.net/man/8/logrotate). The issue can be found here: 

https://docs.datadoghq.com/logs/guide/setting-file-permissions-for-rotating-logs/#setting-permissions-when-acls-are-not-present

You can verify it by copying the provided code snippet in you logrotate.d and then call `sudo logrotate /etc/logrotate.d/dd-agent_ACLs`. You will get:

> error: /etc/logrotate.d/dd-agent_ACLs:13 unknown option 'missing' -- ignoring line
   error: /etc/logrotate.d/dd-agent_ACLs:15 unknown option 'Compress' -- ignoring line

**Comment by PierreVanRoy** [comment]
Hello @felix-voicehub ,

Thanks for your issue, I just created the PR to fix this.
https://github.com/DataDog/documentation/pull/7033

Pierre

**Comment by l0k0ms** [comment]
Hello,

PR is merged, i'm closing this issue. If you have other feedback feel free to comment this issue or open a new one :) 

Many thanks for the feedback <3 
Best regards,
Pierre
