### ISSUE TITLE
C# logs aren't parsed correctly using the configuration from the doc

### ISSUE THREAD

**Issue by verdie-g** [DataDog/documentation#7029]
## Documentation Page

[C# log collection (Serilog)](https://docs.datadoghq.com/logs/log_collection/csharp/?tab=serilog)

## Issue Description

Using the Serilog configuration from the documentation
```csharp
var log = new LoggerConfiguration()
    .WriteTo.File(new JsonFormatter(), "log.json")
    .CreateLogger();
```
logs aren't parsed correctly, especially status which is always info.
![Log Explorer](https://user-images.githubusercontent.com/9092290/77853203-2cb81d80-71e3-11ea-899e-a65500c82e26.png)

**Comment by PierreVanRoy** [comment]
Hello @verdie-g

It seems that the csharp processing pipeline on datadog side has not been installed properly when you sent your first logs. Hard to know what went wrong, I assume that the csharp.d/conf.yaml was not configured properly.
Please reach  the support team (sending an email to support@datadoghq.com), they will help with your integration. Then we will update the doc if needed.

Pierre

**Comment by CarlosPozosTR** [comment]
@verdie-g did you get a solution for this? what was the root cause?
