### ISSUE TITLE
Datadog-AWS RDS Integration docs has a mistake

### ISSUE THREAD

**Issue by apoman66** [DataDog/documentation#708]
Docs URL: http://docs.datadoghq.com/integrations/awsrds/

In the Enhanced RDS Integration section point 5:
Enter a policy name, such as lambda-datadog-policy. For Policy Document, enter the following, replacing <ROLE ARN> with the ARN of the role

It should be:
Enter a policy name, such as lambda-datadog-policy. For Policy Document, enter the following, replacing <ENCRYPTION_KEY ARN> with the ARN of the encryption key

Same for the following IAM policy, it should be:
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "kms:Decrypt"
            ],
            "Resource": [
                "ENCRYPTION_KEY ARN>"
            ]
        }
    ]
}

**Comment by irabinovitch** [comment]
@tmichelet  Does this look correct? I ask because the encryption keys aren't created until step 6, but we create the policy in step 5.  So if we're scoping to a given key here, rather than role we likely need to update the ordering as well?

**Comment by tmichelet** [comment]
@irabinovitch that's correct, see https://github.com/DataDog/dd-aws-lambda-functions/blob/master/rds_enhanced_monitoring/main.py#L19 for another explanation
