### ISSUE TITLE
Hidden Section in Graphing Primer is difficult for customers to find

### ISSUE THREAD

**Issue by Ricky-Thomas** [DataDog/documentation#714]
There's a large section of our docs that is missed frequently by our customers. This is in the graphing primer here: http://docs.datadoghq.com/graphing/

This link is the one that is missed: http://cl.ly/1Y1O3y161x0q

Here's some feedback from Cory at Stripe (one of our bigger customers): 

> It'd be great if Y-Axis controls (outliers, min, max and scale) were in the UI. But that's probably a lot of work. In the short term it would be nice if the Yaxis stuff was documented in a single place. Preferably somewhere other than the kinda hidden, but very useful help articles (https://help.datadoghq.com/hc/en-us/sections/200763645-Graphing) .

> Specifically I feel it would be helpful to get them on the graphing primer (http://docs.datadoghq.com/graphing/) in a Y-axis section.

That exists, he just hasn't found it. I pointed it out.
He added a few more requests:

> While I'm here:

> * It would be great to add on-hover heading anchor links (like github) to the sections in the primer so I could more easily link people to specific sections without inspecting and copying the headings ID. :)

This would definitely be a nice addition.
 
> * The functions should not be hidden by default, as you can't cmd-F and find them on the page for an explanation. Plus the "click here" thing is hidden af and I can never find it. 

This is referring again to that link I screenshotted.

> * Showing how to do math here would be great. (advanced, add metric, etc)

I pointed out that this is also found in this hidden section.

Any chance we can open that up to not be behind the link? Even a separate doc for JSON entirely might be nice. Thanks so much!

**Comment by irabinovitch** [comment]
👍  I've added this to the current sprint.

**Comment by technovangelist** [comment]
this page has a long history. early on it was all in one page and there were many requests to simplify, even chop and delete half of it. I went with the hide what most (according to the most vocal) don't ever need. the previous version was linkable to any section, even the stuff that was hidden by default. The latest version moves the json half to a new page with a partial used for the functions that is reused on both the main gui page and the json page.

https://github.com/DataDog/documentation/pull/717
