### ISSUE TITLE
Links on Agent Kubernetes not generated

### ISSUE THREAD

**Issue by jspiewak** [DataDog/documentation#7312]
**Describe the bug**
The links for the text "DogStatsD over Unix Domain Sockets" and Tagging "Kubnernetes" are not links.

**To Reproduce**
1. Go to https://docs.datadoghq.com/agent/kubernetes/?tab=helm
2. Scroll down to 'Tagging'
4. Observe "[DogStatsD over Unix Domain Sockets][14]" and "[Kubernetes][16]" are not clickable.

**Expected behavior**
I expect to be able to navigate to DogStatsD over UDS.

**Screenshots**

![image](https://user-images.githubusercontent.com/399516/80728395-e18c7580-8ad4-11ea-9e67-f14aa957630b.png)

**Comment by l0k0ms** [comment]
Hello, many thanks for this feedback 🙇  

I've went ahead and open a PR to fix this, if you spot other glitches within the doc feel free to open another issue :) 

Best regards,
Pierre
