### ISSUE TITLE
dd.trace_id and dd.span_id doesn't seem to work in Serilog

### ISSUE THREAD

**Issue by rpatrick00** [DataDog/documentation#7367]
## Documentation Page
documentation/content/en/tracing/connect_logs_and_traces/dotnet.md
## Issue Description
In the Manual Tracing example code for Serilog, the documentation shows:

```csharp
using Datadog.Trace;
using Serilog.Context;

// there must be spans started and active before this block.
using (LogContext.PushProperty("dd.trace_id", CorrelationIdentifier.TraceId.ToString()))
using (LogContext.PushProperty("dd.span_id", CorrelationIdentifier.SpanId.ToString()))
{
    // Log something
}
```
As far as I can tell, these LogContext property names do not work because they have a . (dot) in them.  When I try to reference these properties in my Serilog outputTemplate, I get nothing.  If I convert the dots into underscores, it works as expected.

**Comment by macrogreg** [comment]
Internal tracker:
https://datadoghq.atlassian.net/browse/DOTNET-99
