### ISSUE TITLE
Unix Domain Socket Windows Support

### ISSUE THREAD

**Issue by verdie-g** [DataDog/documentation#7694]
## Documentation Page
[DogStatsD over Unix Domain Socket](https://docs.datadoghq.com/developers/dogstatsd/unix_socket/)

## Issue Description
It is not clear wether or not Unix Domain Socket are supported by the Datadog agent on Windows. When setting _dogstatsd_socket_ I get the following log: `(pkg/dogstatsd/server.go:128 in NewServer) | can't listen: listen unixgram XXX\dd.sock: socket: An address incompatible with the requested protocol was used.`. The Datadog agent [uses the standard go library to open the socket](https://github.com/DataDog/datadog-agent/blob/c9588a61e1fef100c61deb39a5145f3b471d107a/pkg/dogstatsd/listeners/uds_common.go#L80) but is seems like it is [not supported on Windows](https://golang.org/src/net/unixsock.go?s=346:478#L8).

**Comment by apigirl** [comment]
@sarina-dd found where we state that it is not in fact supported by windows - seems this is a limitation of go and not a decision on our side - https://github.com/DataDog/datadog-agent/blob/c9588a61e1fef100c61deb39a5145f3b471d107a/pkg/dogstatsd/listeners/uds_common_test.go#L7
