### ISSUE TITLE
Datadog FAQ has a mistake - how to share a graph in timeboard

### ISSUE THREAD

**Issue by toolyee** [DataDog/documentation#772]
doc URL:
on English
http://docs.datadoghq.com/faq/#metrics
on Japanese
http://docs.datadoghq.com/ja/overview/#dashboards

on English doc,
The ability to embed any chart anywhere. Pick a graph on a dashboard, click on the cog to edit it and you’ll find the “share” tab that will generate an IFRAME.
[click on the cog] should be [click on the pencil]

on Japanese doc,
グラフは、iframeに挿入することができます。この機能を使い、基礎データや他の情報を隠蔽したまま、第３者にグラフを公開することができます。(グラフ右上の歯車マークから)
[グラフ右上の歯車マークから] should be [グラフ右上の鉛筆マークから]

Thanks

**Comment by irabinovitch** [comment]
@toolyee Thanks for the feedback. We'll take a look and adjust.

@jhotta can you help confirm the Japanese text?

**Comment by jhotta** [comment]
@irabinovitch sure working on it.

**Comment by irabinovitch** [comment]
Thanks @jhotta for addressing both english and japanese in #773
