### ISSUE TITLE
Log restriction query, example parameter type is incorrect

### ISSUE THREAD

**Issue by loitho** [DataDog/documentation#7747]
**Describe the bug**
Hi, 

The example for the body to send in order to create a log restriction query has a little error 

 **To Reproduce**
Here : https://docs.datadoghq.com/api/v2/logs-restriction-queries/#create-a-restriction-query
In the example, for the type param it's written : 
`"type": "string"`
This is incorrect and yield a 400 error code.
The example should have been : 
`"type": "logs_restriction_queries"`

This happens a second time here : 
https://docs.datadoghq.com/api/v2/logs-restriction-queries/#update-a-restriction-query

Both errors are in this file
https://github.com/DataDog/documentation/blob/master/content/en/api/v2/logs-restriction-queries/examples.json

Have a good day !

Kind regards, 

Thomas

**Comment by sarina-dd** [comment]
Hi Thomas,

Thanks for letting us know! I went ahead and updated the type parameter, this issue is resolved now. Closing this issue, but if you run into any additional questions feel free to contact our support@datadoghq.com team and they'll be able help you out!

Best,
Sarina
