### ISSUE TITLE
SNS logging language is confusing 

### ISSUE THREAD

**Issue by rromanchuk** [DataDog/documentation#7801]
## Documentation Page
https://docs.datadoghq.com/integrations/amazon_sns/#log-collection

## Issue Description

> Log collection
> There is no SNS Logs. Process logs and events that are transiting through to the SNS Service.

and then right below that 

> SEND LOGS TO DATADOG
> Configure a new SNS subscription, Select the topic where messages come from, Select “Lambda” as protocol and the arn of the lambda you want to use:

I think i understand what you're getting at, but "select the arn of lambda" is confusing. Do you mean i need to create my own function that outputs logs to cloudwatch which is then picked up by the datadog log forwarder, or am i supposed to to invoke the log forwarder directly?

**Comment by apigirl** [comment]
Hi there! thanks for this feedback - we've updated the language to make it clearer.
