### ISSUE TITLE
Non-ASCII quotation marks in example in Monitors Template Variable Evaluation page 

### ISSUE THREAD

**Issue by lgh2** [DataDog/documentation#7871]
## Documentation Page: 
https://github.com/DataDog/documentation/blob/master/content/en/monitors/guide/template-variable-evaluation.md#operators

## Issue Description

A customer reached out saying that the examples on this page do not use ASCII quotation marks. I did some researc, but I can't seem to find a way to replace them with ASCII quotation marks, or determine what type of quotation marks we are currently using. Is there a way we can replace the quotes with ASCII ones? 

The customer says that if the quotes are not ASCII, it may break some pipelines in ways that are difficult to troubleshoot. 

Thank you, and please let me know if you have any questions.

**Comment by apigirl** [comment]
Hi @lgh2 - I am taking this to an internal discussion and closing this issue.
