### ISSUE TITLE
k8s: Agent manifests not using the secret created earlier in the installation guide 

### ISSUE THREAD

**Issue by jlevesy** [DataDog/documentation#7884]
**Describe the bug**

All  the provided installation manifests in the [kubernetes installation guide](https://docs.datadoghq.com/agent/kubernetes/?tab=daemonset) redefine a secret `datadog-agent` for the API key instead of using the `datadog-secret` previously created as instructed by the guide. 

**To Reproduce**
1. Go to https://docs.datadoghq.com/agent/kubernetes/?tab=daemonset
2. Follow the Guide until the section "deploy the daemon set"
3. See that the manifest cannot be applied because the value of secret `datadog-agent` is not base64 encoded.

**Expected behavior**

Either:
- Don't create the secret using `kubectl create secret` in the guide and instruct the user to edit the downloaded manifest to set the right secret value
- Or remove the `datadog-agent` secret declaration in all the manifests and have them reference `datadog-secret` instead

**Desktop (please complete the following information):**

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"archive", BuildDate:"2020-06-20T07:41:29Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"6c143d35bb11d74970e7bc0b6c45b6bfdffc0bd4", GitTreeState:"clean", BuildDate:"2019-12-11T12:34:17Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by apigirl** [comment]
thanks for this feedback! we will take a look and likely make an update.

**Comment by urseberry** [comment]
This has beeb fixed.
