### ISSUE TITLE
Assigning tags via Infrastructure list in Datadog

### ISSUE THREAD

**Issue by saisirisha1835** [DataDog/documentation#7987]
## Issue Description
Hi,

I have recently tried to update tags via Infrastructure list and added tag in user tags in the following format

Product:CompanyName,Tier:App,EnvType:Non-Prod

After I have assigned tags ,I tried to check the traces in trace dashboard with Tier:App etc filters.I didn't find any logs as well as user tags in infrastructure list are not updated.

Please advise me on how to update tags so that I can see the logs by filtering a specific tag.

Thanks

**Comment by apigirl** [comment]
Hi @saisirisha1835,

Feel free to reach out to our [awesome support team](https://docs.datadoghq.com/help/) - they can definitely help you get this specific issue figured out. Since this isn't docs specific feedback, I am going to close this issue.

Kaylyn
