### ISSUE TITLE
How to slice metrics on different dimensions

### ISSUE THREAD

**Issue by clofresh** [DataDog/documentation#8]
* Set up tagging
* Graph editor

**Comment by technovangelist** [comment]
hi @clofresh 

is this still something that needs documenting? Do you have an example?

**Comment by clofresh** [comment]
Yeah, we still don't have a good guide on tagging, why to do it and what it gives you that other products don't. For example, with metric alerts, if you're submitting some response time metric, `myapp.response_time`, you can tag it by app like `app:app1`, `app:app2` etc, and then set up a multi alert on it so that every new app you add gets monitored with you haven't to update the monitor. It's a common use case we describe in demos but don't have any associated docs on.

**Comment by technovangelist** [comment]
Excellent, thanks. I will come up with something

**Comment by technovangelist** [comment]
Hey I am going to ask about this again. I have a doc on tagging now (http://docs.datadoghq.com/guides/tagging/) but its purely about how to use tagging in different areas. Its more of a reference to what the different tagging options are. I don't think it addresses this scenario. Perhaps you can show me what you mean and I can come up with more of a guide to useful scenarios.

**Comment by technovangelist** [comment]
with the doc on tagging and the update to the guide to graphing, i think this is addressed
