### ISSUE TITLE
Docs should specify which regex, date, and grok parsers are being used

### ISSUE THREAD

**Issue by case** [DataDog/documentation#8010]
**Is your feature request related to a problem? Please describe.**

I'm working on getting [glog](https://github.com/google/glog)-formatted logs parsed via your logs processing functionality, and it isn't clear which specific regex library you are using. Same for date formatting, and grok parsing. A bit more about glog is [here](https://medium.com/technical-tips/google-log-glog-output-format-7eb31b3f0ce5).

For example, in the [Parsing dates section](https://docs.datadoghq.com/logs/processing/parsing/?tab=matcher#parsing-dates), I need "microseconds" but it isn't clear what `SSS` represents?

And for regex, it would be helpful to know which specific library or language you are using. Currently, it's too ambiguous.

**Describe the solution you'd like**
    
Please document which libraries (or languages, etc) you are using for regex and date parsing. 

E.g. is it [this grok lib](thekrakken/grok), or something else?

**Describe alternatives you've considered**

Honeycomb, for example, documents their parsing:

- https://docs.honeycomb.io/getting-data-in/integrations/kubernetes/configuration/
- https://github.com/honeycombio/honeycomb-kubernetes-agent/blob/master/parsers/glog.go

**Comment by apigirl** [comment]
Hi @case,

We're going to look into getting the docs updated here, but in the meantime, feel free to reach out to our [awesome support team](https://docs.datadoghq.com/help/) - they can definitely help you get to the bottom of figuring out your implementation.

Kaylyn

**Comment by case** [comment]
Thanks @apigirl! I've already been in touch with them, and they have been very helpful. But the need remains for more precision in these docs; this is the biggest pain point our engineering team has identified as we've gotten started working with Datadog's service.

**Comment by apigirl** [comment]
Hi @case - I've just confirmed that we're not allowed to expose this information in the docs because of a potential security issue. So syncing with support is the best option! Thanks for giving us this feedback!!

**Comment by case** [comment]
That's unfortunate.
