### ISSUE TITLE
No documentation for Ansible events

### ISSUE THREAD

**Issue by verdie-g** [DataDog/documentation#8018]
## Documentation Page

[Ansible integration](https://docs.datadoghq.com/integrations/ansible/).

## Issue Description

The documentation states
> The Ansible integration does not include any events.

and also
> You should start seeing Ansible **events** and metrics appear on Datadog when your playbook is run.

which is contradictory.

**Comment by apigirl** [comment]
Hey @verdie-g - thanks for pointing this out! We'll get this updated
