### ISSUE TITLE
Rename organization to Datadog?

### ISSUE THREAD

**Issue by RohanTalip** [DataDog/documentation#8028]
Hi,

(There doesn't really seem like a good place to file this; this repository seemed like the best choice.)

Should the "DataDog" GitHub organization be renamed to "Datadog" (note the lowercase second "d") to be consistent with the branding of the Datadog company, or even all lowercase like https://github.com/google and https://github.com/microsoft

It looks like Datadog was using that form ("Datadog", only first letter capitalized) as early as 2010: https://web.archive.org/web/20100809050504/http://www.datadoghq.com/

It seems like GitHub doesn't care about case in URLs, e.g. https://github.com/Datadog and https://github.com/datadog are the same organization as https://github.com/DataDog, so I don't think you would have to worry about links breaking.

**Comment by apigirl** [comment]
Hi @RohanTalip - thanks for pointing this out!  It's a fair point, but we have internal processes that depend on the DataDog org and it would be too big of an effort to update it at this point.
