### ISSUE TITLE
Want to get a demo of the product

### ISSUE THREAD

**Issue by yamankalra** [DataDog/documentation#8033]
We're looking at your Real-time threat detection tool and would like to know more about it
**Issue faced by us:**
We have an active system where financial transactions happen and there is a fix limit assigned to each user for the transactions.
Recently we've seen multiple events where user has fired a CURL command and increase their limits at the run-time while making the transaction request.
We would like to get a demo or info on how we can use your product and setup some pattern recognition rules to stop such behaviour

**Comment by apigirl** [comment]
Hi @yamankalra,

Feel free to reach out to our [awesome support team](https://docs.datadoghq.com/help/) - they can definitely help you get this specific issue figured out. Since this isn't docs specific feedback, I am going to close this issue.

Kaylyn
