### ISSUE TITLE
Host map, group by Agent Version

### ISSUE THREAD

**Issue by CraigWoolgar** [DataDog/documentation#8077]
**Is your feature request related to a problem? Please describe.**
As a team that manages 250+ hosts and ~150 with agents it is always frustrating to find that an agent has not been updated for a while and is running an old version with bugs and/or missing features. Some autoupdate on deployments, some are legacy applications that get infrequent updates.

**Describe the solution you'd like**
In the `Group Hosts by Tags` section on a Host Map it would be highly beneficial to have an option to group by installed agent version. This would allow us to quickly and easily see what agents need updating and go about performing the updates. This could involve the agent adding its own tag with the datadog agent version and sending it to the server.

**Describe alternatives you've considered**
An additional Watchdog alert for agents that are out of date. This would need recurring checks and a knowledge of what is deemed "out of date", although this could be left to user configuration.

**Additional context**
Something similar to the attached is what I have in mind if it's added to the Hosts Map.
![2020-07-23 09_45_53-Host Map _ Datadog](https://user-images.githubusercontent.com/11512117/88232069-57197380-ccc9-11ea-8c10-1872f91c17d8.png)

**Comment by CraigWoolgar** [comment]
Missed this was for documentation. My bad.

**Comment by apigirl** [comment]
Hey Craig, if you file a ticket with our [support team](https://docs.datadoghq.com/help/) they do track feature requests.

**Comment by CraigWoolgar** [comment]
Thanks @apigirl. An email was sent to the support team on Thursday, and I believe a feature request has been raised from that.
