### ISSUE TITLE
Datadog is not authorized to perform action sts:AssumeRole Account affected: *** Regions affected: every region

### ISSUE THREAD

**Issue by MatteoGioioso** [DataDog/documentation#8265]
**Describe the bug**
We are trying to integrate datadog with our AWS account, but so far has not worked

**To Reproduce**
1. Install the AWS integration
2. Automatically configure via Cloudformation in our working region (**Maybe you should specify that you should switch region since the default one is Virginia**)
3. Provide a generated API key from: https://app.datadoghq.com/account/settings#api to the Cloudformation parameters
4. After the DataDog stack has been successfully deployed, supply our accountId (**No dashes**) and the name of the automatically created role `DatadogIntegrationRole`
5. Press "Update Configuration**
6. Success message is displayed
7. After couple of minutes of testing no metrics were showing
8. I went back to the AWS integration pop-up this and error was displayed:
```
Datadog is not authorized to perform action sts:AssumeRole Account affected: *** Regions affected: every region
```

I went to check the trust policy but everything looks normal:

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::464622532012:root"
      },
      "Action": "sts:AssumeRole",
      "Condition": {
        "StringEquals": {
          "sts:ExternalId": "*****"
        }
      }
    }
  ]
}

```

**Expected behavior**
Should work

**Comment by MatteoGioioso** [comment]
Ok, I have reinstalled everything and it worked this time

**Comment by apigirl** [comment]
Hi @MatteoGioioso,

If you run into any more issues, you can reach out to our [awesome support team](https://docs.datadoghq.com/help/).

Kaylyn
