### ISSUE TITLE
Bulk export metrics

### ISSUE THREAD

**Issue by nlandolfi** [DataDog/documentation#8284]
## Documentation Page

https://docs.datadoghq.com/api/v1/metrics/#query-timeseries-points

## Issue Description

Is this the best way to bulk export metrics? It seems to have strict quotas and not like requesting metrics for more than an hour.

**Comment by apigirl** [comment]
Hi @nlandolfi,

Feel free to reach out to our [awesome support team](https://docs.datadoghq.com/help/) - they can definitely help you get this specific issue figured out. Since this isn't docs specific feedback, I am going to close this issue.

Kaylyn
