### ISSUE TITLE
Need help fixing alert issue

### ISSUE THREAD

**Issue by maidelba** [DataDog/documentation#8307]
We have 4 boxes that are going offline at certain times and I want to exclude them from the alerting.  I need some guidance because when I try to use the downtime exclude, it takes all the boxes off the exclude not just certain ones.  I need help with best practices around how to do this.  Thanks!

**Comment by apigirl** [comment]
Hi @maidelba, 

Feel free to reach out to our [awesome support team](https://docs.datadoghq.com/help/) - they can definitely help you get this specific issue figured out. Since this isn't docs specific feedback, I am going to close this issue.

Kaylyn
