### ISSUE TITLE
invalid `datadog_collection.json` for postman

### ISSUE THREAD

**Issue by kennedy** [DataDog/documentation#8441]
**Describe the bug**
The `datadog_collection.json` file in https://docs.datadoghq.com/getting_started/api/#import-the-datadog-collection is invalid. Unable to import. It seems to be encoded.

**To Reproduce**

1. Download https://docs.datadoghq.com/resources/json/datadog_collection.json
2. Open Postman
3. Click on Import
4. Select the datadog_collection.json file downloaded in step 1.

**Expected behavior**
Have a Datadog collection with many different API examples.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/854543/91998350-1ae62380-ed09-11ea-8554-f4ffaba9d254.PNG)

**Desktop (please complete the following information):**
 - OS: Win10

**Comment by apigirl** [comment]
hi @kennedy! thanks for the feedback. we're currently in the process of broadly updating our postman spec generally, so we'll make sure this gets addressed.
