### ISSUE TITLE
[lighttpd] documentation update

### ISSUE THREAD

**Issue by AbrilLoyaEnriquez** [DataDog/documentation#848]
Differentiate between Lighttpd1 (stable branch) and Lighttpd2 metrics available for collection by the Agent in our [documentation](http://docs.datadoghq.com/integrations/lighttpd/): 

Monitored metrics Lighttpd1

- lighttpd.net.bytes
- lighttpd.net.bytes_per_s
- lighttpd.net.hits
- lighttpd.net.request_per_s
- lighttpd.performance.busy_servers
- lighttpd.performance.idle_server
- lighttpd.performance.uptime

Monitored metrics Lighttpd2

- lighttpd.connections.state_handle_request
- lighttpd.connections.state_keep_alive
- lighttpd.connections.state_read_header
- lighttpd.connections.state_start
- lighttpd.connections.state_write_response
- lighttpd.net.bytes_in
- lighttpd.net.bytes_in_avg
- lighttpd.net.bytes_in_avg_5sec
- lighttpd.net.bytes_out
- lighttpd.net.bytes_out_avg
- lighttpd.net.bytes_out_avg_5sec
- lighttpd.net.connections_avg
- lighttpd.net.connections_avg_5sec
- lighttpd.net.connections_total
- lighttpd.net.requests_avg
- lighttpd.net.requests_avg_5sec
- lighttpd.net.requests_total
- lighttpd.performance.memory_usage
- lighttpd.performance.uptime
- lighttpd.response.status_1xx
- lighttpd.response.status_2xx
- lighttpd.response.status_3xx
- lighttpd.response.status_4xx
- lighttpd.response.status_5xx

**Comment by irabinovitch** [comment]
Thanks @AbrilLoyaEnriquez. We've addressed in  #857.
