### ISSUE TITLE
agent/guide/network has undocumented endpoints

### ISSUE THREAD

**Issue by williams-brian** [DataDog/documentation#8483]
## Documentation Page

https://docs.datadoghq.com/agent/guide/network/

## Issue Description

I found the agent using several endpoints that are not documented in the network documentation:
- `agent-http-intake.logs.datadoghq.com:443` will be used for log collection, unless `logs_config.use_tcp` is set, or the agent cannot connect via HTTP. [1](https://github.com/DataDog/datadog-agent/blob/9e2ad3b72da3e98d5b91484f70bbaab1060a720f/pkg/logs/config/config.go#L198) [2](https://github.com/DataDog/datadog-agent/blob/9e2ad3b72da3e98d5b91484f70bbaab1060a720f/pkg/logs/config/config.go#L111)
- `agent-443-intake.logs.datadoghq.com:443` will be used for log collection if `logs_config.use_port_443` is set to true.  [1](https://github.com/DataDog/datadog-agent/blob/9e2ad3b72da3e98d5b91484f70bbaab1060a720f/pkg/logs/config/config.go#L154) [2](https://github.com/DataDog/datadog-agent/blob/9e2ad3b72da3e98d5b91484f70bbaab1060a720f/pkg/config/config.go#L560)
- The DataDog agent seems to use `app.datadoghq.com` to verify the API key even on versions > `7.18.0` (see below)

```
$ datadog-agent version
Agent 7.21.1 - Commit: 83bdc57 - Serialization version: 4.36.0 - Go version: go1.13.11
$ sudo datadog-agent status | grep -C 3 -i 'api key'
    Success: 72,562
    TimeseriesV1: 34,417

  API Keys status
  ===============
    API key ending with [redacted]: API Key valid

==========
Endpoints
==========
  https://app.datadoghq.com - API Key ending with:
      - [redacted]
```

**Comment by apigirl** [comment]
Hi @williams-brian,

Thanks for letting us know about this! We have the logs intake endpoints documented here - https://docs.datadoghq.com/logs/log_collection/?tab=http#datadog-logs-endpoints.

That is indeed odd that it validates against the app. I've let the team know!

Kaylyn
