### ISSUE TITLE
APM go and nodejs: `DD_AGENT_HOST` vs. `DD_TRACE_AGENT_HOSTNAME`

### ISSUE THREAD

**Issue by mickeyreiss** [DataDog/documentation#8551]
## Documentation Page

https://docs.datadoghq.com/tracing/setup/go and https://docs.datadoghq.com/tracing/setup/nodejs/.

## Issue Description

Through trial and error, I realized that the go and nodejs SDKs use subtly different environment vars for specifying the APM agent host: `DD_AGENT_HOST` vs. `DD_TRACE_AGENT_HOSTNAME`. 

If this is true, I think might warrant a callout in the docs. In my multi-language kubernetes environment, I failed to read the instructions carefully enough. This led to an unnecessary debugging session trying to figure out why an identical kubernetes env config worked for one service but did not for another.

Thanks!

**Comment by apigirl** [comment]
Hi @mickeyreiss,

Sorry you had such a tough time with this! We're currently working on a central list of clear (and unified) env vars and we will make sure this specific use case is covered!

Kaylyn

**Comment by lattwood** [comment]
@apigirl any progress on this? I'm working on building a rubrick of env vars.

Golang: https://docs.datadoghq.com/tracing/setup_overview/setup/go?tab=containers

no table for env vars

But many of the other languages do

**Comment by pinko-fowle** [comment]
@apigirl any update on documenting the env vars?
