### ISSUE TITLE
Uploading sourcemaps

### ISSUE THREAD

**Issue by knoppixjs** [DataDog/documentation#8677]
I've a issue when uploading sourcemaps. 
Console output reposne below, but i have sourcemaps in path:  "static\js"   

**Response:**
Starting upload with concurrency 20.
Will look for sourcemaps in static\js
Will match JS files for errors on files starting with https://"my domain here"/static/js
version: 1.0.0 service: "my service name here" project path:
:white_check_mark: Uploaded 0 files in 0.001 seconds.

**Comment by apigirl** [comment]
Hi @skang0601,

Feel free to reach out to our [awesome support team](https://docs.datadoghq.com/help/) - they can definitely help you get this sorted out. Since this isn't docs specific feedback, I am going to close this issue.

Kaylyn
