### ISSUE TITLE
Numerous Golang API examples are invalid

### ISSUE THREAD

**Issue by JordanSussman** [DataDog/documentation#8720]
**Describe the bug**

The majority of Golang examples I have looked at in the API documentation are not valid against the changes that https://github.com/DataDog/datadog-api-client-go has implemented. 

**To Reproduce**
1. Go to https://docs.datadoghq.com/api/v1/logs/
2. Click on `Go` button within the first code example
3. Copy and paste the code into a local `main.go` file
4. Run the program with `go run main.go` and see the following errors

```
$ go run main.go
# command-line-arguments
./main.go:24:34: cannot use "Index_example" (type string) as type *string in field value
./main.go:24:58: cannot use 123 (type int) as type *int32 in field value
./main.go:24:116: invalid composite literal type datadog.LogsSort
./main.go:24:120: cannot use "StartAt_example" (type string) as type *string in field value
./main.go:24:154: undefined: datadog.LogsListRequest_time
```

**Expected behavior**

Examples work without major modifications

**Desktop (please complete the following information):**
 - OS: MacOS
 - Golang Version: 1.15

**Additional context**

I've also noticed the docs within https://github.com/DataDog/datadog-api-client-go/blob/master/api/v2/datadog/docs/LogsApi.md#listlogs are invalid

**Comment by apigirl** [comment]
hi @JordanSussman - thanks for the feedback! we're looking into it.

**Comment by apigirl** [comment]
hello - this PR should fix the issue you identified here - https://github.com/DataDog/documentation/pull/9058 - thanks so much for letting us know!

**Comment by JordanSussman** [comment]
Hi @apigirl,

Can you clarify if these changes have already been applied to the live documentation site? If so, I disagree that the changes have fully fixed the issues. Steps to reproduce the latest error I saw:

1. Go to https://docs.datadoghq.com/api/v1/logs/
1. Click on the `Go button` within the https://docs.datadoghq.com/api/v1/logs/#get-a-list-of-logs example
1. Copy and paste the code into a local `main.go` file
1. Run the program with `go run main.go` and see the following error

```sh
$ go run main.go
# command-line-arguments
./main.go:24:59: undefined: datadog.NewLogsListRequest_time
```

That specific error appears to be fixable with updating `datadog.NewLogsListRequest_time` to be `datadog.NewLogsListRequestTime`.
