### ISSUE TITLE
Golang code example ill-formatted

### ISSUE THREAD

**Issue by leonardbinet** [DataDog/documentation#8768]
## Documentation Page
https://docs.datadoghq.com/fr/developers/metrics/dogstatsd_metrics_submission/?tab=go

https://github.com/DataDog/documentation/blob/master/content/fr/developers/metrics/dogstatsd_metrics_submission.md

## Issue Description
Golang example is not well formatted:

<img width="665" alt="Capture d’écran 2020-10-09 à 14 53 32" src="https://user-images.githubusercontent.com/1590371/95585603-b6249400-0a3f-11eb-9ad9-5048ca80664a.png">

On google chrome Version 85.0.4183.121

**Comment by apigirl** [comment]
hello @leonardbinet! thanks for letting us know about this! this Pr - https://github.com/DataDog/documentation/pull/9058 - should fix this issue.
