### ISSUE TITLE
Code snippet for json-log-formatter is incorrect

### ISSUE THREAD

**Issue by rbusquet** [DataDog/documentation#8781]
## Documentation Page

https://docs.datadoghq.com/logs/log_collection/python/?tab=json_logformatter

## Issue Description

Code snippet is referencing python-json-logger instead of json-log-formatter.

Looks like this was caused by #8667

**Comment by sarina-dd** [comment]
Thanks for catching that, @rbusquet! Submitting a fix for this now. 👍

**Comment by rbusquet** [comment]
the snippet for #8802 is still incorrect. The API for JSON-log-formatter is different from python-json-logger.

Apologize if there will be more work in that PR to fix the snippet.

Thanks for the response!

**Comment by sarina-dd** [comment]
Hi @rbusquet, I made some changes and this issue is resolved now!

Thanks,
Sarina
