### ISSUE TITLE
Configure C# logger

### ISSUE THREAD

**Issue by mdhakecha** [DataDog/documentation#8845]
https://docs.datadoghq.com/logs/log_collection/csharp/?tab=log4net
i tried to integrate in .net framework project but not getting log entries in log.json file.  please help me how can i make it workable.

**Comment by apigirl** [comment]
Hi @mdhakecha,

Feel free to reach out to our [awesome support team](https://docs.datadoghq.com/help/) - they can definitely help you get this sorted out. Since this isn't docs specific feedback, I am going to close this issue.

Kaylyn
