### ISSUE TITLE
Broken link 

### ISSUE THREAD

**Issue by sutekar** [DataDog/documentation#8984]
There is broken link and needs to be updated here on https://github.com/DataDog/documentation/blob/master/content/en/integrations/faq/snmp.md under Further Reading section

For SNMP, does Datadog have a list of commonly used/compatible OIDs? this leads to https://github.com/DataDog/documentation/blob/master/integrations/faq/for-snmp-does-datadog-have-a-list-of-commonly-used-compatible-oids. The link attached returns 404.

**Comment by kayayarai** [comment]
Hi @sutekar The content of the docs, including all the relative links in them, is intended to be used within the official Datadog docs site (https://docs.datadoghq.com), not github. So none of the relative links on this page (for example, "custom metrics") work here. View it in the full docs site at: https://docs.datadoghq.com/integrations/faq/snmp/ where the link to the OIDs page does work. Hope that helps!
