### ISSUE TITLE
How to submit lots of related events

### ISSUE THREAD

**Issue by clofresh** [DataDog/documentation#9]
* various event inputs
* aggregation key

**Comment by technovangelist** [comment]
Hi @clofresh 

Are you referring to doing this in the api?

**Comment by clofresh** [comment]
Yeah, so the api describes how to send events in general, and most people will spam themselves with tons of related events without realizing that they can collapse related events together using the aggregation key.

**Comment by technovangelist** [comment]
thanks. I will update this in the documentation.

**Comment by irabinovitch** [comment]
@technovangelist  Did we do this?
