### ISSUE TITLE
Question about "\dd_trace_peek_span_id" and "\DDTrace\trace_id"

### ISSUE THREAD

**Issue by carltondickson** [DataDog/documentation#9441]
## Documentation Page

https://github.com/DataDog/documentation/commit/b9391ecf7dfc67ccb0ae51737d7ab74a336a8b4a#diff-0f9f0d742e866cd305e7300c5c4cb5da8f0d6ae044f01a0fc61dcade20c340bc

https://github.com/DataDog/documentation/commit/92f3c8812c9a5c6e62067e3fe9c31b0dd5a3f8d8#diff-0f9f0d742e866cd305e7300c5c4cb5da8f0d6ae044f01a0fc61dcade20c340bc

## Issue Description

Hi, I've managed to collect logs for a Laravel application on Heroku using the instructions defined here - https://docs.datadoghq.com/logs/log_collection/php/?tab=phpmonolog

Over the last few releases the example has changed slightly and just wanted to understand if there's a benefit of to using `\dd_trace_peek_span_id()` and `\DDTrace\trace_id()`?

I'm assuming if these are functions defined by the ddtrace extension they will be faster? Any other benefits?

I just have a smallish issue in that ddtrace not defined in our homestead dev environment so these examples will fail with function not defined. So ended up using a workaround for local dev for the span_id, but will add one for trace id as that just changed too. as of 0.53

`$span_id = function_exists('\dd_trace_peek_span_id') ? \dd_trace_peek_span_id() : $span->getSpanId();`

**Comment by apigirl** [comment]
Hi @carltondickson,

Feel free to reach out to our [awesome support team](https://docs.datadoghq.com/help/) - they can definitely help you understand the benefits and updates here. Since this isn't docs specific feedback, I am going to close this issue.

Kaylyn
