### ISSUE TITLE
502 Bad Gateway error with REST API

### ISSUE THREAD

**Issue by devappkr** [DataDog/documentation#9470]
**Describe the bug**
502 "Bad Gateway" error occurs when request POST from REST API

          ```
URL = [ "https://api.datadoghq.com/api/v1/logs-queries/list", 'https://api.datadoghq.com/api/v2/logs/events/search']
          headers = {'DD-API-KEY': api_key, 'DD-APPLICATION-KEY': app_key}
          ```
          data = {
                        "index": "*",
                        "limit": "100",
                        "query": "service:prd-*",
                        "sort": "desc",
                        # "startAt": "string",
                        "time": {
                          "from": "2021-01-013T01:02:02Z",
                          "timezone": "Asia/Seoul",
                          "to": "2021-01-01T13:09:20Z"
                        }
                      }
```

response
        `'{"status":"error","code":502,"errors":["Bad Gateway"],"statuspage":"http://status.datadoghq.com","twitter":"http://twitter.com/datadogops","email":"support@datadoghq.com"}\n'
`

**Comment by apigirl** [comment]
Hi @devappkr,

Feel free to reach out to our [awesome support team](https://docs.datadoghq.com/help/) - they can definitely help you get this sorted out. Since this isn't docs specific feedback, I am going to close this issue.

Kaylyn
