### ISSUE TITLE
No documentation for nginx tracing variables 

### ISSUE THREAD

**Issue by verdie-g** [DataDog/documentation#9562]
## Documentation Page

[Tracing a Proxy](https://docs.datadoghq.com/tracing/setup_overview/proxy_setup/?tab=nginx).

## Issue Description

Hello, I think it would be great to add two words about the tracing variables available in a nginx configuration file to format a log: `$opentracing_context_x_datadog_trace_id` and `$opentracing_context_x_datadog_parent_id`. These variables are present in the[ full example](https://github.com/DataDog/dd-opentracing-cpp/blob/master/examples/nginx-tracing/nginx.conf#L18) but there are not mentioned in the documentation. It's easy to guess that `opentracing_context_x_datadog_trace_id` should be mapped to the trace id in a log pipeline but I'm not sure what `$opentracing_context_x_datadog_parent_id` is used for.

**Comment by kayayarai** [comment]
Hi Grégoire, thanks for pointing this out. I'll look into what the `parent_id` might be used for, and will add this to our docs backlog.

**Comment by kayayarai** [comment]
Update: `opentracing_context_x_datadog_parent_id` should be mapped to the span id. I have added a description of both these variables in the NGINX proxy setup page you linked to. Thank you for reporting the missing information .
