### ISSUE TITLE
Could we update the AWS setup process doc?

### ISSUE THREAD

**Issue by tmichelet** [DataDog/documentation#961]
We released a fix that prevents people from using keys for new accounts except in China and GovCloud. We make it clear on the [AWS tile](https://app.datadoghq.com/account/settings#integrations/amazon_web_services)

<img width="569" alt="screen shot 2016-09-13 at 10 00 41 am" src="https://cloud.githubusercontent.com/assets/1532259/18476662/f20cb470-7998-11e6-8c13-f260c9d0d156.png">

Could we update the documentation to relate that?

Thanks!

**Comment by jyee** [comment]
Trello card at https://trello.com/c/AjaptbLy/1135-update-aws-setup-docs

**Comment by technovangelist** [comment]
https://github.com/DataDog/documentation/pull/981
