### ISSUE TITLE
Update SAML guide

### ISSUE THREAD

**Issue by samanthadrago** [DataDog/documentation#977]
This doc needs two updates:

- Updated screenshots (as of 9/21 there is a new SAML ui)
- Update/remove "Additional features on request" section. Users can now configure these features through the UI and do not need to request them through support. Maybe add a section about "Additional features" and what each of them do, with screenshots.

Thanks!

**Comment by technovangelist** [comment]
Thanks @samanthadrago . will get this added to our list.

**Comment by technovangelist** [comment]
addressed in #978
