### ISSUE TITLE
Broken image on GCP Load Balancing Page

### ISSUE THREAD

**Issue by jlosito** [DataDog/documentation#9795]
**Describe the bug**

There exists a broken image link on the page below. The page makes reference to an image under step 3 of the log collection section, "Export Google Cloud Pub/Sub Logs to Pub Sub", but when clicking the image it leads me to nowhere useful.

Below is the link to the page with the broken link.

https://docs.datadoghq.com/integrations/google_cloud_loadbalancing/

**To Reproduce**
1. Go to https://docs.datadoghq.com/integrations/google_cloud_loadbalancing/
2. Click on image under step 3 of Log collection.
3. See error

**Expected behavior**

The link resolve to a useful image.

**Screenshots**

![Screen Shot 2021-02-16 at 12 14 05 PM](https://user-images.githubusercontent.com/25142529/108097696-79515500-7050-11eb-825c-3acd02b39158.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7
 - Browser : chrome
 - Version: 88.0.4324.150

**Comment by apigirl** [comment]
Hi @jlosito - thanks for pointing this out and thanks for describing in so much detail! This is sourced from an internal repo and I removed the image for now. The update should deploy and go live within a couple of hours.
