### ISSUE TITLE
list-your-managed-organizations endpoint does not return a list of managed orgs 

### ISSUE THREAD

**Issue by vibrantlife** [DataDog/documentation#9830]
## Documentation Page
https://docs.datadoghq.com/api/latest/organizations/#list-your-managed-organizations

## Issue Description
This endpoint describes the return value of this endpoint as a list of managed orgs, however the endpoint only returns data for the parent org. This was acknowledged by the team that manages this endpoint (#support-aaa) in [this slack thread](https://dd.slack.com/archives/CGZ80PVQF/p1613488802276400). While they work on a resolution, can we remove this endpoint from the documentation? 
[relevant customer escalation](https://datadoghq.atlassian.net/browse/WEBPS-3054) that lead to this request. They expected to see a response with all of the data from the org.

CC: @agnesjang98 from #aaa-team

**Comment by urseberry** [comment]
It's not appropriate to remove the endpoint, but I am in the process of updating the description to indicate that it only returns info on the parent org.
