### ISSUE TITLE
Allow customization of the OOTB dashboard of hosts in Host Map

### ISSUE THREAD

**Issue by victorsosaio** [DataDog/documentation#9850]
**Is your feature request related to a problem? No

**Describe the solution you'd like**
I want to customize the OOTB host dashboard. My goal is to be able to look at a host in the host map, select it and then click the Dashboard link. This will redirect me to the dashboard and then I want to see the OOTB dashboard plus other widgets needed by my team to have a more granular view on other integrations, not just CPU or Memory.

**Describe alternatives you've considered**
I've tried to update the host dashboard but since it's read-only I'm not able to do it.

**Additional context**
N/A

**Comment by apigirl** [comment]
Hi @victorsosaio ,

Feel free to reach out to our [awesome support team](https://docs.datadoghq.com/help/) - they can definitely help you get this sorted out. Since this isn't docs specific feedback, I am going to close this issue.

Kaylyn
