### ISSUE TITLE
 'JMX metrics via Java Tracing Agent' link is broken

### ISSUE THREAD

**Issue by mcculls** [DataDog/documentation#9852]
**Describe the bug**
The 'JMX metrics via Java Tracing Agent' link on https://docs.datadoghq.com/integrations/java/ is broken and leads to a 404

**To Reproduce**
1. Go to https://docs.datadoghq.com/integrations/java/
2. Scroll down to the link that says 'JMX metrics via Java Tracing Agent'
3. Click on that link (https://docs.datadoghq.com/integrations/java/14)
4. 404 :(

**Expected behavior**
I _think_ https://docs.datadoghq.com/tracing/runtime_metrics/java/ is the page it's supposed to link to

**Additional notes**
There's also a spelling mistake on the first line of https://docs.datadoghq.com/integrations/java/
> The Java integration allows you to collects metrics, traces, and logs from your Java application.

it should be `collect` and not `collects`

**Comment by apigirl** [comment]
Hey there, thanks for letting us know about this! I just pushed an update and it should be live on the site in the next few hours.
