### ISSUE TITLE
Unclear where DD_TRACE_SAMPLE_RATE needs to be set

### ISSUE THREAD

**Issue by heyLu** [DataDog/documentation#9893]
## Documentation Page

- https://docs.datadoghq.com/tracing/trace_search_and_analytics/#recommended-enable-tracing-without-limits
- https://docs.datadoghq.com/tracing/trace_retention_and_ingestion/#recommended-setting-the-global-ingestion-rate-to-100

## Issue Description

From the documentation it is not clear to me whether `DD_TRACE_SAMPLE_RATE` needs to be set at the Datadog Agent level or for each service.  I am guessing it needs to be set for each service, but of the setup docs per language only the [php one](https://docs.datadoghq.com/tracing/setup_overview/setup/php/?tab=containers) mentions as a possible parameter.

Should I open a PR to:

- add the parameter to the setup instructions for the other languages
- mention that it needs to be added to the environment of each service (if that is the case)

**Comment by kayayarai** [comment]
Hello, Luna. Thank you for this feedback. I've added the work of checking with the development team and making the update to our backlog, and we will address it.

**Comment by kayayarai** [comment]
Hi Luna. Finally getting around to doing some research on this. The config setting `DD_TRACE_SAMPLE_RATE` is made at the _tracer_ level, and it applies to all the services there. Some tracers (C++, .NET, Java, PHP, Python) also have DD_TRACE_SAMPLING_RULES which lets you pass in specific services and a rate for each one, if you want them different from the tracer-level rate. You are correct in your observation that only PHP and C++ have this documented, and I am looking into whether engineering wants it added to the other library docs.

**Comment by kayayarai** [comment]
Cleaning up old issues, noticed this one. This is pretty thoroughly documented here now: https://docs.datadoghq.com/tracing/trace_pipeline/ingestion_mechanisms/
