### ISSUE TITLE
missing project: logstash-output-dogstatsd

### ISSUE THREAD

**Issue by FlorinAndrei** [DataDog/documentation#993]
On this page...

http://docs.datadoghq.com/libraries/

...for the Logstash Output libs the official datadog output plugin is mentioned. But there's no mention of the dogstatsd output plugin for Logstash:

https://github.com/brigade/logstash-output-dogstatsd

The dogstatsd plugin is non-blocking, which is important currently since Logstash still only has a single data pipeline, and a blocking output plugin (like the official Datadog plugin) could block all outputs, creating all sorts of problems - which has happened to us recently.

The statsd-based plugin is non-blocking and handles pretty well a high volume of data. Please add it to the list.

**Comment by l0k0ms** [comment]
Hello, 

Documentation has been updated.

Thank you very much for your feedback.
