### ISSUE TITLE
PCI Compliance Vulnerability is Software

### ISSUE THREAD

**Issue by VinodVerma7584** [DataDog/documentation#9961]
**Describe the bug**
DataDog Software is not PCI Compliant

**To Reproduce**
Our Reports says they have 2 vulnerability as below,

SSL/TLS Server supports TLSv1.1
Host is Vulnerable to Extended Master Secret TLS Extension (TLS triple handshake)

TLSv1.1 is supported#
--
Host:10.3.191.48:9090   is vulnerable to TLS triple handshake#

Can you please fix this issues ASAP?

**Comment by apigirl** [comment]
Hi @VinodVerma7584 ,

Feel free to reach out to our [awesome support team](https://docs.datadoghq.com/help/) - they can definitely help you get this sorted out. Since this isn't docs specific feedback, I am going to close this issue.

Kaylyn
