### ISSUE TITLE
add custom subdomain to my org

### ISSUE THREAD

**Issue by kangko** [DataDog/documentation#9965]
## Issue Description
We have an org called Agent Profile Manager.  I'd like to assign the custom subdomain below to it.

rlgy-apm.datadoghq.com

**Comment by apigirl** [comment]
Hi @kangko ,

If you haven't yet, please feel free to reach out to our [awesome support team](https://docs.datadoghq.com/help/) - they can definitely help you get this sorted out.

Kaylyn
