### ISSUE TITLE
Nested JSON Parsing

### ISSUE THREAD

**Issue by shawn2306** [DataDog/documentation#9992]
## Issue Description
So we have a nested JSON formatted log file where we have all the KPI's that we are pushing to DataDog.

**Comment by apigirl** [comment]
Hi @shawn2306,

Feel free to reach out to our [awesome support team](https://docs.datadoghq.com/help/) - they can definitely help you get this sorted out. Since this isn't docs specific feedback, I am going to close this issue.

Kaylyn
