### ISSUE TITLE
Syslog_ng integration doc missing informations for EU Site 

### ISSUE THREAD

**Issue by loitho** [DataDog/documentation#9996]
**Describe the bug**
Hi Datadog Team,

There is a disparity between the US and EU datadog documentation on the syslog-ng integration.
The EU documentation is missing the section for adding metadata tags to the logs in the DatadogTemplate example.

**To Reproduce**
1. Go to https://docs.datadoghq.com/integrations/syslog_ng/?tab=datadogussite#pagetitle
2. Go to https://docs.datadoghq.com/integrations/syslog_ng/?tab=datadogeusite#pagetitle
3. Check the 2 pages and you'll see the EU Site is missing the "(Optional) Set the source" section, explaining how to add custom tags and source

**Expected behavior**
Same Documentation for both sites

Thanks !

**Comment by apigirl** [comment]
Hi @loitho! 

Thanks for letting us know about this, we'll investigate! Also know that you can use our site selector to see any docs page with EU information. 
![image](https://user-images.githubusercontent.com/28788585/110831428-76b0dc80-8257-11eb-87f0-2837ca435ae9.png)

Kaylyn

**Comment by aronday** [comment]
Both US & EU now have the same information.
