### ISSUE TITLE
I'm trying to setup the Integration "Amazon Managed Streaming for Apache Kafka (Amazon MSK) Integration" but I'm not able to find any metric yet on the Metrics Explorer

### ISSUE THREAD

**Issue by rever-carlos** [DataDog/documentation#9998]
## Documentation Page

https://app.datadoghq.com/account/settings#integrations/amazon-kafka

## Issue Description

I'm trying to setup the Integration "Amazon Managed Streaming for Apache Kafka (Amazon MSK) Integration" but I'm not able to find any metric yet on the Metrics Explorer

I already set the only required field (the cluster_arn) in the file:
`/etc/datadog-agent/conf.d/amazon_msk.d/conf.yaml`

**Comment by apigirl** [comment]
Hi @rever-carlos,

Feel free to reach out to our [awesome support team](https://docs.datadoghq.com/help/) - they can definitely help you get this sorted out. Since this isn't docs specific feedback, I am going to close this issue.

Kaylyn
